import type {CatalogueFact, CatalogueRecord, CatalogueRecordType} from "./catalogue-types";

const dataAsOf = "Alpha 1 - 7 Aug 2026";
const betaDataAsOf = "Closed Beta - 21-23 Aug 2026";
const evidenceStatus = "pre-release-build" as const;
const betaSourceNotes = [
  "Cross-checked against dated Closed Beta catalogue footage and two community catalogue snapshots; values not visible in the footage remain unknown.",
] as const;
const identifierOnlyNotes = [
  "Identifier observed in a pre-release catalogue listing; no reliable price, calibre, handling, or unlock data was captured.",
] as const;

type CatalogueRecordInput = Omit<CatalogueRecord, "evidenceTier" | "mediaState" | "sourceNotes"> &
  Partial<Pick<CatalogueRecord, "evidenceTier" | "mediaState" | "sourceNotes">>;

const fact = (label: string, value: string): CatalogueFact => ({label, value});

const weaponRecords: readonly CatalogueRecordInput[] = [
  {slug: "a-91", name: "A-91", type: "weapons", subtype: "Assault rifle", image: "/images/catalogue/weapons/a-91.webp", imageAlt: "A-91 assault rifle", summary: "Assault XP rifle using 5.56x45mm with semi and burst fire.", facts: [fact("Alpha price", "Not captured"), fact("Ammunition", "5.56x45mm"), fact("Fire modes", "Semi / Burst"), fact("Weight", "3.17 kg"), fact("Progression", "Assault XP")], filterValues: ["assault-rifle", "assault-xp", "5-56x45mm"], detailStatus: "published", detailHref: "/items/weapons/a-91", evidenceStatus, dataAsOf},
  {slug: "ak74", name: "AK74", type: "weapons", subtype: "Assault rifle", image: "/images/catalogue/weapons/ak74.webp", imageAlt: "AK74 assault rifle", summary: "Assault XP rifle using 5.45x39mm with semi and full-auto fire.", facts: [fact("Alpha price", "Not captured"), fact("Ammunition", "5.45x39mm"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "3 kg"), fact("Progression", "Assault XP")], filterValues: ["assault-rifle", "assault-xp", "5-45x39mm"], detailStatus: "published", detailHref: "/items/weapons/ak74", evidenceStatus, dataAsOf},
  {slug: "amp-9", name: "AMP-9", type: "weapons", subtype: "SMG", image: "/images/catalogue/weapons/amp-9.webp", imageAlt: "AMP-9 submachine gun", summary: "Medic XP SMG using 9x19mm with semi and full-auto fire.", facts: [fact("Alpha price", "$900"), fact("Ammunition", "9x19mm"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "1.4 kg"), fact("Progression", "Medic XP")], filterValues: ["smg", "medic-xp", "9x19mm"], detailStatus: "published", detailHref: "/items/weapons/amp-9", evidenceStatus, dataAsOf},
  {slug: "amr-50", name: "AMR 50", type: "weapons", subtype: "Sniper rifle", image: "/images/catalogue/weapons/amr-50.webp", imageAlt: "AMR 50 sniper rifle", summary: "Recon XP sniper rifle using .50 Cal with bolt-action and magazine fire.", facts: [fact("Alpha price", "$8,800"), fact("Ammunition", ".50 Cal"), fact("Fire modes", "Bolt-action / Magazine"), fact("Weight", "12.5 kg"), fact("Progression", "Recon XP")], filterValues: ["sniper-rifle", "recon-xp", "50-cal"], detailStatus: "published", detailHref: "/items/weapons/amr-50", evidenceStatus, dataAsOf},
  {slug: "bmr-308", name: "BMR-308", type: "weapons", subtype: "Marksman rifle", image: "/images/catalogue/weapons/bmr-308.webp", imageAlt: "BMR-308 marksman rifle", summary: "Recon XP marksman rifle using .308 Winchester with semi-automatic fire.", facts: [fact("Alpha price", "$6,000"), fact("Ammunition", ".308 Winchester"), fact("Fire modes", "Semi automatic"), fact("Weight", "3.9 kg"), fact("Progression", "Recon XP")], filterValues: ["marksman-rifle", "recon-xp", "308-winchester"], detailStatus: "published", detailHref: "/items/weapons/bmr-308", evidenceStatus, dataAsOf},
  {slug: "bushmaster-m17s", name: "Bushmaster M17S", type: "weapons", subtype: "Assault rifle", image: "/images/catalogue/weapons/bushmaster-m17s.webp", imageAlt: "Bushmaster M17S assault rifle", summary: "Assault XP rifle using 5.56x45mm with semi and burst fire.", facts: [fact("Alpha price", "$0"), fact("Ammunition", "5.56x45mm"), fact("Fire modes", "Semi / Burst"), fact("Weight", "3.17 kg"), fact("Progression", "Assault XP")], filterValues: ["assault-rifle", "assault-xp", "5-56x45mm"], detailStatus: "published", detailHref: "/items/weapons/bushmaster-m17s", evidenceStatus, dataAsOf},
  {slug: "compound-bow", name: "Compound Bow", type: "weapons", subtype: "Bow", image: "/images/catalogue/weapons/compound-bow.webp", imageAlt: "Compound bow", summary: "Recon XP bow using Standard Arrows with pull-and-release fire.", facts: [fact("Alpha price", "$800"), fact("Ammunition", "Standard Arrows"), fact("Fire modes", "Pull and Release"), fact("Weight", "1.3 kg"), fact("Progression", "Recon XP")], filterValues: ["bow", "recon-xp", "standard-arrows"], detailStatus: "published", detailHref: "/items/weapons/compound-bow", evidenceStatus, dataAsOf},
  {slug: "deagle", name: "Deagle", type: "weapons", subtype: "Sidearm", image: "/images/catalogue/weapons/deagle.webp", imageAlt: "Deagle sidearm", summary: "Sidearm using .50 AE with semi-automatic fire.", facts: [fact("Alpha price", "$900"), fact("Ammunition", ".50 AE"), fact("Fire modes", "Semi automatic"), fact("Weight", "Not captured"), fact("Progression", "Not captured")], filterValues: ["sidearm", "50-ae"], detailStatus: "published", detailHref: "/items/weapons/deagle", evidenceStatus, dataAsOf},
  {slug: "fal", name: "FAL", type: "weapons", subtype: "Assault rifle", image: "/images/catalogue/weapons/fal.webp", imageAlt: "FAL assault rifle", summary: "Assault XP rifle using .308 Winchester with semi and full-auto fire.", facts: [fact("Alpha price", "$5,500"), fact("Ammunition", ".308 Winchester"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "4.25 kg"), fact("Progression", "Assault XP")], filterValues: ["assault-rifle", "assault-xp", "308-winchester"], detailStatus: "published", detailHref: "/items/weapons/fal", evidenceStatus, dataAsOf},
  {slug: "galil", name: "Galil", type: "weapons", subtype: "Assault rifle", image: "/images/catalogue/weapons/galil.webp", imageAlt: "Galil assault rifle", summary: "Assault XP rifle using 5.56x45mm with semi and full-auto fire.", facts: [fact("Alpha price", "$2,200"), fact("Ammunition", "5.56x45mm"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "3.95 kg"), fact("Progression", "Assault XP")], filterValues: ["assault-rifle", "assault-xp", "5-56x45mm"], detailStatus: "published", detailHref: "/items/weapons/galil", evidenceStatus, dataAsOf},
  {slug: "ggx-17", name: "GGX 17", type: "weapons", subtype: "Sidearm", image: "/images/catalogue/weapons/ggx-17.webp", imageAlt: "GGX 17 sidearm", summary: "Sidearm using 9x19mm with semi-automatic fire.", facts: [fact("Alpha price", "Not captured"), fact("Ammunition", "9x19mm"), fact("Fire modes", "Semi automatic"), fact("Weight", "Not captured"), fact("Progression", "Not captured")], filterValues: ["sidearm", "9x19mm"], detailStatus: "published", detailHref: "/items/weapons/ggx-17", evidenceStatus, dataAsOf},
  {slug: "ggx-18", name: "GGX 18", type: "weapons", subtype: "Sidearm", image: "/images/catalogue/weapons/ggx-18.webp", imageAlt: "GGX 18 sidearm", summary: "Sidearm using 9x19mm with semi and full-auto fire.", facts: [fact("Alpha price", "Not captured"), fact("Ammunition", "9x19mm"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "Not captured"), fact("Progression", "Not captured")], filterValues: ["sidearm", "9x19mm"], detailStatus: "published", detailHref: "/items/weapons/ggx-18", evidenceStatus, dataAsOf},
  {slug: "judge", name: "Judge", type: "weapons", subtype: "Sidearm", image: "/images/catalogue/weapons/judge.webp", imageAlt: "Judge sidearm", summary: "Sidearm using .45 Colt; fire mode, weight, and progression were not captured.", facts: [fact("Alpha price", "$250"), fact("Ammunition", ".45 Colt"), fact("Fire modes", "Not captured"), fact("Weight", "Not captured"), fact("Progression", "Not captured")], filterValues: ["sidearm", "45-colt"], detailStatus: "published", detailHref: "/items/weapons/judge", evidenceStatus, dataAsOf},
  {slug: "kh-2002", name: "KH-2002", type: "weapons", subtype: "Assault rifle", image: "/images/catalogue/weapons/kh-2002.webp", imageAlt: "KH-2002 assault rifle", summary: "Assault XP rifle using 5.56x45mm with semi and burst fire.", facts: [fact("Alpha price", "Not captured"), fact("Ammunition", "5.56x45mm"), fact("Fire modes", "Semi / Burst"), fact("Weight", "3.17 kg"), fact("Progression", "Assault XP")], filterValues: ["assault-rifle", "assault-xp", "5-56x45mm"], detailStatus: "published", detailHref: "/items/weapons/kh-2002", evidenceStatus, dataAsOf},
  {slug: "m4", name: "M4", type: "weapons", subtype: "Assault rifle", image: "/images/catalogue/weapons/m4.webp", imageAlt: "M4 rifle shown in official WARDOGS gameplay", summary: "Assault XP rifle observed with 5.56x45mm ammunition and semi or full-auto fire in Alpha 1.", facts: [fact("Alpha price", "$2,800"), fact("Ammunition", "5.56x45mm"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "2.92 kg"), fact("Progression", "Assault XP")], filterValues: ["assault-rifle", "assault-xp", "5-56x45mm"], detailStatus: "published", detailHref: "/items/weapons/m4", evidenceStatus, evidenceTier: "official", mediaState: "verified", sourceNotes: ["Official Team17 press-kit gameplay frame identifies the equipped M4 in the HUD; Alpha values remain build-sensitive and use the separate catalogue evidence set."], dataAsOf: betaDataAsOf},
  {slug: "t-21", name: "T-21", type: "weapons", subtype: "Assault rifle", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "T-21 image verification pending", summary: "Assault XP rifle observed with 5.56x45mm ammunition and semi or full-auto fire in Alpha 1.", facts: [fact("Alpha price", "$600"), fact("Ammunition", "5.56x45mm"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "3.27 kg"), fact("Progression", "Assault XP")], filterValues: ["assault-rifle", "assault-xp", "5-56x45mm"], detailStatus: "published", detailHref: "/items/weapons/t-21", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "m249-saw", name: "M249 SAW", type: "weapons", subtype: "LMG", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "M249 SAW image verification pending", summary: "Support XP light machine gun using 5.56x45mm; price was not captured in the observed build.", facts: [fact("Alpha price", "Not captured"), fact("Ammunition", "5.56x45mm"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "7.5 kg"), fact("Progression", "Support XP")], filterValues: ["lmg", "support-xp", "5-56x45mm"], detailStatus: "published", detailHref: "/items/weapons/m249-saw", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "pkm", name: "PKM", type: "weapons", subtype: "LMG", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "PKM image verification pending", summary: "Support XP light machine gun observed with 7.62x54mmR ammunition and full-auto capability.", facts: [fact("Alpha price", "$4,500"), fact("Ammunition", "7.62x54mmR"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "7.5 kg"), fact("Progression", "Support XP")], filterValues: ["lmg", "support-xp", "7-62x54mmr"], detailStatus: "published", detailHref: "/items/weapons/pkm", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "sks", name: "SKS", type: "weapons", subtype: "Marksman rifle", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "SKS image verification pending", summary: "Recon XP semi-automatic marksman rifle using 7.62x39mm ammunition.", facts: [fact("Alpha price", "$2,400"), fact("Ammunition", "7.62x39mm"), fact("Fire modes", "Semi automatic"), fact("Weight", "3.85 kg"), fact("Progression", "Recon XP")], filterValues: ["marksman-rifle", "recon-xp", "7-62x39mm"], detailStatus: "published", detailHref: "/items/weapons/sks", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "svd", name: "SVD", type: "weapons", subtype: "Marksman rifle", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "SVD image verification pending", summary: "Recon XP semi-automatic marksman rifle using 7.62x54mmR ammunition.", facts: [fact("Alpha price", "$4,800"), fact("Ammunition", "7.62x54mmR"), fact("Fire modes", "Semi automatic"), fact("Weight", "5.3 kg"), fact("Progression", "Recon XP")], filterValues: ["marksman-rifle", "recon-xp", "7-62x54mmr"], detailStatus: "published", detailHref: "/items/weapons/svd", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "m1911", name: "M1911", type: "weapons", subtype: "Sidearm", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "M1911 image verification pending", summary: "Semi-automatic .45 ACP sidearm observed in the pre-release catalogue.", facts: [fact("Alpha price", "$300"), fact("Ammunition", ".45 ACP"), fact("Fire modes", "Semi automatic"), fact("Weight", "Not captured"), fact("Progression", "Not captured")], filterValues: ["sidearm", "45-acp"], detailStatus: "published", detailHref: "/items/weapons/m1911", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "m500", name: "M500", type: "weapons", subtype: "Shotgun", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "M500 image verification pending", summary: "Support XP 12 Gauge shotgun observed in the pre-release catalogue.", facts: [fact("Alpha price", "Not captured"), fact("Ammunition", "12 Gauge"), fact("Fire modes", "Semi automatic"), fact("Weight", "3.52 kg"), fact("Progression", "Support XP")], filterValues: ["shotgun", "support-xp", "12-gauge"], detailStatus: "published", detailHref: "/items/weapons/m500", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "mp43", name: "MP43", type: "weapons", subtype: "Shotgun", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "MP43 image verification pending", summary: "Support XP break-action 12 Gauge shotgun observed as a low-cost option.", facts: [fact("Alpha price", "$400"), fact("Ammunition", "12 Gauge"), fact("Fire modes", "Break-action"), fact("Weight", "3.2 kg"), fact("Progression", "Support XP")], filterValues: ["shotgun", "support-xp", "12-gauge"], detailStatus: "published", detailHref: "/items/weapons/mp43", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "mp5", name: "MP5", type: "weapons", subtype: "SMG", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "MP5 image verification pending", summary: "Medic XP SMG using 9x19mm ammunition with semi and full-auto fire.", facts: [fact("Alpha price", "$1,500"), fact("Ammunition", "9x19mm"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "2.54 kg"), fact("Progression", "Medic XP")], filterValues: ["smg", "medic-xp", "9x19mm"], detailStatus: "published", detailHref: "/items/weapons/mp5", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "pp-19-vityaz", name: "PP-19 Vityaz", type: "weapons", subtype: "SMG", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "PP-19 Vityaz image verification pending", summary: "Medic XP SMG using 9x19mm ammunition with semi and full-auto fire.", facts: [fact("Alpha price", "$1,200"), fact("Ammunition", "9x19mm"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "2.9 kg"), fact("Progression", "Medic XP")], filterValues: ["smg", "medic-xp", "9x19mm"], detailStatus: "published", detailHref: "/items/weapons/pp-19-vityaz", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "super-45", name: "Super-45", type: "weapons", subtype: "SMG", image: "/images/catalogue/weapons/super-45.webp", imageAlt: "Super-45 SMG shown in official WARDOGS gameplay", summary: "Medic XP SMG using .45 ACP ammunition with semi and full-auto fire.", facts: [fact("Alpha price", "Not captured"), fact("Ammunition", ".45 ACP"), fact("Fire modes", "Semi / Full Auto"), fact("Weight", "3 kg"), fact("Progression", "Medic XP")], filterValues: ["smg", "medic-xp", "45-acp"], detailStatus: "published", detailHref: "/items/weapons/super-45", evidenceStatus, evidenceTier: "official", mediaState: "verified", sourceNotes: ["Official Team17 press-kit gameplay frame identifies the equipped Super-45 and .45 ACP ammunition in the HUD; Alpha values remain build-sensitive and use the separate catalogue evidence set."], dataAsOf: betaDataAsOf},
  {slug: "mk22", name: "MK22", type: "weapons", subtype: "Sniper rifle", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "MK22 image verification pending", summary: "Recon XP bolt-action sniper rifle using .308 Winchester ammunition.", facts: [fact("Alpha price", "$6,400"), fact("Ammunition", ".308 Winchester"), fact("Fire modes", "Bolt-action / Magazine"), fact("Weight", "6.3 kg"), fact("Progression", "Recon XP")], filterValues: ["sniper-rifle", "recon-xp", "308-winchester"], detailStatus: "published", detailHref: "/items/weapons/mk22", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "mosin-nagant", name: "Mosin Nagant", type: "weapons", subtype: "Sniper rifle", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "Mosin Nagant image verification pending", summary: "Recon XP bolt-action sniper rifle using 7.62x54mmR ammunition.", facts: [fact("Alpha price", "$4,500"), fact("Ammunition", "7.62x54mmR"), fact("Fire modes", "Bolt action"), fact("Weight", "4.1 kg"), fact("Progression", "Recon XP")], filterValues: ["sniper-rifle", "recon-xp", "7-62x54mmr"], detailStatus: "published", detailHref: "/items/weapons/mosin-nagant", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "scout-rifle-td", name: "Scout Rifle TD", type: "weapons", subtype: "Sniper rifle", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "Scout Rifle TD image verification pending", summary: "Recon XP light break-action rifle using 5.56x45mm ammunition.", facts: [fact("Alpha price", "$1,100"), fact("Ammunition", "5.56x45mm"), fact("Fire modes", "Break-action"), fact("Weight", "2.95 kg"), fact("Progression", "Recon XP")], filterValues: ["sniper-rifle", "recon-xp", "5-56x45mm"], detailStatus: "published", detailHref: "/items/weapons/scout-rifle-td", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "sv98", name: "SV98", type: "weapons", subtype: "Sniper rifle", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "SV98 image verification pending", summary: "Recon XP bolt-action sniper rifle using 7.62x54mmR ammunition.", facts: [fact("Alpha price", "$5,200"), fact("Ammunition", "7.62x54mmR"), fact("Fire modes", "Bolt-action / Magazine"), fact("Weight", "5.8 kg"), fact("Progression", "Recon XP")], filterValues: ["sniper-rifle", "recon-xp", "7-62x54mmr"], detailStatus: "published", detailHref: "/items/weapons/sv98", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "9k333-verba", name: "9K333 Verba", type: "weapons", subtype: "Launcher", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "9K333 Verba image verification pending", summary: "Specialist launcher identified in Closed Beta catalogue coverage; exact ammunition, price, and unlock remain unconfirmed.", facts: [fact("Closed Beta price", "Not captured"), fact("Ammunition", "Not captured"), fact("Role", "Anti-air launcher")], filterValues: ["launcher", "anti-air"], detailStatus: "published", detailHref: "/items/weapons/9k333-verba", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "maaws", name: "MAAWS", type: "weapons", subtype: "Launcher", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "MAAWS image verification pending", summary: "84mm specialist launcher observed in pre-release catalogue coverage.", facts: [fact("Alpha price", "Not captured"), fact("Ammunition", "84mm"), fact("Role", "Anti-vehicle launcher")], filterValues: ["launcher", "anti-vehicle", "84mm"], detailStatus: "published", detailHref: "/items/weapons/maaws", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "mgl-40", name: "MGL-40", type: "weapons", subtype: "Launcher", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "MGL-40 image verification pending", summary: "40mm multiple grenade launcher observed in pre-release catalogue coverage.", facts: [fact("Alpha price", "Not captured"), fact("Ammunition", "40mm"), fact("Role", "Grenade launcher")], filterValues: ["launcher", "grenade-launcher", "40mm"], detailStatus: "published", detailHref: "/items/weapons/mgl-40", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "rpg-7", name: "RPG-7", type: "weapons", subtype: "Launcher", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "RPG-7 image verification pending", summary: "93mm specialist launcher observed in the Alpha catalogue.", facts: [fact("Alpha price", "$2,000"), fact("Ammunition", "93mm"), fact("Role", "Anti-vehicle launcher")], filterValues: ["launcher", "anti-vehicle", "93mm"], detailStatus: "published", detailHref: "/items/weapons/rpg-7", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "m12g", name: "M12G", type: "weapons", subtype: "Identifier only", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "M12G image verification pending", summary: "M12G appears as a pre-release weapon identifier, but reliable role and numeric fields were not captured.", facts: [fact("Build", "Closed Beta"), fact("Verification", "Identifier only")], filterValues: ["identifier-only"], detailStatus: "inline", evidenceStatus, evidenceTier: "identifier-only", mediaState: "pending", sourceNotes: identifierOnlyNotes, dataAsOf: betaDataAsOf},
  {slug: "at4", name: "AT4", type: "weapons", subtype: "Identifier only", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "AT4 image verification pending", summary: "AT4 appears as a pre-release weapon identifier, but reliable role and numeric fields were not captured.", facts: [fact("Build", "Closed Beta"), fact("Verification", "Identifier only")], filterValues: ["identifier-only"], detailStatus: "inline", evidenceStatus, evidenceTier: "identifier-only", mediaState: "pending", sourceNotes: identifierOnlyNotes, dataAsOf: betaDataAsOf},
  {slug: "browning-mg", name: "Browning MG", type: "weapons", subtype: "Identifier only", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "Browning MG image verification pending", summary: "Browning MG appears as a pre-release weapon identifier, but reliable role and numeric fields were not captured.", facts: [fact("Build", "Closed Beta"), fact("Verification", "Identifier only")], filterValues: ["identifier-only"], detailStatus: "inline", evidenceStatus, evidenceTier: "identifier-only", mediaState: "pending", sourceNotes: identifierOnlyNotes, dataAsOf: betaDataAsOf},
  {slug: "g60", name: "G60", type: "weapons", subtype: "Identifier only", image: "/images/catalogue/banners/weapons-1280.webp", imageAlt: "G60 image verification pending", summary: "G60 appears as a pre-release weapon identifier, but reliable role and numeric fields were not captured.", facts: [fact("Build", "Closed Beta"), fact("Verification", "Identifier only")], filterValues: ["identifier-only"], detailStatus: "inline", evidenceStatus, evidenceTier: "identifier-only", mediaState: "pending", sourceNotes: identifierOnlyNotes, dataAsOf: betaDataAsOf}
];

const vehicleRecords: readonly CatalogueRecordInput[] = [
  {slug: "ah-6m-miniguns", name: "AH-6M Miniguns", type: "vehicles", subtype: "Combat helicopter", image: "/images/catalogue/vehicles/ah-6m-miniguns.webp", imageAlt: "AH-6M Miniguns combat helicopter", summary: "Combat helicopter listed at $7,000; its Alpha gate was unreadable.", facts: [fact("Role", "Combat helicopter"), fact("Alpha price", "$7,000"), fact("Observed gate", "Gate unread"), fact("Track", "-")], filterValues: ["aircraft", "combat-helicopter", "gate-unread"], detailStatus: "published", detailHref: "/items/vehicles/ah-6m-miniguns", evidenceStatus, dataAsOf},
  {slug: "ah-6r-rockets", name: "AH-6R Rockets", type: "vehicles", subtype: "Rocket helicopter", image: "/images/catalogue/vehicles/ah-6r-rockets.webp", imageAlt: "AH-6R Rockets helicopter", summary: "Rocket helicopter listed at $12,500; its Alpha gate was unreadable.", facts: [fact("Role", "Rocket helicopter"), fact("Alpha price", "$12,500"), fact("Observed gate", "Gate unread"), fact("Track", "-")], filterValues: ["aircraft", "rocket-helicopter", "gate-unread"], detailStatus: "published", detailHref: "/items/vehicles/ah-6r-rockets", evidenceStatus, dataAsOf},
  {slug: "bobcat", name: "Bobcat", type: "vehicles", subtype: "Light transport", image: "/images/catalogue/vehicles/bobcat.webp", imageAlt: "Bobcat light transport", summary: "Light transport listed at $500 with open purchase observed in Alpha 1.", facts: [fact("Role", "Light transport"), fact("Alpha price", "$500"), fact("Observed gate", "Open purchase"), fact("Track", "-")], filterValues: ["land-transport", "light-transport", "open-purchase"], detailStatus: "published", detailHref: "/items/vehicles/bobcat", evidenceStatus, dataAsOf},
  {slug: "dune-buggy", name: "Dune Buggy", type: "vehicles", subtype: "Fast transport", image: "/images/catalogue/vehicles/dune-buggy.webp", imageAlt: "Dune Buggy fast transport", summary: "Fast transport listed at $1,500 with a Driver Level 10 gate.", facts: [fact("Role", "Fast transport"), fact("Alpha price", "$1,500"), fact("Observed gate", "Driver Level 10"), fact("Track", "Driver")], filterValues: ["land-transport", "fast-transport", "driver"], detailStatus: "published", detailHref: "/items/vehicles/dune-buggy", evidenceStatus, dataAsOf},
  {slug: "flakpanzer-gepard", name: "Flakpanzer Gepard", type: "vehicles", subtype: "Anti-air armor", image: "/images/catalogue/vehicles/flakpanzer-gepard.webp", imageAlt: "Flakpanzer Gepard anti-air armor", summary: "Anti-air armor listed at $8,000 with a Wardog Level 45 gate.", facts: [fact("Role", "Anti-air armor"), fact("Alpha price", "$8,000"), fact("Observed gate", "Wardog Level 45"), fact("Track", "Wardog")], filterValues: ["armor-and-artillery", "anti-air-armor", "wardog"], detailStatus: "published", detailHref: "/items/vehicles/flakpanzer-gepard", evidenceStatus, dataAsOf},
  {slug: "havoc", name: "Havoc", type: "vehicles", subtype: "Attack helicopter", image: "/images/catalogue/vehicles/havoc.webp", imageAlt: "Havoc attack helicopter", summary: "Attack helicopter listed at $18,000; its Alpha gate was unreadable.", facts: [fact("Role", "Attack helicopter"), fact("Alpha price", "$18,000"), fact("Observed gate", "Gate unread"), fact("Track", "-")], filterValues: ["aircraft", "attack-helicopter", "gate-unread"], detailStatus: "published", detailHref: "/items/vehicles/havoc", evidenceStatus, dataAsOf},
  {slug: "humvee-m249", name: "Humvee M249", type: "vehicles", subtype: "Armed transport", image: "/images/catalogue/vehicles/humvee-m249.webp", imageAlt: "Humvee M249 armed transport", summary: "Armed transport listed at $3,750 with a Driver Level 25 gate.", facts: [fact("Role", "Armed transport"), fact("Alpha price", "$3,750"), fact("Observed gate", "Driver Level 25"), fact("Track", "Driver")], filterValues: ["land-transport", "armed-transport", "driver"], detailStatus: "published", detailHref: "/items/vehicles/humvee-m249", evidenceStatus, dataAsOf},
  {slug: "humvee-minigun", name: "Humvee Minigun", type: "vehicles", subtype: "Heavy armed transport", image: "/images/catalogue/vehicles/humvee-minigun.webp", imageAlt: "Humvee Minigun heavy armed transport", summary: "Heavy armed transport listed at $4,500; its Alpha gate was unreadable.", facts: [fact("Role", "Heavy armed transport"), fact("Alpha price", "$4,500"), fact("Observed gate", "Gate unread"), fact("Track", "-")], filterValues: ["land-transport", "heavy-armed-transport", "gate-unread"], detailStatus: "published", detailHref: "/items/vehicles/humvee-minigun", evidenceStatus, dataAsOf},
  {slug: "humvee", name: "Humvee", type: "vehicles", subtype: "Protected transport", image: "/images/catalogue/vehicles/humvee.webp", imageAlt: "Humvee protected transport", summary: "Protected transport listed at $3,000 with a Driver Level 15 gate.", facts: [fact("Role", "Protected transport"), fact("Alpha price", "$3,000"), fact("Observed gate", "Driver Level 15"), fact("Track", "Driver")], filterValues: ["land-transport", "protected-transport", "driver"], detailStatus: "published", detailHref: "/items/vehicles/humvee", evidenceStatus, dataAsOf},
  {slug: "kodiak-m249", name: "Kodiak M249", type: "vehicles", subtype: "Armed transport", image: "/images/catalogue/vehicles/kodiak-m249.webp", imageAlt: "Kodiak M249 armed transport", summary: "Armed transport listed at $3,750 with a Driver Level 8 gate.", facts: [fact("Role", "Armed transport"), fact("Alpha price", "$3,750"), fact("Observed gate", "Driver Level 8"), fact("Track", "Driver")], filterValues: ["land-transport", "armed-transport", "driver"], detailStatus: "published", detailHref: "/items/vehicles/kodiak-m249", evidenceStatus, dataAsOf},
  {slug: "kodiak-pickup", name: "Kodiak Pickup", type: "vehicles", subtype: "Cargo transport", image: "/images/catalogue/vehicles/kodiak-pickup.webp", imageAlt: "Kodiak Pickup cargo transport", summary: "Cargo transport listed at $3,000 with a $15,000 unlock observed.", facts: [fact("Role", "Cargo transport"), fact("Alpha price", "$3,000"), fact("Observed gate", "$15,000 unlock"), fact("Track", "-")], filterValues: ["land-transport", "cargo-transport", "15-000-unlock"], detailStatus: "published", detailHref: "/items/vehicles/kodiak-pickup", evidenceStatus, dataAsOf},
  {slug: "kodiak", name: "Kodiak", type: "vehicles", subtype: "Utility transport", image: "/images/catalogue/vehicles/kodiak.webp", imageAlt: "Kodiak utility transport", summary: "Utility transport listed at $2,500 with open purchase observed in Alpha 1.", facts: [fact("Role", "Utility transport"), fact("Alpha price", "$2,500"), fact("Observed gate", "Open purchase"), fact("Track", "-")], filterValues: ["land-transport", "utility-transport", "open-purchase"], detailStatus: "published", detailHref: "/items/vehicles/kodiak", evidenceStatus, dataAsOf},
  {slug: "l2a6", name: "L2A6", type: "vehicles", subtype: "Main battle tank", image: "/images/catalogue/vehicles/l2a6.webp", imageAlt: "L2A6 main battle tank", summary: "Main battle tank listed at $14,000 with a Wardog Level 35 gate.", facts: [fact("Role", "Main battle tank"), fact("Alpha price", "$14,000"), fact("Observed gate", "Wardog Level 35"), fact("Track", "Wardog")], filterValues: ["armor-and-artillery", "main-battle-tank", "wardog"], detailStatus: "published", detailHref: "/items/vehicles/l2a6", evidenceStatus, dataAsOf},
  {slug: "mh-6", name: "MH-6", type: "vehicles", subtype: "Light air transport", image: "/images/catalogue/vehicles/mh-6.webp", imageAlt: "MH-6 light air transport", summary: "Light air transport listed at $6,250 with open purchase observed in Alpha 1.", facts: [fact("Role", "Light air transport"), fact("Alpha price", "$6,250"), fact("Observed gate", "Open purchase"), fact("Track", "-")], filterValues: ["aircraft", "light-air-transport", "open-purchase"], detailStatus: "published", detailHref: "/items/vehicles/mh-6", evidenceStatus, dataAsOf},
  {slug: "sph-2", name: "SPH-2", type: "vehicles", subtype: "Self-propelled artillery", image: "/images/catalogue/vehicles/sph-2.webp", imageAlt: "SPH-2 self-propelled artillery", summary: "Self-propelled artillery listed at $10,000 with a Wardog Level 55 gate.", facts: [fact("Role", "Self-propelled artillery"), fact("Alpha price", "$10,000"), fact("Observed gate", "Wardog Level 55"), fact("Track", "Wardog")], filterValues: ["armor-and-artillery", "self-propelled-artillery", "wardog"], detailStatus: "published", detailHref: "/items/vehicles/sph-2", evidenceStatus, dataAsOf},
  {slug: "uh-1y-miniguns", name: "UH-1Y Miniguns", type: "vehicles", subtype: "Armed utility helicopter", image: "/images/catalogue/vehicles/uh-1y-miniguns.webp", imageAlt: "UH-1Y Miniguns armed utility helicopter", summary: "Armed utility helicopter listed at $8,000; its Alpha gate was unreadable.", facts: [fact("Role", "Armed utility helicopter"), fact("Alpha price", "$8,000"), fact("Observed gate", "Gate unread"), fact("Track", "-")], filterValues: ["aircraft", "armed-utility-helicopter", "gate-unread"], detailStatus: "published", detailHref: "/items/vehicles/uh-1y-miniguns", evidenceStatus, dataAsOf},
  {slug: "uh-1y", name: "UH-1Y", type: "vehicles", subtype: "Air transport", image: "/images/catalogue/vehicles/uh-1y.webp", imageAlt: "UH-1Y air transport", summary: "Air transport listed at $7,400 with a Pilot Level 10 gate.", facts: [fact("Role", "Air transport"), fact("Alpha price", "$7,400"), fact("Observed gate", "Pilot Level 10"), fact("Track", "Pilot")], filterValues: ["aircraft", "air-transport", "pilot"], detailStatus: "published", detailHref: "/items/vehicles/uh-1y", evidenceStatus, dataAsOf},
  {slug: "ural-defender-m249", name: "Ural Defender M249", type: "vehicles", subtype: "Armed logistics", image: "/images/catalogue/vehicles/ural-defender-m249.webp", imageAlt: "Ural Defender M249 armed logistics truck", summary: "Armed logistics vehicle listed at $6,750 with a Driver Level 40 gate.", facts: [fact("Role", "Armed logistics"), fact("Alpha price", "$6,750"), fact("Observed gate", "Driver Level 40"), fact("Track", "Driver")], filterValues: ["land-transport", "armed-logistics", "driver"], detailStatus: "published", detailHref: "/items/vehicles/ural-defender-m249", evidenceStatus, dataAsOf},
  {slug: "ural-defender", name: "Ural Defender", type: "vehicles", subtype: "Protected logistics", image: "/images/catalogue/vehicles/ural-defender.webp", imageAlt: "Ural Defender protected logistics truck", summary: "Protected logistics vehicle listed at $6,000 with a Driver Level 30 gate.", facts: [fact("Role", "Protected logistics"), fact("Alpha price", "$6,000"), fact("Observed gate", "Driver Level 30"), fact("Track", "Driver")], filterValues: ["land-transport", "protected-logistics", "driver"], detailStatus: "published", detailHref: "/items/vehicles/ural-defender", evidenceStatus, dataAsOf},
  {slug: "ural", name: "Ural", type: "vehicles", subtype: "Logistics truck", image: "/images/catalogue/vehicles/ural.webp", imageAlt: "Ural logistics truck", summary: "Logistics truck listed at $5,000 with a $60,000 unlock observed.", facts: [fact("Role", "Logistics truck"), fact("Alpha price", "$5,000"), fact("Observed gate", "$60,000 unlock"), fact("Track", "-")], filterValues: ["land-transport", "logistics-truck", "60-000-unlock"], detailStatus: "published", detailHref: "/items/vehicles/ural", evidenceStatus, dataAsOf},
  {slug: "m113-apc-sv-variant-1", name: "M113 APC SV - Variant 1", type: "vehicles", subtype: "Identifier only", image: "/images/catalogue/banners/vehicles-1280.webp", imageAlt: "M113 APC SV Variant 1 image verification pending", summary: "One of three M113 APC SV identifiers observed in pre-release catalogue coverage; variant details were not readable.", facts: [fact("Build", "Closed Beta"), fact("Verification", "Identifier only")], filterValues: ["identifier-only", "tracked"], detailStatus: "inline", evidenceStatus, evidenceTier: "identifier-only", mediaState: "pending", sourceNotes: identifierOnlyNotes, dataAsOf: betaDataAsOf},
  {slug: "m113-apc-sv-variant-2", name: "M113 APC SV - Variant 2", type: "vehicles", subtype: "Identifier only", image: "/images/catalogue/banners/vehicles-1280.webp", imageAlt: "M113 APC SV Variant 2 image verification pending", summary: "One of three M113 APC SV identifiers observed in pre-release catalogue coverage; variant details were not readable.", facts: [fact("Build", "Closed Beta"), fact("Verification", "Identifier only")], filterValues: ["identifier-only", "tracked"], detailStatus: "inline", evidenceStatus, evidenceTier: "identifier-only", mediaState: "pending", sourceNotes: identifierOnlyNotes, dataAsOf: betaDataAsOf},
  {slug: "m113-apc-sv-variant-3", name: "M113 APC SV - Variant 3", type: "vehicles", subtype: "Identifier only", image: "/images/catalogue/banners/vehicles-1280.webp", imageAlt: "M113 APC SV Variant 3 image verification pending", summary: "One of three M113 APC SV identifiers observed in pre-release catalogue coverage; variant details were not readable.", facts: [fact("Build", "Closed Beta"), fact("Verification", "Identifier only")], filterValues: ["identifier-only", "tracked"], detailStatus: "inline", evidenceStatus, evidenceTier: "identifier-only", mediaState: "pending", sourceNotes: identifierOnlyNotes, dataAsOf: betaDataAsOf},
  {slug: "loudspeaker", name: "Loudspeaker", type: "vehicles", subtype: "Stationary support", image: "/images/catalogue/banners/vehicles-1280.webp", imageAlt: "Loudspeaker image verification pending", summary: "Stationary support-system identifier observed in Closed Beta catalogue coverage; exact function and cost remain build-sensitive.", facts: [fact("Role", "Stationary support"), fact("Closed Beta price", "Not captured"), fact("Observed gate", "Not captured")], filterValues: ["stationary-system", "support"], detailStatus: "published", detailHref: "/items/vehicles/loudspeaker", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "talon-9k-sam", name: "Talon 9K-SAM", type: "vehicles", subtype: "Stationary anti-air", image: "/images/catalogue/banners/vehicles-1280.webp", imageAlt: "Talon 9K-SAM image verification pending", summary: "Stationary anti-air system identified in Closed Beta catalogue coverage; cost and deployment rules remain unconfirmed.", facts: [fact("Role", "Stationary anti-air"), fact("Closed Beta price", "Not captured"), fact("Observed gate", "Not captured")], filterValues: ["stationary-system", "anti-air"], detailStatus: "published", detailHref: "/items/vehicles/talon-9k-sam", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "l81-mortar", name: "L81 Mortar", type: "vehicles", subtype: "Stationary artillery", image: "/images/catalogue/banners/vehicles-1280.webp", imageAlt: "L81 Mortar image verification pending", summary: "Stationary mortar system identified in Closed Beta catalogue coverage; range, ammunition, and cost remain unconfirmed.", facts: [fact("Role", "Stationary artillery"), fact("Closed Beta price", "Not captured"), fact("Observed gate", "Not captured")], filterValues: ["stationary-system", "artillery"], detailStatus: "published", detailHref: "/items/vehicles/l81-mortar", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "vanguard-ciws", name: "Vanguard CIWS", type: "vehicles", subtype: "Stationary defense", image: "/images/catalogue/banners/vehicles-1280.webp", imageAlt: "Vanguard CIWS image verification pending", summary: "Stationary close-in defense system identified in Closed Beta catalogue coverage; exact behavior remains unconfirmed.", facts: [fact("Role", "Stationary defense"), fact("Closed Beta price", "Not captured"), fact("Observed gate", "Not captured")], filterValues: ["stationary-system", "defense"], detailStatus: "published", detailHref: "/items/vehicles/vanguard-ciws", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf},
  {slug: "stingray", name: "Stingray", type: "vehicles", subtype: "Stationary weapon", image: "/images/catalogue/banners/vehicles-1280.webp", imageAlt: "Stingray image verification pending", summary: "Stationary weapon-system identifier observed in Closed Beta catalogue coverage; exact role and cost remain unconfirmed.", facts: [fact("Role", "Stationary weapon"), fact("Closed Beta price", "Not captured"), fact("Observed gate", "Not captured")], filterValues: ["stationary-system", "weapon"], detailStatus: "published", detailHref: "/items/vehicles/stingray", evidenceStatus, evidenceTier: "corroborated-community", mediaState: "pending", sourceNotes: betaSourceNotes, dataAsOf: betaDataAsOf}
];

const ammoRecords: readonly CatalogueRecordInput[] = [
  {slug: "45-acp", name: ".45 ACP", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/45-acp.webp", imageAlt: ".45 ACP ammunition", summary: "Observed .45 ACP calibre with base damage 30 and three load families.", facts: [fact("Base damage", "30"), fact("Loads", "3"), fact("Standard per round", "$1"), fact("Box price", "$10"), fact("Weapons", "2")], filterValues: ["three-loads", "base-damage-observed", "45-acp"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "9x19mm", name: "9x19mm", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/9mm-fmj.webp", imageAlt: "9x19mm ammunition", summary: "Observed 9x19mm calibre with base damage 22 and three load families.", facts: [fact("Base damage", "22"), fact("Loads", "3"), fact("Standard per round", "$1"), fact("Box price", "$10"), fact("Weapons", "5")], filterValues: ["three-loads", "base-damage-observed", "9x19mm"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "5-45x39mm", name: "5.45x39mm", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/5-45x39mm-fmj.webp", imageAlt: "5.45x39mm ammunition", summary: "Observed 5.45x39mm calibre with base damage 26 and three load families.", facts: [fact("Base damage", "26"), fact("Loads", "3"), fact("Standard per round", "Not captured"), fact("Box price", "$15"), fact("Weapons", "1")], filterValues: ["three-loads", "base-damage-observed", "5-45x39mm"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "5-56x45mm", name: "5.56x45mm", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/556x45mm.webp", imageAlt: "5.56x45mm ammunition", summary: "Observed 5.56x45mm calibre with base damage 28 and three load families.", facts: [fact("Base damage", "28"), fact("Loads", "3"), fact("Standard per round", "$1.50"), fact("Box price", "$15"), fact("Weapons", "8")], filterValues: ["three-loads", "base-damage-observed", "5-56x45mm"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "50-ae", name: ".50 AE", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/50-ae.webp", imageAlt: ".50 AE ammunition", summary: "Observed .50 AE calibre with base damage 49 and three load families.", facts: [fact("Base damage", "49"), fact("Loads", "3"), fact("Standard per round", "$4"), fact("Box price", "$20"), fact("Weapons", "1")], filterValues: ["three-loads", "base-damage-observed", "50-ae"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "7-62x54mmr", name: "7.62x54mmR", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/762x54mm.webp", imageAlt: "7.62x54mmR ammunition", summary: "Observed 7.62x54mmR calibre with base damage 55 and three load families.", facts: [fact("Base damage", "55"), fact("Loads", "3"), fact("Standard per round", "$6"), fact("Box price", "$30"), fact("Weapons", "4")], filterValues: ["three-loads", "base-damage-observed", "7-62x54mmr"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "45-colt", name: ".45 Colt", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/45-colt.webp", imageAlt: ".45 Colt ammunition", summary: "Observed .45 Colt calibre with three load families and a $33 box price.", facts: [fact("Base damage", "Not captured"), fact("Loads", "3"), fact("Standard per round", "Not captured"), fact("Box price", "$33"), fact("Weapons", "1")], filterValues: ["three-loads", "base-damage-not-captured", "45-colt"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "7-62x39mm", name: "7.62x39mm", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/762x39mm.webp", imageAlt: "7.62x39mm ammunition", summary: "Observed 7.62x39mm calibre with base damage 42 and three load families.", facts: [fact("Base damage", "42"), fact("Loads", "3"), fact("Standard per round", "Not captured"), fact("Box price", "$40"), fact("Weapons", "1")], filterValues: ["three-loads", "base-damage-observed", "7-62x39mm"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "308-winchester", name: ".308 Winchester", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/308.webp", imageAlt: ".308 Winchester ammunition", summary: "Observed .308 Winchester calibre with base damage 60 and three load families.", facts: [fact("Base damage", "60"), fact("Loads", "3"), fact("Standard per round", "$4"), fact("Box price", "$40"), fact("Weapons", "3")], filterValues: ["three-loads", "base-damage-observed", "308-winchester"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "50-cal", name: ".50 Cal", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/50-cal.webp", imageAlt: ".50 Cal ammunition", summary: "Observed .50 Cal calibre with three load families and a $250 box price.", facts: [fact("Base damage", "Not captured"), fact("Loads", "3"), fact("Standard per round", "$50"), fact("Box price", "$250"), fact("Weapons", "1")], filterValues: ["three-loads", "base-damage-not-captured", "50-cal"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "338-norma-magnum", name: ".338 Norma Magnum", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/338-norma-magnum-fmj.webp", imageAlt: ".338 Norma Magnum ammunition", summary: "Observed .338 Norma Magnum calibre with three load families; prices and weapon count were not captured.", facts: [fact("Base damage", "Not captured"), fact("Loads", "3"), fact("Standard per round", "Not captured"), fact("Box price", "Not captured"), fact("Weapons", "Not captured")], filterValues: ["three-loads", "base-damage-not-captured", "338-norma-magnum"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "12-gauge", name: "12 Gauge", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/12g-buck.webp", imageAlt: "12 Gauge ammunition", summary: "Observed 12 Gauge calibre with two load families and two associated weapons.", facts: [fact("Base damage", "Not captured"), fact("Loads", "2"), fact("Standard per round", "Not captured"), fact("Box price", "Not captured"), fact("Weapons", "2")], filterValues: ["two-loads", "base-damage-not-captured", "12-gauge"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "12-7x55mm", name: "12.7x55mm", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/12-7x55mm.webp", imageAlt: "12.7x55mm ammunition", summary: "Observed 12.7x55mm calibre; load, price, damage, and weapon-count values were not captured.", facts: [fact("Base damage", "Not captured"), fact("Loads", "Not captured"), fact("Standard per round", "Not captured"), fact("Box price", "Not captured"), fact("Weapons", "Not captured")], filterValues: ["load-count-not-captured", "base-damage-not-captured", "12-7x55mm"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "9x39mm", name: "9x39mm", type: "ammo", subtype: "Calibre", image: "/images/catalogue/ammo/9x39mm.webp", imageAlt: "9x39mm ammunition", summary: "Observed 9x39mm calibre; load, price, damage, and weapon-count values were not captured.", facts: [fact("Base damage", "Not captured"), fact("Loads", "Not captured"), fact("Standard per round", "Not captured"), fact("Box price", "Not captured"), fact("Weapons", "Not captured")], filterValues: ["load-count-not-captured", "base-damage-not-captured", "9x39mm"], detailStatus: "inline", evidenceStatus, dataAsOf}
];

const attachmentRecords: readonly CatalogueRecordInput[] = [
  {slug: "vektor-frenix-x-micro-reflex-sight", name: "Vektor Frenix-X Micro Reflex Sight", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/vektor-frenix-x-micro-reflex-sight.webp", imageAlt: "Vektor Frenix-X Micro Reflex Sight optic", summary: "Optic with 1.2x fixed zeroing and 0.03 kg observed weight.", facts: [fact("Alpha price", "$820"), fact("Zoom or capacity", "1.2x / fixed"), fact("Weight or calibre", "0.03 kg")], filterValues: ["optic", "1-2x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "four-reticle-reflex", name: "Four Reticle Reflex", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/four-reticle-reflex.webp", imageAlt: "Four Reticle Reflex optic", summary: "Optic with 1.2x fixed zeroing and 0.12 kg observed weight.", facts: [fact("Alpha price", "$580"), fact("Zoom or capacity", "1.2x / fixed"), fact("Weight or calibre", "0.12 kg")], filterValues: ["optic", "1-2x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "compact-t-2-red-dot", name: "Compact T-2 Red Dot", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/compact-t-2-red-dot.webp", imageAlt: "Compact T-2 Red Dot optic", summary: "Optic with 1.2x fixed zeroing and 0.13 kg observed weight.", facts: [fact("Alpha price", "$340"), fact("Zoom or capacity", "1.2x / fixed"), fact("Weight or calibre", "0.13 kg")], filterValues: ["optic", "1-2x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "holographic-sight", name: "Holographic Sight", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/holographic-sight.webp", imageAlt: "Holographic Sight optic", summary: "Optic with 1.2x fixed zeroing and 0.25 kg observed weight.", facts: [fact("Alpha price", "Not captured"), fact("Zoom or capacity", "1.2x / fixed"), fact("Weight or calibre", "0.25 kg")], filterValues: ["optic", "1-2x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "kobra-reflex", name: "Kobra Reflex", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/kobra-reflex.webp", imageAlt: "Kobra Reflex optic", summary: "Optic with 1.2x fixed zeroing and 0.41 kg observed weight.", facts: [fact("Alpha price", "$520"), fact("Zoom or capacity", "1.2x / fixed"), fact("Weight or calibre", "0.41 kg")], filterValues: ["optic", "1-2x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "okp-7-reflex", name: "OKP 7 Reflex", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/okp-7-reflex.webp", imageAlt: "OKP 7 Reflex optic", summary: "Optic with 1.2x fixed zeroing and 0.48 kg observed weight.", facts: [fact("Alpha price", "$840"), fact("Zoom or capacity", "1.2x / fixed"), fact("Weight or calibre", "0.48 kg")], filterValues: ["optic", "1-2x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "tricon-1-5x-compact-prism-scope", name: "Tricon 1.5x Compact Prism Scope", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/tricon-1-5x-compact-prism-scope.webp", imageAlt: "Tricon 1.5x Compact Prism Scope optic", summary: "Optic with 1.5x zeroing from 100-200m and 0.2 kg observed weight.", facts: [fact("Alpha price", "$650"), fact("Zoom or capacity", "1.5x / 100-200m"), fact("Weight or calibre", "0.2 kg")], filterValues: ["optic", "1-5x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "cq-2x-prism-combat-scope", name: "CQ-2x Prism Combat Scope", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/cq-2x-prism-combat-scope.webp", imageAlt: "CQ-2x Prism Combat Scope optic", summary: "Optic with 2x zeroing from 100-300m and 0.31 kg observed weight.", facts: [fact("Alpha price", "$640"), fact("Zoom or capacity", "2x / 100-300m"), fact("Weight or calibre", "0.31 kg")], filterValues: ["optic", "2x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "2-5x-combat-optic", name: "2.5x Combat Optic", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/2-5x-combat-optic.webp", imageAlt: "2.5x Combat Optic", summary: "Optic with 2.5x zeroing from 100-300m and 0.4 kg observed weight.", facts: [fact("Alpha price", "Not captured"), fact("Zoom or capacity", "2.5x / 100-300m"), fact("Weight or calibre", "0.4 kg")], filterValues: ["optic", "2-5x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "spitfire-3x", name: "Spitfire 3x", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/spitfire-3x.webp", imageAlt: "Spitfire 3x optic", summary: "Optic with 3x zeroing from 100-300m and 0.26 kg observed weight.", facts: [fact("Alpha price", "$790"), fact("Zoom or capacity", "3x / 100-300m"), fact("Weight or calibre", "0.26 kg")], filterValues: ["optic", "3x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "3x-tactical-prism-scope", name: "3x Tactical Prism Scope", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/3x-tactical-prism-scope.webp", imageAlt: "3x Tactical Prism Scope optic", summary: "Optic with 3x zeroing from 100-300m and 0.43 kg observed weight.", facts: [fact("Alpha price", "$740"), fact("Zoom or capacity", "3x / 100-300m"), fact("Weight or calibre", "0.43 kg")], filterValues: ["optic", "3x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "4x-combat-prism-scope-with-reflex", name: "4x Combat Prism Scope with Reflex", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/4x-combat-prism-scope-with-reflex.webp", imageAlt: "4x Combat Prism Scope with Reflex optic", summary: "Optic with 4x zeroing from 100-400m and 0.42 kg observed weight.", facts: [fact("Alpha price", "$880"), fact("Zoom or capacity", "4x / 100-400m"), fact("Weight or calibre", "0.42 kg")], filterValues: ["optic", "4x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "spectr-4x", name: "Spectr 4x", type: "attachments", subtype: "Optic", image: "/images/catalogue/attachments/spectr-4x.webp", imageAlt: "Spectr 4x optic", summary: "Optic with 4x zeroing from 100-400m and 0.66 kg observed weight.", facts: [fact("Alpha price", "Not captured"), fact("Zoom or capacity", "4x / 100-400m"), fact("Weight or calibre", "0.66 kg")], filterValues: ["optic", "4x"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "amp-9-15-rnd-magazine", name: "AMP-9 15 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/amp-9-15-rnd-magazine.webp", imageAlt: "AMP-9 15 Round Magazine", summary: "AMP-9 magazine with 15 rounds for 9x19mm.", facts: [fact("Alpha price", "$30"), fact("Zoom or capacity", "15 rounds"), fact("Weight or calibre", "9x19mm")], filterValues: ["magazine", "9x19mm", "15-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "amp-9-20-rnd-magazine", name: "AMP-9 20 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/amp-9-20-rnd-magazine.webp", imageAlt: "AMP-9 20 Round Magazine", summary: "AMP-9 magazine with 20 rounds for 9x19mm.", facts: [fact("Alpha price", "$70"), fact("Zoom or capacity", "20 rounds"), fact("Weight or calibre", "9x19mm")], filterValues: ["magazine", "9x19mm", "20-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "amp-9-30-rnd-magazine", name: "AMP-9 30 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/amp-9-30-rnd-magazine.webp", imageAlt: "AMP-9 30 Round Magazine", summary: "AMP-9 magazine with 30 rounds for 9x19mm.", facts: [fact("Alpha price", "$100"), fact("Zoom or capacity", "30 rounds"), fact("Weight or calibre", "9x19mm")], filterValues: ["magazine", "9x19mm", "30-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "amp-9-50-rnd-magazine", name: "AMP-9 50 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/amp-9-50-rnd-magazine.webp", imageAlt: "AMP-9 50 Round Magazine", summary: "AMP-9 magazine with 50 rounds for 9x19mm.", facts: [fact("Alpha price", "$180"), fact("Zoom or capacity", "50 rounds"), fact("Weight or calibre", "9x19mm")], filterValues: ["magazine", "9x19mm", "50-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "amr-50-10-rnd-magazine", name: "AMR 50 10 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/amr-50-10-rnd-magazine.webp", imageAlt: "AMR 50 10 Round Magazine", summary: "AMR 50 magazine with 10 rounds for .50 Cal.", facts: [fact("Alpha price", "$30"), fact("Zoom or capacity", "10 rounds"), fact("Weight or calibre", ".50 Cal")], filterValues: ["magazine", "50-cal", "10-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "deagle-7-rnd-magazine", name: "Deagle 7 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/deagle-7-rnd-magazine.webp", imageAlt: "Deagle 7 Round Magazine", summary: "Deagle magazine with 7 rounds for .50 AE.", facts: [fact("Alpha price", "$50"), fact("Zoom or capacity", "7 rounds"), fact("Weight or calibre", ".50 AE")], filterValues: ["magazine", "50-ae", "7-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "fal-bmr-308-20-rnd-magazine", name: "FAL and BMR-308 20 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/fal-bmr-308-20-rnd-magazine.webp", imageAlt: "FAL and BMR-308 20 Round Magazine", summary: "FAL and BMR-308 magazine with 20 rounds for .308 Winchester.", facts: [fact("Alpha price", "$150"), fact("Zoom or capacity", "20 rounds"), fact("Weight or calibre", ".308 Winchester")], filterValues: ["magazine", "308-winchester", "20-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "fal-30-rnd-magazine", name: "FAL 30 Round Magazine", type: "attachments", image: "/images/catalogue/attachments/fal-30-rnd-magazine.webp", imageAlt: "FAL 30 Round Magazine", subtype: "Magazine", summary: "FAL magazine with 30 rounds for .308 Winchester.", facts: [fact("Alpha price", "$250"), fact("Zoom or capacity", "30 rounds"), fact("Weight or calibre", ".308 Winchester")], filterValues: ["magazine", "308-winchester", "30-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "galil-35-rnd-magazine", name: "Galil 35 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/galil-35-rnd-magazine.webp", imageAlt: "Galil 35 Round Magazine", summary: "Galil magazine with 35 rounds for 5.56x45mm.", facts: [fact("Alpha price", "$60"), fact("Zoom or capacity", "35 rounds"), fact("Weight or calibre", "5.56x45mm")], filterValues: ["magazine", "5-56x45mm", "35-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "galil-50-rnd-magazine", name: "Galil 50 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/galil-50-rnd-magazine.webp", imageAlt: "Galil 50 Round Magazine", summary: "Galil magazine with 50 rounds for 5.56x45mm.", facts: [fact("Alpha price", "$110"), fact("Zoom or capacity", "50 rounds"), fact("Weight or calibre", "5.56x45mm")], filterValues: ["magazine", "5-56x45mm", "50-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "ggx-50-rnd-drum-magazine", name: "GGX 50 Round Drum Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/ggx-50-rnd-drum-magazine.webp", imageAlt: "GGX 50 Round Drum Magazine", summary: "GGX drum magazine with 50 rounds for 9x19mm.", facts: [fact("Alpha price", "$110"), fact("Zoom or capacity", "50 rounds"), fact("Weight or calibre", "9x19mm")], filterValues: ["magazine", "9x19mm", "50-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "m1911-7-rnd-magazine", name: "M1911 7 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/m1911-7-rnd-magazine.webp", imageAlt: "M1911 7 Round Magazine", summary: "M1911 magazine with 7 rounds for .45 ACP.", facts: [fact("Alpha price", "$20"), fact("Zoom or capacity", "7 rounds"), fact("Weight or calibre", ".45 ACP")], filterValues: ["magazine", "45-acp", "7-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "m1911-10-rnd-magazine", name: "M1911 10 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/m1911-10-rnd-magazine.webp", imageAlt: "M1911 10 Round Magazine", summary: "M1911 magazine with 10 rounds for .45 ACP.", facts: [fact("Alpha price", "$35"), fact("Zoom or capacity", "10 rounds"), fact("Weight or calibre", ".45 ACP")], filterValues: ["magazine", "45-acp", "10-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "m249-100-rnd-fabric-magazine", name: "M249 100 Round Fabric Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/m249-100-rnd-fabric-magazine.webp", imageAlt: "M249 100 Round Fabric Magazine", summary: "M249 fabric magazine with 100 rounds for 5.56x45mm.", facts: [fact("Alpha price", "$200"), fact("Zoom or capacity", "100 rounds"), fact("Weight or calibre", "5.56x45mm")], filterValues: ["magazine", "5-56x45mm", "100-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "mk22-5-rnd-magazine", name: "MK22 5 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/mk22-5-rnd-magazine.webp", imageAlt: "MK22 5 Round Magazine", summary: "MK22 magazine with 5 rounds for .308 Winchester.", facts: [fact("Alpha price", "$30"), fact("Zoom or capacity", "5 rounds"), fact("Weight or calibre", ".308 Winchester")], filterValues: ["magazine", "308-winchester", "5-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "mp5-20-rnd-magazine", name: "MP5 20 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/mp5-20-rnd-magazine.webp", imageAlt: "MP5 20 Round Magazine", summary: "MP5 magazine with 20 rounds for 9x19mm.", facts: [fact("Alpha price", "$70"), fact("Zoom or capacity", "20 rounds"), fact("Weight or calibre", "9x19mm")], filterValues: ["magazine", "9x19mm", "20-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "mp5-30-rnd-magazine", name: "MP5 30 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/mp5-30-rnd-magazine.webp", imageAlt: "MP5 30 Round Magazine", summary: "MP5 magazine with 30 rounds for 9x19mm.", facts: [fact("Alpha price", "$100"), fact("Zoom or capacity", "30 rounds"), fact("Weight or calibre", "9x19mm")], filterValues: ["magazine", "9x19mm", "30-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "mp5-50-rnd-magazine", name: "MP5 50 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/mp5-50-rnd-magazine.webp", imageAlt: "MP5 50 Round Magazine", summary: "MP5 magazine with 50 rounds for 9x19mm.", facts: [fact("Alpha price", "$230"), fact("Zoom or capacity", "50 rounds"), fact("Weight or calibre", "9x19mm")], filterValues: ["magazine", "9x19mm", "50-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "pp-19-vityaz-10-rnd-magazine", name: "PP-19 Vityaz 10 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/pp-19-vityaz-10-rnd-magazine.webp", imageAlt: "PP-19 Vityaz 10 Round Magazine", summary: "PP-19 Vityaz magazine with 10 rounds for 9x19mm.", facts: [fact("Alpha price", "$25"), fact("Zoom or capacity", "10 rounds"), fact("Weight or calibre", "9x19mm")], filterValues: ["magazine", "9x19mm", "10-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "pp-19-vityaz-30-rnd-magazine", name: "PP-19 Vityaz 30 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/pp-19-vityaz-30-rnd-magazine.webp", imageAlt: "PP-19 Vityaz 30 Round Magazine", summary: "PP-19 Vityaz magazine with 30 rounds for 9x19mm.", facts: [fact("Alpha price", "Not captured"), fact("Zoom or capacity", "30 rounds"), fact("Weight or calibre", "9x19mm")], filterValues: ["magazine", "9x19mm", "30-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "pp-19-50-rnd-magazine", name: "PP-19 50 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/pp-19-50-rnd-magazine.webp", imageAlt: "PP-19 50 Round Magazine", summary: "PP-19 magazine with 50 rounds for 9x19mm.", facts: [fact("Alpha price", "$200"), fact("Zoom or capacity", "50 rounds"), fact("Weight or calibre", "9x19mm")], filterValues: ["magazine", "9x19mm", "50-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "stanag-20-rnd-magazine", name: "STANAG 20 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/stanag-20-rnd-magazine.webp", imageAlt: "STANAG 20 Round Magazine", summary: "STANAG magazine with 20 rounds for 5.56x45mm.", facts: [fact("Alpha price", "Not captured"), fact("Zoom or capacity", "20 rounds"), fact("Weight or calibre", "5.56x45mm")], filterValues: ["magazine", "5-56x45mm", "20-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "stanag-60-rnd-magazine", name: "STANAG 60 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/stanag-60-rnd-magazine.webp", imageAlt: "STANAG 60 Round Magazine", summary: "STANAG magazine with 60 rounds for 5.56x45mm.", facts: [fact("Alpha price", "$420"), fact("Zoom or capacity", "60 rounds"), fact("Weight or calibre", "5.56x45mm")], filterValues: ["magazine", "5-56x45mm", "60-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "super-45-13-rnd-magazine", name: "Super-45 13 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/super-45-13-rnd-magazine.webp", imageAlt: "Super-45 13 Round Magazine", summary: "Super-45 magazine with 13 rounds for .45 ACP.", facts: [fact("Alpha price", "$30"), fact("Zoom or capacity", "13 rounds"), fact("Weight or calibre", ".45 ACP")], filterValues: ["magazine", "45-acp", "13-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "super-45-30-rnd-magazine", name: "Super-45 30 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/super-45-30-rnd-magazine.webp", imageAlt: "Super-45 30 Round Magazine", summary: "Super-45 magazine with 30 rounds for .45 ACP.", facts: [fact("Alpha price", "$80"), fact("Zoom or capacity", "30 rounds"), fact("Weight or calibre", ".45 ACP")], filterValues: ["magazine", "45-acp", "30-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "super-45-40-rnd-drum-magazine", name: "Super-45 40 Round Drum Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/super-45-40-rnd-drum-magazine.webp", imageAlt: "Super-45 40 Round Drum Magazine", summary: "Super-45 drum magazine with 40 rounds for .45 ACP.", facts: [fact("Alpha price", "$280"), fact("Zoom or capacity", "40 rounds"), fact("Weight or calibre", ".45 ACP")], filterValues: ["magazine", "45-acp", "40-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "svd-5-rnd-magazine", name: "SVD 5 Round Magazine", type: "attachments", subtype: "Magazine", image: "/images/catalogue/attachments/svd-5-rnd-magazine.webp", imageAlt: "SVD 5 Round Magazine", summary: "SVD magazine with 5 rounds for 7.62x54mmR.", facts: [fact("Alpha price", "$20"), fact("Zoom or capacity", "5 rounds"), fact("Weight or calibre", "7.62x54mmR")], filterValues: ["magazine", "7-62x54mmr", "5-rounds"], detailStatus: "inline", evidenceStatus, dataAsOf}
];

const gearRecords: readonly CatalogueRecordInput[] = [
  {slug: "light-helmet", name: "Light Helmet", type: "gear", subtype: "Helmet", image: "/images/catalogue/gear/light-helmet.webp", imageAlt: "Light Helmet", summary: "L1 helmet listed at $200 in the observed Alpha gear vendor.", facts: [fact("Slot", "Helmet"), fact("Tier", "L1"), fact("Alpha price", "$200")], filterValues: ["helmet", "l1"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "medium-helmet", name: "Medium Helmet", type: "gear", subtype: "Helmet", image: "/images/catalogue/gear/medium-helmet.webp", imageAlt: "Medium Helmet", summary: "L2 helmet listed at $500 in the observed Alpha gear vendor.", facts: [fact("Slot", "Helmet"), fact("Tier", "L2"), fact("Alpha price", "$500")], filterValues: ["helmet", "l2"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "heavy-helmet", name: "Heavy Helmet", type: "gear", subtype: "Helmet", image: "/images/catalogue/gear/heavy-helmet.webp", imageAlt: "Heavy Helmet", summary: "L3 helmet listed at $1,500 in the observed Alpha gear vendor.", facts: [fact("Slot", "Helmet"), fact("Tier", "L3"), fact("Alpha price", "$1,500")], filterValues: ["helmet", "l3"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "super-heavy-helmet", name: "Super Heavy Helmet", type: "gear", subtype: "Helmet", image: "/images/catalogue/gear/super-heavy-helmet.webp", imageAlt: "Super Heavy Helmet", summary: "L4 helmet listed at $3,000 in the observed Alpha gear vendor.", facts: [fact("Slot", "Helmet"), fact("Tier", "L4"), fact("Alpha price", "$3,000")], filterValues: ["helmet", "l4"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "ghillie-helmet", name: "Ghillie Helmet", type: "gear", subtype: "Helmet", image: "/images/catalogue/gear/ghillie-helmet.webp", imageAlt: "Ghillie Helmet", summary: "Special helmet listed at $2,500 in the observed Alpha gear vendor.", facts: [fact("Slot", "Helmet"), fact("Tier", "Special"), fact("Alpha price", "$2,500")], filterValues: ["helmet", "special"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "light-armor", name: "Light Armor", type: "gear", subtype: "Armor", image: "/images/catalogue/gear/light-armor.webp", imageAlt: "Light Armor", summary: "L1 armor listed at $400 in the observed Alpha gear vendor.", facts: [fact("Slot", "Armor"), fact("Tier", "L1"), fact("Alpha price", "$400")], filterValues: ["armor", "l1"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "medium-armor", name: "Medium Armor", type: "gear", subtype: "Armor", image: "/images/catalogue/gear/medium-armor.webp", imageAlt: "Medium Armor", summary: "L2 armor listed at $1,000 in the observed Alpha gear vendor.", facts: [fact("Slot", "Armor"), fact("Tier", "L2"), fact("Alpha price", "$1,000")], filterValues: ["armor", "l2"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "heavy-armor", name: "Heavy Armor", type: "gear", subtype: "Armor", image: "/images/catalogue/gear/heavy-armor.webp", imageAlt: "Heavy Armor", summary: "L3 armor listed at $2,000 in the observed Alpha gear vendor.", facts: [fact("Slot", "Armor"), fact("Tier", "L3"), fact("Alpha price", "$2,000")], filterValues: ["armor", "l3"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "super-heavy-armor", name: "Super Heavy Armor", type: "gear", subtype: "Armor", image: "/images/catalogue/gear/super-heavy-armor.webp", imageAlt: "Super Heavy Armor", summary: "L4 armor listed at $4,000 in the observed Alpha gear vendor.", facts: [fact("Slot", "Armor"), fact("Tier", "L4"), fact("Alpha price", "$4,000")], filterValues: ["armor", "l4"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "ghillie-armor", name: "Ghillie Armor", type: "gear", subtype: "Armor", image: "/images/catalogue/gear/ghillie-armor.webp", imageAlt: "Ghillie Armor", summary: "Special armor listed at $3,000 in the observed Alpha gear vendor.", facts: [fact("Slot", "Armor"), fact("Tier", "Special"), fact("Alpha price", "$3,000")], filterValues: ["armor", "special"], detailStatus: "inline", evidenceStatus, dataAsOf},
  {slug: "scout-backpack", name: "Scout Backpack", type: "gear", subtype: "Backpack", image: "/images/catalogue/gear/scout-backpack.webp", imageAlt: "Scout Backpack", summary: "Lightest backpack listed at $350 in the observed Alpha gear vendor.", facts: [fact("Slot", "Backpack"), fact("Tier", "Lightest"), fact("Alpha price", "$350")], filterValues: ["backpack", "lightest"], detailStatus: "inline", evidenceStatus, dataAsOf}
];

const recordInputs: readonly CatalogueRecordInput[] = [
  ...weaponRecords,
  ...vehicleRecords,
  ...ammoRecords,
  ...attachmentRecords,
  ...gearRecords
];

export const catalogueRecords: readonly CatalogueRecord[] = recordInputs.map((record) => ({
  ...record,
  evidenceTier: record.evidenceTier ?? "build-capture",
  mediaState: record.mediaState ?? "verified",
  sourceNotes: record.sourceNotes ?? ["Observed in the WARDOGS Alpha 1 catalogue capture dated 7 Aug 2026."],
}));

export function getCatalogueRecords(type: CatalogueRecordType): readonly CatalogueRecord[] {
  return catalogueRecords.filter((record) => record.type === type);
}

export function getCatalogueRecord(type: CatalogueRecordType, slug: string): CatalogueRecord | undefined {
  return catalogueRecords.find((record) => record.type === type && record.slug === slug);
}
