import type {CatalogueRecord, CatalogueRecordType} from "./catalogue-types";

type SuppliedArtEntry = readonly [
  type: CatalogueRecordType,
  slug: string,
  name: string,
  subtype: string,
  sourceFolder: "gear" | "vehicles" | "attachments" | "equipment",
  filename: string,
];

// The owner's September 2026 archive is a snapshot of community catalogue art.
// These entries identify the visible object; they never infer current prices or unlocks.
const entries: readonly SuppliedArtEntry[] = [
  ["vehicles", "z20-lakota", "Z20 Lakota", "Air transport", "vehicles", "z20-lakota"],
  ["vehicles", "z20-lakota-miniguns", "Z20 Lakota Miniguns", "Armed air transport", "vehicles", "z20-lakota-miniguns"],
  ["gear", "large-tac-vest", "Large Tac Vest", "Vest", "gear", "large-tac-vest"],
  ["gear", "medium-tac-vest", "Medium Tac Vest", "Vest", "gear", "medium-tac-vest"],
  ["gear", "small-tac-vest", "Small Tac Vest", "Vest", "gear", "small-tac-vest"],
  ["gear", "arsenal-backpack-2-slings", "Arsenal Backpack + 2 Slings", "Backpack", "gear", "arsenal-backpack-2-slings"],
  ["gear", "assault-backpack", "Assault Backpack", "Backpack", "gear", "assault-backpack"],
  ["gear", "field-backpack", "Field Backpack", "Backpack", "gear", "field-backpack"],
  ["gear", "gunner-backpack-sling", "Gunner Backpack + Sling", "Backpack", "gear", "gunner-backpack-sling"],
  ["gear", "halftrack-backpack", "Halftrack Backpack", "Backpack", "gear", "halftrack-backpack"],
  ["gear", "medium-backpack-sling", "Medium Backpack + Sling", "Backpack", "gear", "medium-backpack-sling"],
  ["gear", "operator-backpack", "Operator Backpack", "Backpack", "gear", "operator-backpack"],
  ["gear", "pouch", "Pouch", "Backpack", "gear", "pouch"],
  ["gear", "ruck-backpack", "Ruck Backpack", "Backpack", "gear", "ruck-backpack"],
  ["gear", "basic-parachute", "Basic Parachute", "Parachute", "gear", "basic-parachute"],
  ["gear", "sport-parachute", "Sport Parachute", "Parachute", "gear", "sport-parachute"],
  ["attachments", "ak74-75-rnd-drum-magazine", "AK74 75-round Drum Magazine", "Magazine", "attachments", "ak74-75-rnd-drum-magazine"],
  ["attachments", "ggx-33-rnd-magazine", "GGX 33-round Magazine", "Magazine", "attachments", "ggx-33-rnd-magazine"],
  ["attachments", "mosin-standard-mag", "Mosin Standard Magazine", "Magazine", "attachments", "mosin-standard-mag"],
  ["attachments", "mp43-internal-mag", "MP43 Internal Magazine", "Magazine", "attachments", "mp43-internal-mag"],
  ["attachments", "amr-50-5-rnd-magazine", "AMR 50 5-round Magazine", "Magazine", "attachments", "amr-50-5-rnd-magazine"],
  ["attachments", "sv98-10-rnd-magazine", "SV98 10-round Magazine", "Magazine", "attachments", "sv98-10-rnd-magazine"],
  ["attachments", "svd-10-rnd-magazine", "SVD 10-round Magazine", "Magazine", "attachments", "svd-10-rnd-magazine"],
  ["attachments", "mk22-10-rnd-magazine", "MK22 10-round Magazine", "Magazine", "attachments", "mk22-10-rnd-magazine"],
  ["attachments", "fal-10-rnd-magazine", "FAL 10-round Magazine", "Magazine", "attachments", "fal-10-rnd-magazine"],
  ["attachments", "ggx-17-rnd-magazine", "GGX 17-round Magazine", "Magazine", "attachments", "ggx-17-rnd-magazine"],
  ["attachments", "stanag-30-rnd-magazine", "STANAG 30-round Magazine", "Magazine", "attachments", "stanag-30-rnd-magazine"],
  ["attachments", "ak74-30-rnd-magazine", "AK74 30-round Magazine", "Magazine", "attachments", "ak74-30-rnd-magazine"],
  ["attachments", "ak74-60-rnd-magazine", "AK74 60-round Magazine", "Magazine", "attachments", "ak74-60-rnd-magazine"],
  ["attachments", "pkm-100-rnd-box", "PKM 100-round Box", "Magazine", "attachments", "pkm-100-rnd-box"],
  ["attachments", "m249-200-rnd-box", "M249 200-round Box", "Magazine", "attachments", "m249-200-rnd-box"],
  ["equipment", "m18-signal-grenade-alert", "M18 Signal Grenade: Alert", "Tactical", "equipment", "m18-signal-grenade-alert"],
  ["equipment", "m18-signal-grenade-damaged-vehicle", "M18 Signal Grenade: Damaged Vehicle", "Tactical", "equipment", "m18-signal-grenade-damaged-vehicle"],
  ["equipment", "m18-signal-grenade-friendly", "M18 Signal Grenade: Friendly", "Tactical", "equipment", "m18-signal-grenade-friendly"],
  ["equipment", "m18-signal-grenade-hostile", "M18 Signal Grenade: Hostile", "Tactical", "equipment", "m18-signal-grenade-hostile"],
  ["equipment", "m18-smoke-grenade-white", "M18 Smoke Grenade: White", "Tactical", "equipment", "smokegrenade"],
  ["equipment", "m18-smoke-grenade-black", "M18 Smoke Grenade: Black", "Tactical", "equipment", "m18-smoke-grenade-black"],
  ["equipment", "m67-frag-grenade", "M67 Frag Grenade", "Tactical", "equipment", "m67-frag-grenade"],
  ["equipment", "c4-charge", "C4 Charge", "Tactical", "equipment", "c4explosive"],
  ["equipment", "remote-detonator", "Remote Detonator", "Tactical", "equipment", "c4trigger"],
  ["equipment", "flash-grenade", "Flash Grenade", "Tactical", "equipment", "flash-grenade"],
  ["equipment", "gold-frag-grenade", "Gold Frag Grenade", "Tactical", "equipment", "gold-frag-grenade"],
  ["equipment", "he-grenade", "HE Grenade", "Tactical", "equipment", "he-grenade"],
  ["equipment", "bandage", "Bandage", "Medical", "equipment", "bandage"],
  ["equipment", "adrenaline-pen", "Adrenaline Pen", "Medical", "equipment", "adrenaline-pen"],
  ["equipment", "field-resuscitator", "Field Resuscitator", "Medical", "equipment", "field-resuscitator"],
  ["equipment", "individual-first-aid-kit", "Individual First Aid Kit", "Medical", "equipment", "individual-first-aid-kit"],
  ["equipment", "amphetamine", "Amphetamine", "Medical", "equipment", "amphetamine"],
  ["equipment", "emergency-resuscitator", "Emergency Resuscitator", "Medical", "equipment", "resuscitator"],
  ["equipment", "energy-drink", "Energy Drink", "Medical", "equipment", "energy-drink"],
  ["equipment", "field-medical-kit", "Field Medical Kit", "Medical", "equipment", "field-medical-kit"],
  ["equipment", "manual-resuscitator", "Manual Resuscitator", "Medical", "equipment", "manual-resuscitator"],
  ["equipment", "painkillers", "Painkillers", "Medical", "equipment", "painkillers"],
  ["equipment", "monocular", "Monocular", "Recon", "equipment", "monocular"],
  ["equipment", "flares", "Flares", "Recon", "equipment", "flares"],
  ["equipment", "infrared-range-finder", "Infrared Range Finder", "Recon", "equipment", "infraredrangefinder"],
  ["equipment", "ir-goggles", "IR Goggles", "Recon", "equipment", "ir-goggles"],
  ["equipment", "spotted-scope", "Spotted Scope", "Recon", "equipment", "spotted-scope"],
  ["equipment", "wrench", "Wrench", "Vehicle tool", "equipment", "repairtool"],
  ["equipment", "light-drill", "Light Drill", "Vehicle tool", "equipment", "light-drill"],
  ["equipment", "heavy-drill", "Heavy Drill", "Vehicle tool", "equipment", "heavy-drill"],
  ["equipment", "m18-signal-grenade-landing-zone", "M18 Signal Grenade: Landing Zone", "Building", "equipment", "m18-signal-grenade-landing-zone"],
  ["equipment", "m18-signal-grenade-supply-request", "M18 Signal Grenade: Supply Request", "Building", "equipment", "m18-signal-grenade-supply-request"],
  ["equipment", "small-hammer", "Small Hammer", "Building", "equipment", "buildtool"],
  ["equipment", "medium-hammer", "Medium Hammer", "Building", "equipment", "medium-hammer"],
  ["equipment", "large-hammer", "Large Hammer", "Building", "equipment", "large-hammer"],
  ["equipment", "forward-operating-base", "Forward Operating Base", "Building", "equipment", "fob"],
  ["equipment", "arrow", "Arrow", "Misc", "equipment", "arrow"],
  ["equipment", "high-capacity-battery", "High Capacity Battery", "Misc", "equipment", "largebattery"],
  ["equipment", "alpha-card-1", "Alpha Card 1", "Misc", "equipment", "keycard"],
  ["equipment", "bravo-card", "Bravo Card", "Misc", "equipment", "bravo-card"],
  ["equipment", "charlie-card", "Charlie Card", "Misc", "equipment", "charlie-card"],
  ["equipment", "music-tape", "Music Tape", "Misc", "equipment", "musictape"],
  ["equipment", "halligan-bar", "Halligan Bar", "Other", "equipment", "crowbar"],
];

const snapshot = "Community catalogue snapshot - 27 Sep 2026";

export const suppliedArtRecords: readonly CatalogueRecord[] = entries.map(([type, slug, name, subtype, sourceFolder, filename]) => ({
  type,
  slug,
  name,
  subtype,
  image: `/images/catalogue/imported/${sourceFolder}/${filename}.webp`,
  imageAlt: `${name} item artwork from a WARDOGS community catalogue`,
  summary: `${name} appears in the supplied WARDOGS community catalogue snapshot. Current in-game availability, price, and unlock are not independently confirmed.`,
  facts: [{label: "Category", value: subtype}, {label: "Current price", value: "Not verified"}],
  filterValues: [subtype.toLowerCase().replaceAll(" ", "-")],
  detailStatus: "inline",
  evidenceStatus: "community-report",
  evidenceTier: "identifier-only",
  mediaState: "context-only",
  sourceNotes: [`Community catalogue artwork identifies ${name}; current availability, price and performance have not been verified in-game.`],
  dataAsOf: snapshot,
  evidence: {build: snapshot, verifiedAt: "2026-09-27", sourceClass: "community-report", confidence: "observed", current: false},
  changeHistory: [],
}));

export const suppliedArtApprovals = entries.map(([type, slug, name, , sourceFolder, filename]) => ({
  origin: "external-capture" as const,
  recordKey: `${type}/${slug}`,
  image: `/images/catalogue/imported/${sourceFolder}/${filename}.webp`,
  approvedState: "context-only" as const,
  assetKind: "object" as const,
  sourceUrl: `https://wardogshub.gg/${sourceFolder}/${filename}.webp`,
  sourceLabel: "Owner-supplied WARDOGS community catalogue image archive (Sep 2026)",
  capturedAt: `Archive filename for ${name}`,
  retrievedAt: "2026-09-27",
  usageNote: `This image is shown for ${type}/${slug} as community catalogue art only; current-version price, stats and availability remain unverified.`,
}));

const existingMatches = [
  ["equipment", "binoculars", "binoculars"],
  ["equipment", "rangefinder", "rangefinder"],
  ["equipment", "fuel-can", "fuelcan"],
  ["equipment", "battery", "battery"],
  ["medical", "stimpen", "stimpen"],
  ["medical", "enox", "enox"],
  ["medical", "defibrillator", "defibrillator"],
  ["supplies", "build-supply-pallet", "buildtoolsupply"],
  ["supplies", "ammo-supply-pallet", "munitionssupplies"],
  ["supplies", "fuel-supply-pallet", "fuelsupplies"],
  ["supplies", "mechanical-supply-pallet", "sparepartssupplies"],
  ["deployables", "improvised-explosive-device", "ied"],
  ["deployables", "at-mine", "atmine"],
  ["deployables", "claymore", "claymore"],
] as const;

export const existingArtMatches: Readonly<Record<string, string>> = Object.fromEntries(
  existingMatches.map(([type, slug, filename]) => [`${type}/${slug}`, `/images/catalogue/imported/equipment/${filename}.webp`]),
);

export const existingArtApprovals = existingMatches.map(([type, slug, filename]) => ({
  origin: "external-capture" as const,
  recordKey: `${type}/${slug}`,
  image: `/images/catalogue/imported/equipment/${filename}.webp`,
  approvedState: "context-only" as const,
  assetKind: "object" as const,
  sourceUrl: `https://wardogshub.gg/equipment/${filename}.webp`,
  sourceLabel: "Owner-supplied WARDOGS community catalogue image archive (Sep 2026)",
  capturedAt: `Archive filename ${filename}`,
  retrievedAt: "2026-09-27",
  usageNote: `Community catalogue art matched to existing ${type}/${slug}; it does not verify current-build function, price or capacity.`,
}));
