import type {Locale} from "@/config/site";

const en = {
  title: "Attachment compatibility reference",
  intro: "Historical catalogue names and specifications are reference entries, not proof of current installation compatibility. A missing association is not an incompatibility result.",
  weapon: "Weapon", allWeapons: "All weapons", kind: "Attachment", all: "All", magazine: "Magazines", optic: "Optics", search: "Search attachments", namedOnly: "Named model entries only",
  item: "Attachment", named: "Model named in historical catalogue", specification: "Historical capacity / zoom", current: "Current fit", unknown: "Not verified", notNamed: "No specific weapon named", purchase: "Purchase unit / included rounds", unitUnknown: "Not recorded; check the vendor and inventory separately", evidence: "Evidence", empty: "No recorded entries match this selection. This does not establish incompatibility.",
  checklist: "Before committing a loadout", checks: ["Check the exact weapon and magazine model, not just calibre.", "Install the attachment in the current client and verify it remains equipped.", "Compare the purchased unit, magazine contents and loose ammunition in inventory.", "Test reload or scope switching in a safe area before deploying."],
  historical: "Historical record", source: "Original source", archive: "Catalogue evidence policy", copy: "Copy selection link", copied: "Link copied", failed: "Copy failed. The selection is saved in the address bar.", invalid: "This shared selection contains an unknown item. It has not been treated as a valid pairing.", rounds: "rounds", version: "Recorded build", checked: "Source checkpoint", scope: "Artwork identifies the historical item only; it does not verify fit, capacity or supplied ammunition in the current build.",
};

export type CompatibilityCopy = typeof en;
const copy: Record<Locale, CompatibilityCopy> = {
  en,
  "zh-cn": {title: "配件兼容性参考", intro: "历史目录的型号与规格仅供核对，不代表已实测当前版本的安装适配。没有关联记录也不等于不兼容。", weapon: "武器", allWeapons: "全部武器", kind: "配件", all: "全部", magazine: "弹匣", optic: "瞄具", search: "搜索配件", namedOnly: "只看明确命名型号的记录", item: "配件", named: "历史目录明确命名的武器", specification: "历史容量／倍率", current: "当前适配", unknown: "尚未核验", notNamed: "未明确命名具体武器", purchase: "采购单位／附带弹药", unitUnknown: "未记录；分别核对商店与库存", evidence: "证据", empty: "没有符合条件的目录记录。这不代表这些配件不兼容。", checklist: "出击前核对", checks: ["核对武器和弹匣的完整型号，不能只看口径。", "在当前客户端安装配件，确认装备后仍保留。", "分别查看采购单位、弹匣内弹药和库存散装弹药。", "在安全区域测试换弹或切换瞄具，再进入战斗。"], historical: "历史记录", source: "原始来源", archive: "目录证据政策", copy: "复制选择链接", copied: "链接已复制", failed: "复制失败；选择已保存在地址栏。", invalid: "分享链接含未知条目，未将其视为有效搭配。", rounds: "发", version: "记录版本", checked: "来源核验时间", scope: "素材仅标识历史道具，不核实当前版本的适配、容量或附带弹药。"},
  "zh-tw": {title: "配件相容性參考", intro: "歷史目錄的型號與規格僅供核對，不代表已實測目前版本的安裝相容性。沒有關聯紀錄也不等於不相容。", weapon: "武器", allWeapons: "全部武器", kind: "配件", all: "全部", magazine: "彈匣", optic: "瞄具", search: "搜尋配件", namedOnly: "只看明確命名型號的紀錄", item: "配件", named: "歷史目錄明確命名的武器", specification: "歷史容量／倍率", current: "目前相容性", unknown: "尚未核驗", notNamed: "未明確命名具體武器", purchase: "採購單位／附帶彈藥", unitUnknown: "未記錄；分別核對商店與庫存", evidence: "證據", empty: "沒有符合條件的目錄紀錄。這不代表這些配件不相容。", checklist: "出擊前核對", checks: ["核對武器和彈匣的完整型號，不能只看口徑。", "在目前客戶端安裝配件，確認裝備後仍保留。", "分別查看採購單位、彈匣內彈藥和庫存散裝彈藥。", "在安全區域測試換彈或切換瞄具，再進入戰鬥。"], historical: "歷史紀錄", source: "原始來源", archive: "目錄證據政策", copy: "複製選擇連結", copied: "連結已複製", failed: "複製失敗；選擇已儲存在網址列。", invalid: "分享連結含未知項目，未將其視為有效搭配。", rounds: "發", version: "記錄版本", checked: "來源核驗時間", scope: "素材僅標識歷史道具，不核實目前版本的相容性、容量或附帶彈藥。"},
  ja: {title: "アタッチメントの互換性資料", intro: "過去のカタログの名称と仕様は参考情報です。現行版での装着確認ではありません。記録がない組み合わせを非対応と判定しません。", weapon: "武器", allWeapons: "すべての武器", kind: "アタッチメント", all: "すべて", magazine: "マガジン", optic: "照準器", search: "アタッチメントを検索", namedOnly: "武器名が明記された記録のみ", item: "アタッチメント", named: "過去のカタログに記載された武器", specification: "過去の容量・倍率", current: "現行版の装着", unknown: "未確認", notNamed: "具体的な武器名の記録なし", purchase: "購入単位・付属弾薬", unitUnknown: "記録なし。ショップと所持品を別々に確認", evidence: "根拠", empty: "条件に一致する記録がありません。非対応という意味ではありません。", checklist: "出撃前の確認", checks: ["口径だけでなく武器とマガジンの型番を確認する。", "現行クライアントで装着し、装備が保持されるか確認する。", "購入単位、マガジン内の弾、所持品の弾薬を分けて確認する。", "安全な場所でリロードや照準器の切り替えを試す。"], historical: "過去の記録", source: "元の情報源", archive: "カタログの根拠方針", copy: "選択リンクをコピー", copied: "コピー済み", failed: "コピーできません。選択はアドレス欄に保存されています。", invalid: "共有リンクに不明な項目があります。有効な組み合わせとは判定しません。", rounds: "発", version: "記録されたビルド", checked: "情報源の確認日", scope: "画像は過去のアイテム識別用です。現行版の互換性、容量、付属弾薬は証明しません。"},
  ru: {title: "Совместимость модулей оружия", intro: "Названия и характеристики старого каталога служат справкой, а не подтверждением установки в текущей версии. Отсутствие связи не означает несовместимость.", weapon: "Оружие", allWeapons: "Всё оружие", kind: "Модуль", all: "Все", magazine: "Магазины", optic: "Прицелы", search: "Поиск модулей", namedOnly: "Только записи с конкретной моделью", item: "Модуль", named: "Оружие, названное в старом каталоге", specification: "Историческая ёмкость / увеличение", current: "Текущая совместимость", unknown: "Не проверено", notNamed: "Конкретное оружие не указано", purchase: "Единица покупки / патроны в комплекте", unitUnknown: "Не записано; проверьте магазин и инвентарь отдельно", evidence: "Источники", empty: "Подходящих записей нет. Это не доказывает несовместимость.", checklist: "Проверка перед выходом", checks: ["Сверьте модель оружия и магазина, а не только калибр.", "Установите модуль в текущем клиенте и проверьте, что он остался на оружии.", "Отдельно проверьте единицу покупки, патроны в магазине и запас в инвентаре.", "Испытайте перезарядку или переключение прицела в безопасном месте."], historical: "Историческая запись", source: "Первичный источник", archive: "Правила проверки каталога", copy: "Копировать ссылку на выбор", copied: "Ссылка скопирована", failed: "Копирование не удалось. Выбор сохранён в адресной строке.", invalid: "В ссылке есть неизвестный предмет. Он не считается допустимой связкой.", rounds: "патронов", version: "Записанная версия", checked: "Дата проверки источника", scope: "Изображение идентифицирует старый предмет, но не подтверждает совместимость, ёмкость или боекомплект текущей версии."},
  de: {title: "Kompatibilität von Waffenaufsätzen", intro: "Namen und Werte aus dem historischen Katalog sind Referenzen, kein Installationsnachweis im aktuellen Build. Eine fehlende Zuordnung bedeutet nicht inkompatibel.", weapon: "Waffe", allWeapons: "Alle Waffen", kind: "Aufsatz", all: "Alle", magazine: "Magazine", optic: "Optiken", search: "Aufsätze suchen", namedOnly: "Nur ausdrücklich benannte Modelle", item: "Aufsatz", named: "Im historischen Katalog benannte Waffe", specification: "Historische Kapazität / Vergrößerung", current: "Aktuelle Passform", unknown: "Nicht geprüft", notNamed: "Keine konkrete Waffe benannt", purchase: "Kaufeinheit / enthaltene Munition", unitUnknown: "Nicht dokumentiert; Händler und Inventar getrennt prüfen", evidence: "Belege", empty: "Keine passenden Katalogeinträge. Das belegt keine Inkompatibilität.", checklist: "Vor dem Einsatz prüfen", checks: ["Exaktes Waffen- und Magazinmodell prüfen, nicht nur das Kaliber.", "Aufsatz im aktuellen Client montieren und den Verbleib prüfen.", "Kaufeinheit, Magazininhalt und lose Munition getrennt prüfen.", "Nachladen oder Optikwechsel zuerst an einem sicheren Ort testen."], historical: "Historischer Eintrag", source: "Originalquelle", archive: "Katalog-Belegregeln", copy: "Auswahllink kopieren", copied: "Link kopiert", failed: "Kopieren fehlgeschlagen. Die Auswahl steht in der Adressleiste.", invalid: "Der geteilte Link enthält einen unbekannten Gegenstand. Keine gültige Kombination bestätigt.", rounds: "Schuss", version: "Dokumentierter Build", checked: "Quellenprüfdatum", scope: "Das Bild identifiziert nur den historischen Gegenstand, nicht aktuelle Passform, Kapazität oder mitgelieferte Munition."},
  "pt-br": {title: "Compatibilidade de acessórios", intro: "Nomes e especificações do catálogo histórico são referências, não prova de instalação na versão atual. A ausência de vínculo não significa incompatibilidade.", weapon: "Arma", allWeapons: "Todas as armas", kind: "Acessório", all: "Todos", magazine: "Carregadores", optic: "Miras", search: "Buscar acessórios", namedOnly: "Somente modelos nomeados explicitamente", item: "Acessório", named: "Arma citada no catálogo histórico", specification: "Capacidade / ampliação histórica", current: "Encaixe atual", unknown: "Não verificado", notNamed: "Nenhuma arma específica citada", purchase: "Unidade de compra / munição incluída", unitUnknown: "Não registrado; confira a loja e o inventário separadamente", evidence: "Evidências", empty: "Nenhum registro corresponde à seleção. Isso não comprova incompatibilidade.", checklist: "Verificar antes de sair", checks: ["Confira o modelo exato da arma e do carregador, não apenas o calibre.", "Instale o acessório no cliente atual e confirme que continua equipado.", "Separe unidade comprada, munição no carregador e munição solta do inventário.", "Teste recarga ou troca de mira em um local seguro."], historical: "Registro histórico", source: "Fonte original", archive: "Política de evidências do catálogo", copy: "Copiar link da seleção", copied: "Link copiado", failed: "Falha ao copiar. A seleção está salva na barra de endereço.", invalid: "O link contém um item desconhecido. Ele não foi considerado uma combinação válida.", rounds: "cartuchos", version: "Versão registrada", checked: "Data de verificação da fonte", scope: "A imagem identifica apenas o item histórico; não confirma encaixe, capacidade ou munição incluída na versão atual."},
  pl: {title: "Zgodność akcesoriów broni", intro: "Nazwy i parametry ze starego katalogu są materiałem referencyjnym, a nie testem montażu w bieżącej wersji. Brak powiązania nie oznacza niezgodności.", weapon: "Broń", allWeapons: "Wszystkie bronie", kind: "Dodatek", all: "Wszystkie", magazine: "Magazynki", optic: "Celowniki", search: "Szukaj dodatków", namedOnly: "Tylko wpisy z nazwanym modelem", item: "Dodatek", named: "Broń nazwana w historycznym katalogu", specification: "Historyczna pojemność / powiększenie", current: "Bieżący montaż", unknown: "Niezweryfikowany", notNamed: "Nie wskazano konkretnej broni", purchase: "Jednostka zakupu / dołączona amunicja", unitUnknown: "Brak zapisu; sprawdź sklep i ekwipunek osobno", evidence: "Źródła", empty: "Brak pasujących wpisów. To nie dowodzi niezgodności.", checklist: "Przed wyruszeniem", checks: ["Sprawdź dokładny model broni i magazynka, nie tylko kaliber.", "Zamontuj dodatek w obecnym kliencie i sprawdź, czy pozostaje wyposażony.", "Osobno sprawdź jednostkę zakupu, zawartość magazynka i luźną amunicję.", "Przetestuj przeładowanie lub zmianę celownika w bezpiecznym miejscu."], historical: "Historyczny wpis", source: "Oryginalne źródło", archive: "Zasady weryfikacji katalogu", copy: "Kopiuj link wyboru", copied: "Link skopiowany", failed: "Kopiowanie nie powiodło się. Wybór zapisano w pasku adresu.", invalid: "Link zawiera nieznany przedmiot. Nie uznano go za poprawne połączenie.", rounds: "nabojów", version: "Zapisana wersja", checked: "Data weryfikacji źródła", scope: "Grafika identyfikuje historyczny przedmiot, nie potwierdza montażu, pojemności ani dołączonej amunicji w bieżącej wersji."},
};

export function getCompatibilityCopy(locale: Locale) { return copy[locale]; }
