import type {Locale} from "@/config/site";
import type {CatalogueEvidence} from "@/features/catalogue/catalogue-types";

const copy = {
  en: {
    systemTitle: "WARDOGS PC Configuration Check",
    systemDescription: "Compare your declared PC with the official Windows minimum and recommended tiers. This does not benchmark your hardware.",
    budgetTitle: "WARDOGS Loadout Budget",
    budgetDescription: "Plan a life using amounts from the build you are playing. No pre-release catalogue price is inserted automatically.",
    officialBasis: "Official requirement basis",
    os: "Operating system",
    ram: "Installed RAM (GB)",
    storage: "Free storage (GB)",
    cpu: "CPU comparison",
    gpu: "GPU comparison",
    windows10: "Windows 10, 64-bit",
    windows11: "Windows 11, 64-bit",
    unsupported: "Older Windows or another OS",
    below: "Below minimum",
    minimum: "Minimum class",
    recommended: "Recommended class",
    unknown: "Not sure",
    result: "Result",
    resultBelow: "Below the advertised minimum",
    resultReview: "Manual comparison needed",
    resultMinimum: "Meets the advertised minimum tier",
    resultRecommended: "Meets the advertised recommended tier",
    limiting: "Review",
    share: "Copy result link",
    copied: "Result link copied",
    cash: "Cash available",
    loadout: "Weapons, ammo and gear",
    vehicle: "Vehicle or team purchase",
    reserve: "Reserve target",
    spent: "Planned spend",
    remaining: "Cash remaining",
    reserveMet: "Reserve protected",
    reserveMissed: "Reserve shortfall",
    buildWarning: "Prices and balance are build-sensitive. Enter the values shown in your current game client.",
    source: "Open official Steam requirements",
  },
  de: {
    systemTitle: "WARDOGS PC-Konfigurationscheck", systemDescription: "Vergleiche deine Angaben mit den offiziellen Windows-Mindest- und empfohlenen Anforderungen. Dies ist kein Benchmark.",
    budgetTitle: "WARDOGS Loadout-Budget", budgetDescription: "Plane ein Leben mit den Preisen deines aktuellen Builds. Vorabpreise werden nicht automatisch eingesetzt.",
    officialBasis: "Offizielle Anforderungsbasis", os: "Betriebssystem", ram: "Installierter RAM (GB)", storage: "Freier Speicher (GB)", cpu: "CPU-Vergleich", gpu: "GPU-Vergleich",
    windows10: "Windows 10, 64-Bit", windows11: "Windows 11, 64-Bit", unsupported: "Älteres Windows oder anderes OS", below: "Unter Minimum", minimum: "Mindestklasse", recommended: "Empfohlene Klasse", unknown: "Unsicher",
    result: "Ergebnis", resultBelow: "Unter dem veröffentlichten Minimum", resultReview: "Manueller Vergleich nötig", resultMinimum: "Erfüllt die veröffentlichte Mindeststufe", resultRecommended: "Erfüllt die empfohlene Stufe", limiting: "Prüfen", share: "Ergebnislink kopieren", copied: "Ergebnislink kopiert",
    cash: "Verfügbares Geld", loadout: "Waffen, Munition und Ausrüstung", vehicle: "Fahrzeug- oder Teamkauf", reserve: "Reserveziel", spent: "Geplante Ausgaben", remaining: "Verbleibendes Geld", reserveMet: "Reserve geschützt", reserveMissed: "Reserve unterschritten", buildWarning: "Preise und Balance hängen vom Build ab. Nutze die Werte aus deinem aktuellen Spielclient.", source: "Offizielle Steam-Anforderungen öffnen",
  },
  ru: {
    systemTitle: "Проверка конфигурации ПК для WARDOGS", systemDescription: "Сравните указанный ПК с официальными минимальными и рекомендуемыми требованиями Windows. Это не тест производительности.",
    budgetTitle: "Бюджет комплекта WARDOGS", budgetDescription: "Планируйте одну жизнь по ценам текущей сборки. Цены из предварительных версий не подставляются.",
    officialBasis: "Официальные требования", os: "Операционная система", ram: "ОЗУ (ГБ)", storage: "Свободное место (ГБ)", cpu: "Сравнение CPU", gpu: "Сравнение GPU",
    windows10: "Windows 10, 64-разрядная", windows11: "Windows 11, 64-разрядная", unsupported: "Старая Windows или другая ОС", below: "Ниже минимума", minimum: "Минимальный класс", recommended: "Рекомендуемый класс", unknown: "Не уверен",
    result: "Результат", resultBelow: "Ниже заявленного минимума", resultReview: "Нужно ручное сравнение", resultMinimum: "Соответствует заявленному минимуму", resultRecommended: "Соответствует рекомендуемому уровню", limiting: "Проверить", share: "Копировать ссылку", copied: "Ссылка скопирована",
    cash: "Доступные средства", loadout: "Оружие, боеприпасы и снаряжение", vehicle: "Транспорт или командная покупка", reserve: "Целевой резерв", spent: "Планируемые расходы", remaining: "Остаток", reserveMet: "Резерв сохранён", reserveMissed: "Резерва не хватает", buildWarning: "Цены и баланс зависят от сборки. Введите значения из текущего клиента игры.", source: "Открыть требования в Steam",
  },
  "pt-br": {
    systemTitle: "Verificador de configuração de WARDOGS", systemDescription: "Compare o PC informado com os requisitos oficiais mínimo e recomendado para Windows. Isto não é um benchmark.",
    budgetTitle: "Orçamento de equipamento de WARDOGS", budgetDescription: "Planeje uma vida com os valores da build atual. Nenhum preço de pré-lançamento é preenchido automaticamente.",
    officialBasis: "Base oficial de requisitos", os: "Sistema operacional", ram: "RAM instalada (GB)", storage: "Armazenamento livre (GB)", cpu: "Comparação de CPU", gpu: "Comparação de GPU",
    windows10: "Windows 10, 64 bits", windows11: "Windows 11, 64 bits", unsupported: "Windows antigo ou outro sistema", below: "Abaixo do mínimo", minimum: "Classe mínima", recommended: "Classe recomendada", unknown: "Não tenho certeza",
    result: "Resultado", resultBelow: "Abaixo do mínimo divulgado", resultReview: "Comparação manual necessária", resultMinimum: "Atende ao nível mínimo divulgado", resultRecommended: "Atende ao nível recomendado", limiting: "Revisar", share: "Copiar link do resultado", copied: "Link do resultado copiado",
    cash: "Dinheiro disponível", loadout: "Armas, munição e equipamento", vehicle: "Veículo ou compra da equipe", reserve: "Reserva desejada", spent: "Gasto planejado", remaining: "Dinheiro restante", reserveMet: "Reserva protegida", reserveMissed: "Reserva insuficiente", buildWarning: "Preços e balanceamento dependem da build. Informe os valores mostrados no cliente atual.", source: "Abrir requisitos oficiais na Steam",
  },
  ja: {
    systemTitle: "WARDOGS PC構成チェック", systemDescription: "入力したPCを公式のWindows最低・推奨要件と比較します。ベンチマークではありません。",
    budgetTitle: "WARDOGS ロードアウト予算", budgetDescription: "現在プレイ中のビルドに表示された金額で1ライフを計画します。旧ビルド価格は自動入力しません。",
    officialBasis: "公式要件に基づく比較", os: "OS", ram: "搭載RAM (GB)", storage: "空き容量 (GB)", cpu: "CPU比較", gpu: "GPU比較",
    windows10: "Windows 10 64-bit", windows11: "Windows 11 64-bit", unsupported: "古いWindowsまたは別OS", below: "最低未満", minimum: "最低クラス", recommended: "推奨クラス", unknown: "不明",
    result: "結果", resultBelow: "公表された最低要件未満", resultReview: "手動確認が必要", resultMinimum: "公表された最低要件を満たす", resultRecommended: "公表された推奨要件を満たす", limiting: "確認項目", share: "結果リンクをコピー", copied: "結果リンクをコピーしました",
    cash: "利用可能な資金", loadout: "武器・弾薬・装備", vehicle: "車両またはチーム購入", reserve: "残す資金", spent: "支出予定", remaining: "残金", reserveMet: "予備資金を確保", reserveMissed: "予備資金不足", buildWarning: "価格とバランスはビルドで変わります。現在のゲーム内表示額を入力してください。", source: "Steamの公式要件を見る",
  },
  "zh-cn": {
    systemTitle: "WARDOGS 电脑配置检测", systemDescription: "把你填写的电脑配置与 Steam 官方 Windows 最低、推荐配置比较。本工具不运行性能测试。",
    budgetTitle: "WARDOGS 配装预算工具", budgetDescription: "使用当前游戏版本里显示的价格规划一次生命，不自动套用测试版本旧价格。",
    officialBasis: "官方配置依据", os: "操作系统", ram: "内存容量 (GB)", storage: "可用硬盘空间 (GB)", cpu: "CPU 对比", gpu: "显卡对比",
    windows10: "Windows 10 64 位", windows11: "Windows 11 64 位", unsupported: "旧版 Windows 或其他系统", below: "低于最低配置", minimum: "最低配置级别", recommended: "推荐配置级别", unknown: "不确定",
    result: "检测结果", resultBelow: "低于官方公布的最低配置", resultReview: "需要手动核对", resultMinimum: "达到官方公布的最低配置", resultRecommended: "达到官方公布的推荐配置", limiting: "需要复核", share: "复制结果链接", copied: "结果链接已复制",
    cash: "可用资金", loadout: "武器、弹药和装备", vehicle: "载具或团队支出", reserve: "计划保留资金", spent: "计划支出", remaining: "剩余资金", reserveMet: "已保留预算", reserveMissed: "未达到保留目标", buildWarning: "价格和平衡会随版本变化，请输入你当前游戏客户端中显示的数值。", source: "查看 Steam 官方配置",
  },
} as const;

const evidenceToolCopy = {
  en: {
    weaponCompareTitle: "WARDOGS Weapon Compare",
    weaponCompareDescription: "Compare only documented weapon fields. Every value keeps its source build and current, historical, or unknown evidence state.",
    weaponCompareEyebrow: "Evidence-first loadout tool",
    ammoMatcherTitle: "WARDOGS Ammo Matcher",
    ammoMatcherDescription: "Look up weapon-to-ammunition and ammunition-to-weapon relationships only when the catalogue records an explicit match.",
    ammoMatcherEyebrow: "Explicit catalogue relationships",
    leftWeapon: "First weapon",
    rightWeapon: "Second weapon",
    selectWeapon: "Select a weapon",
    selectAmmo: "Select ammunition",
    comparison: "Documented field comparison",
    weaponToAmmo: "Ammunition recorded for this weapon",
    ammoToWeapons: "Weapons recorded for this ammunition",
    currentEvidence: "Current",
    historicalEvidence: "Historical",
    unknownEvidence: "Unknown",
    historicalWarning: "Historical observations are not current-build recommendations.",
    build: "Build",
    verified: "Verified",
    fieldRole: "Role",
    fieldPrice: "Observed cost",
    fieldAmmunition: "Ammunition",
    fieldFireModes: "Fire modes",
    fieldWeight: "Weight",
    fieldProgression: "Progression gate",
    fieldRequiredLevel: "Required level",
    strengths: "Documented context",
    cautions: "Evidence cautions",
    openItem: "Open evidence page",
    noConfirmedAmmo: "No confirmed ammunition relationship is recorded for this weapon.",
    noConfirmedWeapons: "No confirmed weapon relationship is recorded for this ammunition.",
    emptyMatcher: "Choose a weapon, ammunition type, or both to inspect the recorded relationships.",
    copyToolLink: "Copy tool link",
    copiedToolLink: "Tool link copied",
  },
  de: {
    weaponCompareTitle: "WARDOGS Waffenvergleich",
    weaponCompareDescription: "Vergleiche nur dokumentierte Waffenfelder. Jeder Wert behält Build sowie aktuellen, historischen oder unbekannten Belegstatus.",
    weaponCompareEyebrow: "Beleggestütztes Loadout-Werkzeug",
    ammoMatcherTitle: "WARDOGS Munitionszuordnung",
    ammoMatcherDescription: "Zeigt Waffen-Munitions-Beziehungen nur dann, wenn der Katalog eine ausdrückliche Zuordnung enthält.",
    ammoMatcherEyebrow: "Explizite Katalogbeziehungen",
    leftWeapon: "Erste Waffe", rightWeapon: "Zweite Waffe", selectWeapon: "Waffe auswählen", selectAmmo: "Munition auswählen", comparison: "Dokumentierter Feldvergleich",
    weaponToAmmo: "Für diese Waffe erfasste Munition", ammoToWeapons: "Für diese Munition erfasste Waffen", currentEvidence: "Aktuell", historicalEvidence: "Historisch", unknownEvidence: "Unbekannt",
    historicalWarning: "Historische Beobachtungen sind keine Empfehlungen für den aktuellen Build.", build: "Build", verified: "Geprüft", fieldRole: "Rolle", fieldPrice: "Beobachtete Kosten", fieldAmmunition: "Munition", fieldFireModes: "Feuermodi", fieldWeight: "Gewicht", fieldProgression: "Fortschrittsbedingung", fieldRequiredLevel: "Benötigte Stufe",
    strengths: "Dokumentierter Kontext", cautions: "Beleggrenzen", openItem: "Belegseite öffnen", noConfirmedAmmo: "Für diese Waffe ist keine bestätigte Munitionsbeziehung erfasst.", noConfirmedWeapons: "Für diese Munition ist keine bestätigte Waffenbeziehung erfasst.", emptyMatcher: "Wähle eine Waffe, Munition oder beides, um erfasste Beziehungen zu prüfen.", copyToolLink: "Werkzeuglink kopieren", copiedToolLink: "Werkzeuglink kopiert",
  },
  ru: {
    weaponCompareTitle: "Сравнение оружия WARDOGS",
    weaponCompareDescription: "Сравнивайте только документированные поля. Для каждого значения сохраняются сборка и статус: актуальное, историческое или неизвестное.",
    weaponCompareEyebrow: "Инструмент на основе источников",
    ammoMatcherTitle: "Подбор боеприпасов WARDOGS",
    ammoMatcherDescription: "Связи оружия и боеприпасов показываются только при наличии прямой записи в каталоге.",
    ammoMatcherEyebrow: "Явные связи каталога",
    leftWeapon: "Первое оружие", rightWeapon: "Второе оружие", selectWeapon: "Выберите оружие", selectAmmo: "Выберите боеприпас", comparison: "Сравнение документированных полей",
    weaponToAmmo: "Боеприпасы, записанные для этого оружия", ammoToWeapons: "Оружие, записанное для этого боеприпаса", currentEvidence: "Актуально", historicalEvidence: "Исторические данные", unknownEvidence: "Неизвестно",
    historicalWarning: "Исторические наблюдения не являются рекомендацией для текущей сборки.", build: "Сборка", verified: "Проверено", fieldRole: "Роль", fieldPrice: "Наблюдавшаяся цена", fieldAmmunition: "Боеприпасы", fieldFireModes: "Режимы огня", fieldWeight: "Вес", fieldProgression: "Условие прогресса", fieldRequiredLevel: "Требуемый уровень",
    strengths: "Документированный контекст", cautions: "Ограничения данных", openItem: "Открыть страницу источников", noConfirmedAmmo: "Для этого оружия не записана подтверждённая связь с боеприпасом.", noConfirmedWeapons: "Для этого боеприпаса не записана подтверждённая связь с оружием.", emptyMatcher: "Выберите оружие, боеприпас или оба варианта для проверки записанных связей.", copyToolLink: "Копировать ссылку", copiedToolLink: "Ссылка скопирована",
  },
  "pt-br": {
    weaponCompareTitle: "Comparador de armas de WARDOGS",
    weaponCompareDescription: "Compare apenas campos documentados. Cada valor mantém a build de origem e o estado atual, histórico ou desconhecido.",
    weaponCompareEyebrow: "Ferramenta baseada em evidências",
    ammoMatcherTitle: "Correspondência de munição de WARDOGS",
    ammoMatcherDescription: "Consulte relações entre armas e munições somente quando houver uma correspondência explícita no catálogo.",
    ammoMatcherEyebrow: "Relações explícitas do catálogo",
    leftWeapon: "Primeira arma", rightWeapon: "Segunda arma", selectWeapon: "Selecione uma arma", selectAmmo: "Selecione a munição", comparison: "Comparação de campos documentados",
    weaponToAmmo: "Munição registrada para esta arma", ammoToWeapons: "Armas registradas para esta munição", currentEvidence: "Atual", historicalEvidence: "Histórico", unknownEvidence: "Desconhecido",
    historicalWarning: "Observações históricas não são recomendações para a build atual.", build: "Build", verified: "Verificado", fieldRole: "Função", fieldPrice: "Custo observado", fieldAmmunition: "Munição", fieldFireModes: "Modos de disparo", fieldWeight: "Peso", fieldProgression: "Requisito de progressão", fieldRequiredLevel: "Nível necessário",
    strengths: "Contexto documentado", cautions: "Limites da evidência", openItem: "Abrir página de evidências", noConfirmedAmmo: "Nenhuma relação confirmada de munição foi registrada para esta arma.", noConfirmedWeapons: "Nenhuma relação confirmada de arma foi registrada para esta munição.", emptyMatcher: "Escolha uma arma, munição ou ambas para consultar as relações registradas.", copyToolLink: "Copiar link da ferramenta", copiedToolLink: "Link da ferramenta copiado",
  },
  ja: {
    weaponCompareTitle: "WARDOGS 武器比較",
    weaponCompareDescription: "記録済みの項目だけを比較します。各値には、出典ビルドと現行・履歴・不明の証拠状態を表示します。",
    weaponCompareEyebrow: "証拠優先のロードアウトツール",
    ammoMatcherTitle: "WARDOGS 弾薬対応表",
    ammoMatcherDescription: "カタログに明示された関係だけを使って、武器から弾薬、弾薬から武器を検索します。",
    ammoMatcherEyebrow: "カタログの明示的な対応関係",
    leftWeapon: "1つ目の武器", rightWeapon: "2つ目の武器", selectWeapon: "武器を選択", selectAmmo: "弾薬を選択", comparison: "記録済み項目の比較",
    weaponToAmmo: "この武器に記録された弾薬", ammoToWeapons: "この弾薬に記録された武器", currentEvidence: "現行", historicalEvidence: "履歴", unknownEvidence: "不明",
    historicalWarning: "過去ビルドの観察値は、現行ビルドの推奨値ではありません。", build: "ビルド", verified: "確認日", fieldRole: "役割", fieldPrice: "確認済み価格", fieldAmmunition: "弾薬", fieldFireModes: "射撃モード", fieldWeight: "重量", fieldProgression: "進行条件", fieldRequiredLevel: "必要レベル",
    strengths: "記録済みの文脈", cautions: "証拠上の注意", openItem: "証拠ページを開く", noConfirmedAmmo: "この武器には確認済みの弾薬対応が記録されていません。", noConfirmedWeapons: "この弾薬には確認済みの武器対応が記録されていません。", emptyMatcher: "武器、弾薬、または両方を選択して記録済みの関係を確認してください。", copyToolLink: "ツールリンクをコピー", copiedToolLink: "ツールリンクをコピーしました",
  },
  "zh-cn": {
    weaponCompareTitle: "WARDOGS 武器对比工具",
    weaponCompareDescription: "只对比已经记录的武器字段。每个值都保留来源版本，并明确标注当前、历史或未知状态。",
    weaponCompareEyebrow: "证据优先的配装工具",
    ammoMatcherTitle: "WARDOGS 武器弹药匹配器",
    ammoMatcherDescription: "仅在图鉴存在明确关系时，查询武器对应弹药或弹药对应武器，不根据名称猜测兼容性。",
    ammoMatcherEyebrow: "图鉴中的明确对应关系",
    leftWeapon: "第一把武器", rightWeapon: "第二把武器", selectWeapon: "选择武器", selectAmmo: "选择弹药", comparison: "已记录字段对比",
    weaponToAmmo: "该武器已记录的弹药", ammoToWeapons: "该弹药已记录的武器", currentEvidence: "当前", historicalEvidence: "历史", unknownEvidence: "未知",
    historicalWarning: "历史版本观察值不是当前版本推荐。", build: "版本", verified: "核查日期", fieldRole: "定位", fieldPrice: "已观察价格", fieldAmmunition: "弹药", fieldFireModes: "射击模式", fieldWeight: "重量", fieldProgression: "进度门槛", fieldRequiredLevel: "所需等级",
    strengths: "已记录使用背景", cautions: "证据限制", openItem: "打开证据页面", noConfirmedAmmo: "图鉴尚未记录该武器的明确弹药关系。", noConfirmedWeapons: "图鉴尚未记录该弹药的明确武器关系。", emptyMatcher: "选择武器、弹药或同时选择两者，查看已记录的对应关系。", copyToolLink: "复制工具链接", copiedToolLink: "工具链接已复制",
  },
} as const;

const evidenceProvenanceCopy = {
  en: {
    sourceClass: "Source class",
    confidence: "Confidence",
    sourceOfficial: "Official",
    sourceLiveClient: "Live client",
    sourceCreatorCurrent: "Current creator source",
    sourceCreatorHistorical: "Historical creator source",
    sourceCommunityReport: "Community report",
    confidenceConfirmed: "Confirmed",
    confidenceObserved: "Observed",
    confidenceCorroborated: "Corroborated",
    confidenceUnverified: "Unverified",
  },
  de: {
    sourceClass: "Quellenklasse",
    confidence: "Vertrauensniveau",
    sourceOfficial: "Offiziell",
    sourceLiveClient: "Live-Client",
    sourceCreatorCurrent: "Aktuelle Creator-Quelle",
    sourceCreatorHistorical: "Historische Creator-Quelle",
    sourceCommunityReport: "Community-Bericht",
    confidenceConfirmed: "Bestätigt",
    confidenceObserved: "Beobachtet",
    confidenceCorroborated: "Gegengeprüft",
    confidenceUnverified: "Unbestätigt",
  },
  ru: {
    sourceClass: "Класс источника",
    confidence: "Уверенность",
    sourceOfficial: "Официальный",
    sourceLiveClient: "Текущий клиент",
    sourceCreatorCurrent: "Актуальный материал автора",
    sourceCreatorHistorical: "Исторический материал автора",
    sourceCommunityReport: "Сообщение сообщества",
    confidenceConfirmed: "Подтверждено",
    confidenceObserved: "Наблюдалось",
    confidenceCorroborated: "Сверено",
    confidenceUnverified: "Не проверено",
  },
  "pt-br": {
    sourceClass: "Classe da fonte",
    confidence: "Confiança",
    sourceOfficial: "Oficial",
    sourceLiveClient: "Cliente ao vivo",
    sourceCreatorCurrent: "Criador atual",
    sourceCreatorHistorical: "Criador histórico",
    sourceCommunityReport: "Relato da comunidade",
    confidenceConfirmed: "Confirmado",
    confidenceObserved: "Observado",
    confidenceCorroborated: "Corroborado",
    confidenceUnverified: "Não verificado",
  },
  ja: {
    sourceClass: "出典区分",
    confidence: "信頼度",
    sourceOfficial: "公式",
    sourceLiveClient: "現行クライアント",
    sourceCreatorCurrent: "現行クリエイター資料",
    sourceCreatorHistorical: "過去クリエイター資料",
    sourceCommunityReport: "コミュニティ報告",
    confidenceConfirmed: "確認済み",
    confidenceObserved: "観測済み",
    confidenceCorroborated: "裏付けあり",
    confidenceUnverified: "未検証",
  },
  "zh-cn": {
    sourceClass: "来源类别",
    confidence: "可信度",
    sourceOfficial: "官方",
    sourceLiveClient: "当前客户端",
    sourceCreatorCurrent: "当前创作者资料",
    sourceCreatorHistorical: "历史创作者资料",
    sourceCommunityReport: "社区报告",
    confidenceConfirmed: "已确认",
    confidenceObserved: "已观察",
    confidenceCorroborated: "已交叉验证",
    confidenceUnverified: "未验证",
  },
} as const;

const plannerToolCopy = {
  en: {
    progressionRouteTitle: "WARDOGS Progression Route",
    progressionRouteDescription: "Choose one of the six live role tracks, record your current level, and review only officially published Season 1 changes. No XP rate or time estimate is invented.",
    progressionRouteEyebrow: "Source-backed role planning",
    logisticsPlannerTitle: "WARDOGS FOB and Logistics Planner",
    logisticsPlannerDescription: "Arrange a reusable operation checklist for spawn, construction, supply, transport, defense, and recovery without inserting unverified costs, capacities, distances, or travel times.",
    logisticsPlannerEyebrow: "Ordered team operations",
    selectRole: "Role track",
    currentLevel: "Current level shown in your client",
    currentLevelOptional: "Optional; leave blank when unknown",
    routeGoal: "Goal",
    routeDuty: "Evidence boundary",
    nextUsefulAction: "Next useful action",
    durationEstimate: "Time estimate",
    unknownDuration: "Unknown. The official Season 1 source does not publish hours, match counts, or XP-per-hour rates.",
    confirmedSeasonChanges: "Confirmed Season 1 changes",
    noPublishedRoleChanges: "The published Season 1 changelog lists no role-specific unlock move for this track. Check the live client instead of assuming an order.",
    previousValue: "Previous",
    currentValue: "Season 1",
    officialSource: "Open official Season 1 source",
    checkedOn: "Checked",
    availableStages: "Available stages",
    selectedPlan: "Selected operation order",
    emptyLogisticsPlan: "No stages selected. Add at least one stage to create a shareable operation checklist.",
    includeStage: "Include stage",
    moveEarlier: "Move earlier",
    moveLater: "Move later",
    roles: {
      assault: {label: "Assault", goal: "Plan the next Assault-track decision from the live menu.", duty: "Season 1 names the track, but the published changelog does not list an Assault-specific unlock move.", nextAction: "Open the live Assault track, enter the displayed level, and verify the next item before spending."},
      medic: {label: "Medic", goal: "Check the current Medic order around the confirmed PP-19 magazine change.", duty: "Only the published PP-19 50-round drum level move is treated as current evidence.", nextAction: "Compare your displayed Medic level with the live PP-19 magazine gate and inspect the next client-listed unlock."},
      recon: {label: "Recon", goal: "Review Recon unlock spending against the confirmed scope price changes.", duty: "The source confirms two scope unlock price changes, not a complete Recon order or leveling rate.", nextAction: "Check both live scope entries and the next Recon unlock before committing cash."},
      support: {label: "Support", goal: "Review the Support route around the confirmed hammer changes.", duty: "Hammer unlock price and level changes are current; other Support ordering stays client-verified.", nextAction: "Check the live Medium and Large Hammer entries, then choose the next support task your team actually needs."},
      driver: {label: "Driver", goal: "Review the Driver route with the Season 1 vehicle and supply moves in view.", duty: "Only the vehicle, crate, tape, and track moves listed by the official changelog are treated as current.", nextAction: "Open the Driver track, compare your level with the confirmed moves, and verify the next usable vehicle in the client."},
      pilot: {label: "Pilot", goal: "Review Pilot spending around the confirmed aircraft and supply-crate changes.", duty: "The source confirms selected unlock prices and one item moving out of Pilot, not a complete Pilot ladder.", nextAction: "Check the live Pilot track for the supply crate, Little Bird, and Z20 entries before spending."},
    },
    logisticsStages: {
      spawn: {title: "Spawn", action: "Confirm where the team needs a spawn, then verify the live FOB vendor before committing resources.", evidenceNote: "Season 1 confirms the FOB vendor price change; placement rules still need the live client."},
      construction: {title: "Construction", action: "Agree on the structure and placement first; build only after the current hammer and vendor entries are visible.", evidenceNote: "Season 1 confirms Large Hammer vendor, Support unlock, and required-level changes."},
      supply: {title: "Supply", action: "Ask which resource is needed, confirm loading and transfer, then verify that the destination stock changed.", evidenceNote: "Season 1 confirms a Large Supply Crate level move; capacity and transfer values are not inserted."},
      transport: {title: "Transport", action: "Assign a driver, route, destination, and return plan before moving the vehicle.", evidenceNote: "Season 1 confirms selected Driver vehicle and progression changes; distance and travel time remain unstated."},
      defense: {title: "Defense", action: "Cover approaches and protect the spawn, builders, and deliveries without assuming a final coverage value.", evidenceNote: "The approved source does not publish a complete current defense cost, range, or capacity table."},
      recovery: {title: "Recovery", action: "Recover reusable assets when safe, report losses, and restart the checklist from the team's current need.", evidenceNote: "No official recovery timing, refund, or salvage value is inserted."},
    },
  },
  de: {
    progressionRouteTitle: "WARDOGS-Fortschrittsroute", progressionRouteDescription: "Wähle eine der sechs Rollen, notiere deine aktuelle Stufe und prüfe nur offiziell veröffentlichte Änderungen aus Season 1. XP-Raten und Zeitangaben werden nicht erfunden.", progressionRouteEyebrow: "Rollenplanung mit Quellen",
    logisticsPlannerTitle: "WARDOGS FOB- und Logistikplaner", logisticsPlannerDescription: "Ordne eine wiederverwendbare Einsatzliste für Spawn, Bau, Nachschub, Transport, Verteidigung und Bergung, ohne unbestätigte Kosten, Kapazitäten, Entfernungen oder Fahrzeiten einzusetzen.", logisticsPlannerEyebrow: "Geordnete Teamoperationen",
    selectRole: "Rollenpfad", currentLevel: "Aktuelle Stufe im Spielclient", currentLevelOptional: "Optional; bei Unklarheit leer lassen", routeGoal: "Ziel", routeDuty: "Beleggrenze", nextUsefulAction: "Nächster sinnvoller Schritt", durationEstimate: "Zeitschätzung", unknownDuration: "Unbekannt. Die offizielle Season-1-Quelle nennt weder Stunden noch Matchzahlen oder XP pro Stunde.", confirmedSeasonChanges: "Bestätigte Season-1-Änderungen", noPublishedRoleChanges: "Der veröffentlichte Season-1-Changelog nennt keine rollenspezifische Verschiebung für diesen Pfad. Prüfe den Live-Client, statt eine Reihenfolge anzunehmen.", previousValue: "Vorher", currentValue: "Season 1", officialSource: "Offizielle Season-1-Quelle öffnen", checkedOn: "Geprüft", availableStages: "Verfügbare Phasen", selectedPlan: "Gewählte Einsatzreihenfolge", emptyLogisticsPlan: "Keine Phase ausgewählt. Füge mindestens eine Phase für eine teilbare Einsatzliste hinzu.", includeStage: "Phase aufnehmen", moveEarlier: "Nach vorne", moveLater: "Nach hinten",
    roles: {
      assault: {label: "Assault", goal: "Plane die nächste Entscheidung im Assault-Pfad über das Live-Menü.", duty: "Season 1 nennt den Pfad, veröffentlicht aber keine Assault-spezifische Freischaltungsverschiebung.", nextAction: "Öffne den Live-Assault-Pfad, trage die angezeigte Stufe ein und prüfe das nächste Objekt vor dem Kauf."},
      medic: {label: "Medic", goal: "Prüfe die aktuelle Medic-Reihenfolge rund um die bestätigte PP-19-Magazinänderung.", duty: "Nur die veröffentlichte Stufenverschiebung des PP-19-Trommelmagazins gilt als aktueller Beleg.", nextAction: "Vergleiche deine Medic-Stufe mit der Live-Freischaltung und prüfe den nächsten Eintrag im Client."},
      recon: {label: "Recon", goal: "Prüfe Recon-Ausgaben anhand der bestätigten Zielfernrohrpreise.", duty: "Bestätigt sind zwei Preisänderungen, keine vollständige Reihenfolge oder Levelrate.", nextAction: "Prüfe beide Zielfernrohre und die nächste Recon-Freischaltung vor der Ausgabe."},
      support: {label: "Support", goal: "Prüfe den Support-Pfad rund um die bestätigten Hammeränderungen.", duty: "Hammerpreis und Stufenänderung sind aktuell; die übrige Reihenfolge bleibt im Client zu prüfen.", nextAction: "Prüfe Medium und Large Hammer live und wähle danach die tatsächlich benötigte Teamaufgabe."},
      driver: {label: "Driver", goal: "Prüfe den Driver-Pfad mit den Season-1-Verschiebungen für Fahrzeuge und Nachschub.", duty: "Nur die offiziell genannten Fahrzeug-, Kisten-, Band- und Pfadänderungen gelten als aktuell.", nextAction: "Öffne Driver, vergleiche deine Stufe mit den bestätigten Änderungen und prüfe das nächste nutzbare Fahrzeug."},
      pilot: {label: "Pilot", goal: "Prüfe Pilot-Ausgaben rund um bestätigte Flugzeug- und Nachschubänderungen.", duty: "Bestätigt sind ausgewählte Preise und ein aus Pilot verschobenes Objekt, nicht der gesamte Pfad.", nextAction: "Prüfe Nachschubkiste, Little Bird und Z20 im Live-Pilotpfad vor dem Kauf."},
    },
    logisticsStages: {
      spawn: {title: "Spawn", action: "Kläre den benötigten Spawnort und prüfe den Live-FOB-Händler vor dem Ressourceneinsatz.", evidenceNote: "Season 1 bestätigt die FOB-Preisänderung; Platzierungsregeln bleiben im Client zu prüfen."},
      construction: {title: "Bau", action: "Einigt euch zuerst auf Bauwerk und Position; baut erst nach Prüfung der aktuellen Hammer- und Händlereinträge.", evidenceNote: "Season 1 bestätigt Händlerpreis, Support-Freischaltung und Stufe des Large Hammer."},
      supply: {title: "Nachschub", action: "Frage nach der benötigten Ressource, bestätige Ladung und Übergabe und prüfe den Zielbestand.", evidenceNote: "Season 1 bestätigt eine Stufenänderung der Large Supply Crate; Kapazitäten werden nicht eingesetzt."},
      transport: {title: "Transport", action: "Bestimmt Fahrer, Route, Ziel und Rückkehrplan, bevor das Fahrzeug bewegt wird.", evidenceNote: "Season 1 bestätigt ausgewählte Driver-Änderungen; Entfernung und Fahrzeit bleiben offen."},
      defense: {title: "Verteidigung", action: "Sichere Zufahrten und schütze Spawn, Bautrupp und Lieferungen ohne angenommene Reichweiten.", evidenceNote: "Die Quelle enthält keine vollständige aktuelle Kosten-, Reichweiten- oder Kapazitätstabelle."},
      recovery: {title: "Bergung", action: "Berge wiederverwendbare Mittel, wenn es sicher ist, melde Verluste und starte nach aktuellem Bedarf neu.", evidenceNote: "Keine offiziellen Bergungszeiten, Erstattungen oder Restwerte werden eingesetzt."},
    },
  },
  ru: {
    progressionRouteTitle: "Маршрут прогресса WARDOGS", progressionRouteDescription: "Выберите одну из шести ролей, укажите текущий уровень и смотрите только официальные изменения сезона 1. Скорость XP и время не выдумываются.", progressionRouteEyebrow: "Планирование по источникам",
    logisticsPlannerTitle: "Планировщик FOB и логистики WARDOGS", logisticsPlannerDescription: "Составьте порядок действий для точки возрождения, строительства, снабжения, транспорта, обороны и восстановления без неподтвержденных цен, вместимости, расстояний и времени.", logisticsPlannerEyebrow: "Последовательность командных задач",
    selectRole: "Ролевая ветка", currentLevel: "Текущий уровень в клиенте", currentLevelOptional: "Необязательно; оставьте пустым, если неизвестно", routeGoal: "Цель", routeDuty: "Граница доказательств", nextUsefulAction: "Следующее полезное действие", durationEstimate: "Оценка времени", unknownDuration: "Неизвестно. Официальный источник сезона 1 не публикует часы, число матчей или XP в час.", confirmedSeasonChanges: "Подтвержденные изменения сезона 1", noPublishedRoleChanges: "В опубликованном списке нет отдельного переноса разблокировки для этой роли. Проверяйте текущий клиент.", previousValue: "Раньше", currentValue: "Сезон 1", officialSource: "Открыть официальный источник сезона 1", checkedOn: "Проверено", availableStages: "Доступные этапы", selectedPlan: "Выбранный порядок операции", emptyLogisticsPlan: "Этапы не выбраны. Добавьте хотя бы один этап для общей ссылки.", includeStage: "Добавить этап", moveEarlier: "Переместить выше", moveLater: "Переместить ниже",
    roles: {
      assault: {label: "Assault", goal: "Планируйте следующий выбор Assault по текущему меню.", duty: "В сезоне 1 ветка названа, но отдельный перенос разблокировки Assault не опубликован.", nextAction: "Откройте Assault, укажите показанный уровень и проверьте следующий предмет до траты средств."},
      medic: {label: "Medic", goal: "Проверьте порядок Medic с учетом подтвержденного изменения магазина PP-19.", duty: "Текущим считается только опубликованный перенос уровня 50-зарядного магазина PP-19.", nextAction: "Сравните уровень Medic с текущим порогом магазина и проверьте следующую разблокировку."},
      recon: {label: "Recon", goal: "Сверьте расходы Recon с подтвержденными ценами прицелов.", duty: "Источник подтверждает две цены, но не полную очередь и не скорость прокачки.", nextAction: "Проверьте оба прицела и следующую разблокировку Recon перед покупкой."},
      support: {label: "Support", goal: "Проверьте Support с учетом подтвержденных изменений молотков.", duty: "Цена и уровень молотков актуальны; остальной порядок проверяется в клиенте.", nextAction: "Проверьте Medium и Large Hammer, затем выберите нужную команде задачу."},
      driver: {label: "Driver", goal: "Проверьте Driver с учетом переносов техники и снабжения сезона 1.", duty: "Актуальны только перечисленные официально изменения техники, ящиков, кассеты и ветки.", nextAction: "Откройте Driver, сравните уровень с изменениями и проверьте следующую доступную машину."},
      pilot: {label: "Pilot", goal: "Проверьте расходы Pilot с учетом изменений авиации и ящика снабжения.", duty: "Подтверждены отдельные цены и перенос одного предмета, но не вся ветка Pilot.", nextAction: "Проверьте ящик снабжения, Little Bird и Z20 в текущей ветке Pilot."},
    },
    logisticsStages: {
      spawn: {title: "Возрождение", action: "Уточните нужное место возрождения и проверьте текущего продавца FOB до расхода ресурсов.", evidenceNote: "Сезон 1 подтверждает изменение цены FOB; правила размещения проверяются в клиенте."},
      construction: {title: "Строительство", action: "Согласуйте объект и место, затем проверьте текущие записи молотка и продавца.", evidenceNote: "Сезон 1 подтверждает цену, стоимость разблокировки Support и уровень Large Hammer."},
      supply: {title: "Снабжение", action: "Уточните ресурс, подтвердите загрузку и передачу, затем проверьте изменение запаса цели.", evidenceNote: "Подтвержден перенос уровня Large Supply Crate; вместимость и значения передачи не подставляются."},
      transport: {title: "Транспорт", action: "Назначьте водителя, маршрут, цель и план возврата до движения машины.", evidenceNote: "Подтверждены отдельные изменения Driver; расстояние и время не указаны."},
      defense: {title: "Оборона", action: "Прикройте подходы и защищайте точку возрождения, строителей и доставки без выдуманной дальности.", evidenceNote: "Источник не публикует полной актуальной таблицы цены, дальности или вместимости обороны."},
      recovery: {title: "Восстановление", action: "Безопасно верните полезные средства, сообщите о потерях и начните цикл с текущей потребности команды.", evidenceNote: "Официальные сроки, возвраты и стоимость спасения не подставляются."},
    },
  },
  "pt-br": {
    progressionRouteTitle: "Rota de progressão de WARDOGS", progressionRouteDescription: "Escolha uma das seis trilhas, informe o nível atual e consulte apenas mudanças oficiais da Temporada 1. Não estimamos XP, partidas ou tempo.", progressionRouteEyebrow: "Planejamento com fontes",
    logisticsPlannerTitle: "Planejador de FOB e logística de WARDOGS", logisticsPlannerDescription: "Ordene uma lista reutilizável de spawn, construção, suprimento, transporte, defesa e recuperação sem inserir custos, capacidades, distâncias ou tempos não confirmados.", logisticsPlannerEyebrow: "Operações em ordem",
    selectRole: "Trilha de função", currentLevel: "Nível atual exibido no cliente", currentLevelOptional: "Opcional; deixe vazio se não souber", routeGoal: "Objetivo", routeDuty: "Limite da evidência", nextUsefulAction: "Próxima ação útil", durationEstimate: "Estimativa de tempo", unknownDuration: "Desconhecida. A fonte oficial da Temporada 1 não publica horas, número de partidas ou XP por hora.", confirmedSeasonChanges: "Mudanças confirmadas da Temporada 1", noPublishedRoleChanges: "O changelog publicado não lista uma mudança específica de desbloqueio para esta trilha. Confira o cliente atual.", previousValue: "Antes", currentValue: "Temporada 1", officialSource: "Abrir fonte oficial da Temporada 1", checkedOn: "Verificado", availableStages: "Etapas disponíveis", selectedPlan: "Ordem selecionada", emptyLogisticsPlan: "Nenhuma etapa selecionada. Adicione ao menos uma para criar uma operação compartilhável.", includeStage: "Incluir etapa", moveEarlier: "Mover para cima", moveLater: "Mover para baixo",
    roles: {
      assault: {label: "Assault", goal: "Planeje a próxima decisão de Assault pelo menu atual.", duty: "A Temporada 1 nomeia a trilha, mas não publica uma mudança específica de desbloqueio de Assault.", nextAction: "Abra Assault, informe o nível exibido e confirme o próximo item antes de gastar."},
      medic: {label: "Medic", goal: "Confira a ordem de Medic perto da mudança confirmada do carregador PP-19.", duty: "Somente a mudança publicada do tambor de 50 tiros é tratada como evidência atual.", nextAction: "Compare o nível de Medic com o requisito atual do carregador e confira o próximo desbloqueio."},
      recon: {label: "Recon", goal: "Revise os gastos de Recon com os preços confirmados das miras.", duty: "A fonte confirma dois preços, não uma ordem completa nem velocidade de progressão.", nextAction: "Confira as duas miras e o próximo desbloqueio de Recon antes de gastar."},
      support: {label: "Support", goal: "Revise Support ao redor das mudanças confirmadas dos martelos.", duty: "Preço e nível dos martelos são atuais; a ordem restante depende do cliente.", nextAction: "Confira Medium e Large Hammer e escolha a tarefa de suporte que a equipe precisa."},
      driver: {label: "Driver", goal: "Revise Driver com as mudanças de veículos e suprimento da Temporada 1.", duty: "Só veículos, caixas, fita e mudanças de trilha listados oficialmente são atuais.", nextAction: "Abra Driver, compare seu nível e confirme o próximo veículo utilizável no cliente."},
      pilot: {label: "Pilot", goal: "Revise Pilot perto das mudanças confirmadas de aeronaves e suprimento.", duty: "A fonte confirma alguns preços e um item removido de Pilot, não a trilha completa.", nextAction: "Confira a caixa, Little Bird e Z20 na trilha Pilot antes de gastar."},
    },
    logisticsStages: {
      spawn: {title: "Spawn", action: "Confirme onde a equipe precisa nascer e confira o vendedor de FOB antes de gastar recursos.", evidenceNote: "A Temporada 1 confirma a mudança do preço do FOB; o posicionamento depende do cliente."},
      construction: {title: "Construção", action: "Combine estrutura e posição primeiro; construa após conferir martelo e vendedor atuais.", evidenceNote: "A Temporada 1 confirma preço, desbloqueio de Support e nível do Large Hammer."},
      supply: {title: "Suprimento", action: "Pergunte o recurso necessário, confirme carga e transferência e confira o estoque no destino.", evidenceNote: "A Temporada 1 confirma uma mudança de nível da Large Supply Crate; capacidade não é inserida."},
      transport: {title: "Transporte", action: "Defina motorista, rota, destino e retorno antes de mover o veículo.", evidenceNote: "A Temporada 1 confirma mudanças selecionadas de Driver; distância e tempo ficam desconhecidos."},
      defense: {title: "Defesa", action: "Cubra acessos e proteja spawn, construtores e entregas sem assumir alcance final.", evidenceNote: "A fonte não publica uma tabela atual completa de custo, alcance ou capacidade defensiva."},
      recovery: {title: "Recuperação", action: "Recupere recursos reutilizáveis quando for seguro, relate perdas e reinicie pela necessidade atual.", evidenceNote: "Não inserimos tempo, reembolso ou valor de salvamento sem fonte oficial."},
    },
  },
  ja: {
    progressionRouteTitle: "WARDOGS 進行ルート", progressionRouteDescription: "6つの役割トラックから選び、現在レベルと公式Season 1変更だけを確認します。XP効率、試合数、所要時間は推測しません。", progressionRouteEyebrow: "出典付き役割計画",
    logisticsPlannerTitle: "WARDOGS FOB・兵站プランナー", logisticsPlannerDescription: "スポーン、建築、補給、輸送、防衛、回収を並べ、未確認の価格、容量、距離、移動時間を入れずに共有できます。", logisticsPlannerEyebrow: "順序付きチーム作戦",
    selectRole: "役割トラック", currentLevel: "ゲーム内の現在レベル", currentLevelOptional: "任意。不明なら空欄", routeGoal: "目標", routeDuty: "証拠の範囲", nextUsefulAction: "次に行うこと", durationEstimate: "所要時間", unknownDuration: "不明です。公式Season 1資料は時間、試合数、1時間当たりXPを公表していません。", confirmedSeasonChanges: "確認済みSeason 1変更", noPublishedRoleChanges: "公開された変更履歴には、このトラック固有の解除移動がありません。現行クライアントで確認してください。", previousValue: "以前", currentValue: "Season 1", officialSource: "公式Season 1資料を開く", checkedOn: "確認日", availableStages: "利用可能な段階", selectedPlan: "選択した作戦順", emptyLogisticsPlan: "段階が選択されていません。共有するには1つ以上追加してください。", includeStage: "段階を追加", moveEarlier: "前へ", moveLater: "後へ",
    roles: {
      assault: {label: "Assault", goal: "現行メニューから次のAssault判断を計画します。", duty: "Season 1はトラック名を示しますが、Assault固有の解除変更は掲載していません。", nextAction: "現行Assaultを開き、表示レベルを入力し、購入前に次の項目を確認します。"},
      medic: {label: "Medic", goal: "PP-19マガジン変更を基準にMedic順序を確認します。", duty: "現在の証拠は公開されたPP-19 50発ドラムのレベル変更だけです。", nextAction: "Medicレベルと現行の条件を比較し、次の解除をクライアントで確認します。"},
      recon: {label: "Recon", goal: "確認済みスコープ価格を基準にRecon支出を確認します。", duty: "2つの価格変更は確認済みですが、全順序や進行速度は未公表です。", nextAction: "両スコープと次のRecon解除を購入前に確認します。"},
      support: {label: "Support", goal: "確認済みハンマー変更を基準にSupportを確認します。", duty: "価格とレベル変更は現行です。他の順序はクライアントで確認します。", nextAction: "MediumとLarge Hammerを確認し、チームが必要とする支援作業を選びます。"},
      driver: {label: "Driver", goal: "Season 1の車両・補給変更を見ながらDriverを確認します。", duty: "公式一覧の車両、箱、テープ、トラック移動だけを現行として扱います。", nextAction: "Driverを開き、レベルと変更を比較して次に使える車両を確認します。"},
      pilot: {label: "Pilot", goal: "確認済み航空機・補給箱変更を基準にPilotを確認します。", duty: "一部価格とPilot外への移動は確認済みですが、全解除順は未公表です。", nextAction: "補給箱、Little Bird、Z20を現行Pilotトラックで確認します。"},
    },
    logisticsStages: {
      spawn: {title: "スポーン", action: "必要なスポーン地点を確認し、資源投入前に現行FOBベンダーを確認します。", evidenceNote: "Season 1はFOB価格変更を確認しますが、配置ルールはクライアントで確認します。"},
      construction: {title: "建築", action: "構造物と位置を合意し、現行ハンマーとベンダーを確認してから建築します。", evidenceNote: "Large Hammerのベンダー価格、Support解除、必要レベル変更が確認済みです。"},
      supply: {title: "補給", action: "必要資源を聞き、積載と移送を確認し、目的地の在庫変化を確認します。", evidenceNote: "Large Supply Crateのレベル変更は確認済みですが、容量は入力しません。"},
      transport: {title: "輸送", action: "車両を動かす前に運転手、経路、目的地、帰還計画を決めます。", evidenceNote: "一部Driver変更は確認済みですが、距離と移動時間は未公表です。"},
      defense: {title: "防衛", action: "最終射程を仮定せず、進入路、スポーン、建築者、配送を守ります。", evidenceNote: "承認済み資料に現行の完全な防衛価格・射程・容量表はありません。"},
      recovery: {title: "回収", action: "安全なら再利用可能な資産を回収し、損失を共有して現在の需要から再開します。", evidenceNote: "公式の回収時間、返金、回収価値は入力しません。"},
    },
  },
  "zh-cn": {
    progressionRouteTitle: "WARDOGS 成长路线工具", progressionRouteDescription: "选择六条角色路线之一，填写客户端当前等级，只查看官方已公布的 Season 1 变更；不编造 XP 效率、比赛场数或所需时间。", progressionRouteEyebrow: "有来源的角色规划",
    logisticsPlannerTitle: "WARDOGS FOB 与后勤规划器", logisticsPlannerDescription: "按出生点、建造、补给、运输、防守和回收编排可分享任务清单，不填入未经确认的价格、容量、距离或行程时间。", logisticsPlannerEyebrow: "有顺序的团队行动",
    selectRole: "角色路线", currentLevel: "客户端显示的当前等级", currentLevelOptional: "选填；未知时留空", routeGoal: "目标", routeDuty: "证据边界", nextUsefulAction: "下一步行动", durationEstimate: "所需时间", unknownDuration: "未知。Season 1 官方来源没有公布所需小时、比赛场数或每小时 XP。", confirmedSeasonChanges: "Season 1 已确认变更", noPublishedRoleChanges: "已发布的 Season 1 更新日志没有列出该路线专属的解锁调整，请以当前客户端为准，不猜测顺序。", previousValue: "原值", currentValue: "Season 1", officialSource: "打开 Season 1 官方来源", checkedOn: "核查日期", availableStages: "可选阶段", selectedPlan: "已选行动顺序", emptyLogisticsPlan: "尚未选择阶段。至少添加一个阶段，才能生成可分享的行动清单。", includeStage: "加入阶段", moveEarlier: "向前移动", moveLater: "向后移动",
    roles: {
      assault: {label: "Assault", goal: "根据当前客户端规划下一项 Assault 路线选择。", duty: "Season 1 官方资料确认存在该路线，但没有公布 Assault 专属解锁调整。", nextAction: "打开当前 Assault 路线，填入显示等级，并在花费前核对下一项物品。"},
      medic: {label: "Medic", goal: "围绕已确认的 PP-19 弹匣调整核对 Medic 解锁顺序。", duty: "只有官方公布的 PP-19 50 发弹鼓等级调整被视为当前证据。", nextAction: "将当前 Medic 等级与客户端弹匣门槛比较，再核对下一项解锁。"},
      recon: {label: "Recon", goal: "根据已确认的瞄具解锁价格规划 Recon 支出。", duty: "官方确认了两项瞄具价格调整，但没有公布完整顺序或升级速度。", nextAction: "花费前在客户端核对两款瞄具和下一项 Recon 解锁。"},
      support: {label: "Support", goal: "围绕已确认的锤子调整核对 Support 路线。", duty: "锤子的解锁价格和等级调整是当前事实，其余顺序仍以客户端为准。", nextAction: "核对 Medium Hammer 和 Large Hammer，再选择团队眼下真正需要的支援任务。"},
      driver: {label: "Driver", goal: "结合 Season 1 载具与补给调整核对 Driver 路线。", duty: "只把官方列出的载具、补给箱、磁带和路线迁移视为当前事实。", nextAction: "打开 Driver 路线，将等级与已确认调整比较，再核对下一辆可用载具。"},
      pilot: {label: "Pilot", goal: "围绕已确认的飞行载具与补给箱价格核对 Pilot 支出。", duty: "官方确认了部分解锁价格及一项移出 Pilot 的物品，并未公布完整路线。", nextAction: "花费前核对补给箱、Little Bird 和 Z20 的当前 Pilot 条目。"},
    },
    logisticsStages: {
      spawn: {title: "出生点", action: "先确认团队需要出生点的位置，再核对当前 FOB 商店条目后投入资源。", evidenceNote: "Season 1 确认了 FOB 商店价格调整；放置规则仍需在当前客户端核对。"},
      construction: {title: "建造", action: "先统一建筑与位置，再在看清当前锤子和商店条目后建造。", evidenceNote: "Season 1 确认了 Large Hammer 商店价格、Support 解锁价格和所需等级调整。"},
      supply: {title: "补给", action: "询问当前所需资源，确认装载与转移，并检查目的地库存确实发生变化。", evidenceNote: "Season 1 确认了 Large Supply Crate 等级调整；不填入未公布的容量和转移数值。"},
      transport: {title: "运输", action: "移动车辆前先确定驾驶员、路线、目的地与返程方案。", evidenceNote: "Season 1 确认了部分 Driver 载具与路线调整；距离和行程时间仍未知。"},
      defense: {title: "防守", action: "覆盖接近路线，保护出生点、建造者和运输，不假设最终防御范围。", evidenceNote: "已批准来源没有公布完整的当前防守价格、范围或容量表。"},
      recovery: {title: "回收", action: "安全时回收可复用资产，报告损失，并从团队当前需求重新开始清单。", evidenceNote: "不填入没有官方来源的回收时间、退款或残值。"},
    },
  },
} as const;

export function getToolCopy(locale: Locale) {
  return {...copy[locale], ...evidenceToolCopy[locale], ...evidenceProvenanceCopy[locale], ...plannerToolCopy[locale]};
}

export type ToolCopy = ReturnType<typeof getToolCopy>;

export function getSourceClassLabel(sourceClass: CatalogueEvidence["sourceClass"], copy: ToolCopy) {
  if (sourceClass === "official") return copy.sourceOfficial;
  if (sourceClass === "live-client") return copy.sourceLiveClient;
  if (sourceClass === "creator-current") return copy.sourceCreatorCurrent;
  if (sourceClass === "creator-historical") return copy.sourceCreatorHistorical;
  return copy.sourceCommunityReport;
}

export function getConfidenceLabel(confidence: CatalogueEvidence["confidence"], copy: ToolCopy) {
  if (confidence === "confirmed") return copy.confidenceConfirmed;
  if (confidence === "observed") return copy.confidenceObserved;
  if (confidence === "corroborated") return copy.confidenceCorroborated;
  return copy.confidenceUnverified;
}
