import type {Locale} from "@/config/site";

const copy = {
  en: {
    systemTitle: "WARDOGS PC Configuration Check",
    systemDescription: "Compare your declared PC with the official Windows minimum and recommended tiers. This does not benchmark your hardware.",
    budgetTitle: "WARDOGS Loadout Budget",
    budgetDescription: "Plan a life using amounts from the build you are playing. No pre-release catalogue price is inserted automatically.",
    officialBasis: "Official requirement basis",
    os: "Operating system",
    ram: "Installed RAM (GB)",
    storage: "Free storage (GB)",
    cpu: "CPU comparison",
    gpu: "GPU comparison",
    windows10: "Windows 10, 64-bit",
    windows11: "Windows 11, 64-bit",
    unsupported: "Older Windows or another OS",
    below: "Below minimum",
    minimum: "Minimum class",
    recommended: "Recommended class",
    unknown: "Not sure",
    result: "Result",
    resultBelow: "Below the advertised minimum",
    resultReview: "Manual comparison needed",
    resultMinimum: "Meets the advertised minimum tier",
    resultRecommended: "Meets the advertised recommended tier",
    limiting: "Review",
    share: "Copy result link",
    copied: "Result link copied",
    cash: "Cash available",
    loadout: "Weapons, ammo and gear",
    vehicle: "Vehicle or team purchase",
    reserve: "Reserve target",
    spent: "Planned spend",
    remaining: "Cash remaining",
    reserveMet: "Reserve protected",
    reserveMissed: "Reserve shortfall",
    buildWarning: "Prices and balance are build-sensitive. Enter the values shown in your current game client.",
    source: "Open official Steam requirements",
  },
  de: {
    systemTitle: "WARDOGS PC-Konfigurationscheck", systemDescription: "Vergleiche deine Angaben mit den offiziellen Windows-Mindest- und empfohlenen Anforderungen. Dies ist kein Benchmark.",
    budgetTitle: "WARDOGS Loadout-Budget", budgetDescription: "Plane ein Leben mit den Preisen deines aktuellen Builds. Vorabpreise werden nicht automatisch eingesetzt.",
    officialBasis: "Offizielle Anforderungsbasis", os: "Betriebssystem", ram: "Installierter RAM (GB)", storage: "Freier Speicher (GB)", cpu: "CPU-Vergleich", gpu: "GPU-Vergleich",
    windows10: "Windows 10, 64-Bit", windows11: "Windows 11, 64-Bit", unsupported: "Älteres Windows oder anderes OS", below: "Unter Minimum", minimum: "Mindestklasse", recommended: "Empfohlene Klasse", unknown: "Unsicher",
    result: "Ergebnis", resultBelow: "Unter dem veröffentlichten Minimum", resultReview: "Manueller Vergleich nötig", resultMinimum: "Erfüllt die veröffentlichte Mindeststufe", resultRecommended: "Erfüllt die empfohlene Stufe", limiting: "Prüfen", share: "Ergebnislink kopieren", copied: "Ergebnislink kopiert",
    cash: "Verfügbares Geld", loadout: "Waffen, Munition und Ausrüstung", vehicle: "Fahrzeug- oder Teamkauf", reserve: "Reserveziel", spent: "Geplante Ausgaben", remaining: "Verbleibendes Geld", reserveMet: "Reserve geschützt", reserveMissed: "Reserve unterschritten", buildWarning: "Preise und Balance hängen vom Build ab. Nutze die Werte aus deinem aktuellen Spielclient.", source: "Offizielle Steam-Anforderungen öffnen",
  },
  ru: {
    systemTitle: "Проверка конфигурации ПК для WARDOGS", systemDescription: "Сравните указанный ПК с официальными минимальными и рекомендуемыми требованиями Windows. Это не тест производительности.",
    budgetTitle: "Бюджет комплекта WARDOGS", budgetDescription: "Планируйте одну жизнь по ценам текущей сборки. Цены из предварительных версий не подставляются.",
    officialBasis: "Официальные требования", os: "Операционная система", ram: "ОЗУ (ГБ)", storage: "Свободное место (ГБ)", cpu: "Сравнение CPU", gpu: "Сравнение GPU",
    windows10: "Windows 10, 64-разрядная", windows11: "Windows 11, 64-разрядная", unsupported: "Старая Windows или другая ОС", below: "Ниже минимума", minimum: "Минимальный класс", recommended: "Рекомендуемый класс", unknown: "Не уверен",
    result: "Результат", resultBelow: "Ниже заявленного минимума", resultReview: "Нужно ручное сравнение", resultMinimum: "Соответствует заявленному минимуму", resultRecommended: "Соответствует рекомендуемому уровню", limiting: "Проверить", share: "Копировать ссылку", copied: "Ссылка скопирована",
    cash: "Доступные средства", loadout: "Оружие, боеприпасы и снаряжение", vehicle: "Транспорт или командная покупка", reserve: "Целевой резерв", spent: "Планируемые расходы", remaining: "Остаток", reserveMet: "Резерв сохранён", reserveMissed: "Резерва не хватает", buildWarning: "Цены и баланс зависят от сборки. Введите значения из текущего клиента игры.", source: "Открыть требования в Steam",
  },
  "pt-br": {
    systemTitle: "Verificador de configuração de WARDOGS", systemDescription: "Compare o PC informado com os requisitos oficiais mínimo e recomendado para Windows. Isto não é um benchmark.",
    budgetTitle: "Orçamento de equipamento de WARDOGS", budgetDescription: "Planeje uma vida com os valores da build atual. Nenhum preço de pré-lançamento é preenchido automaticamente.",
    officialBasis: "Base oficial de requisitos", os: "Sistema operacional", ram: "RAM instalada (GB)", storage: "Armazenamento livre (GB)", cpu: "Comparação de CPU", gpu: "Comparação de GPU",
    windows10: "Windows 10, 64 bits", windows11: "Windows 11, 64 bits", unsupported: "Windows antigo ou outro sistema", below: "Abaixo do mínimo", minimum: "Classe mínima", recommended: "Classe recomendada", unknown: "Não tenho certeza",
    result: "Resultado", resultBelow: "Abaixo do mínimo divulgado", resultReview: "Comparação manual necessária", resultMinimum: "Atende ao nível mínimo divulgado", resultRecommended: "Atende ao nível recomendado", limiting: "Revisar", share: "Copiar link do resultado", copied: "Link do resultado copiado",
    cash: "Dinheiro disponível", loadout: "Armas, munição e equipamento", vehicle: "Veículo ou compra da equipe", reserve: "Reserva desejada", spent: "Gasto planejado", remaining: "Dinheiro restante", reserveMet: "Reserva protegida", reserveMissed: "Reserva insuficiente", buildWarning: "Preços e balanceamento dependem da build. Informe os valores mostrados no cliente atual.", source: "Abrir requisitos oficiais na Steam",
  },
  ja: {
    systemTitle: "WARDOGS PC構成チェック", systemDescription: "入力したPCを公式のWindows最低・推奨要件と比較します。ベンチマークではありません。",
    budgetTitle: "WARDOGS ロードアウト予算", budgetDescription: "現在プレイ中のビルドに表示された金額で1ライフを計画します。旧ビルド価格は自動入力しません。",
    officialBasis: "公式要件に基づく比較", os: "OS", ram: "搭載RAM (GB)", storage: "空き容量 (GB)", cpu: "CPU比較", gpu: "GPU比較",
    windows10: "Windows 10 64-bit", windows11: "Windows 11 64-bit", unsupported: "古いWindowsまたは別OS", below: "最低未満", minimum: "最低クラス", recommended: "推奨クラス", unknown: "不明",
    result: "結果", resultBelow: "公表された最低要件未満", resultReview: "手動確認が必要", resultMinimum: "公表された最低要件を満たす", resultRecommended: "公表された推奨要件を満たす", limiting: "確認項目", share: "結果リンクをコピー", copied: "結果リンクをコピーしました",
    cash: "利用可能な資金", loadout: "武器・弾薬・装備", vehicle: "車両またはチーム購入", reserve: "残す資金", spent: "支出予定", remaining: "残金", reserveMet: "予備資金を確保", reserveMissed: "予備資金不足", buildWarning: "価格とバランスはビルドで変わります。現在のゲーム内表示額を入力してください。", source: "Steamの公式要件を見る",
  },
  "zh-cn": {
    systemTitle: "WARDOGS 电脑配置检测", systemDescription: "把你填写的电脑配置与 Steam 官方 Windows 最低、推荐配置比较。本工具不运行性能测试。",
    budgetTitle: "WARDOGS 配装预算工具", budgetDescription: "使用当前游戏版本里显示的价格规划一次生命，不自动套用测试版本旧价格。",
    officialBasis: "官方配置依据", os: "操作系统", ram: "内存容量 (GB)", storage: "可用硬盘空间 (GB)", cpu: "CPU 对比", gpu: "显卡对比",
    windows10: "Windows 10 64 位", windows11: "Windows 11 64 位", unsupported: "旧版 Windows 或其他系统", below: "低于最低配置", minimum: "最低配置级别", recommended: "推荐配置级别", unknown: "不确定",
    result: "检测结果", resultBelow: "低于官方公布的最低配置", resultReview: "需要手动核对", resultMinimum: "达到官方公布的最低配置", resultRecommended: "达到官方公布的推荐配置", limiting: "需要复核", share: "复制结果链接", copied: "结果链接已复制",
    cash: "可用资金", loadout: "武器、弹药和装备", vehicle: "载具或团队支出", reserve: "计划保留资金", spent: "计划支出", remaining: "剩余资金", reserveMet: "已保留预算", reserveMissed: "未达到保留目标", buildWarning: "价格和平衡会随版本变化，请输入你当前游戏客户端中显示的数值。", source: "查看 Steam 官方配置",
  },
} as const;

const evidenceToolCopy = {
  en: {
    weaponCompareTitle: "WARDOGS Weapon Compare",
    weaponCompareDescription: "Compare only documented weapon fields. Every value keeps its source build and current, historical, or unknown evidence state.",
    weaponCompareEyebrow: "Evidence-first loadout tool",
    ammoMatcherTitle: "WARDOGS Ammo Matcher",
    ammoMatcherDescription: "Look up weapon-to-ammunition and ammunition-to-weapon relationships only when the catalogue records an explicit match.",
    ammoMatcherEyebrow: "Explicit catalogue relationships",
    leftWeapon: "First weapon",
    rightWeapon: "Second weapon",
    selectWeapon: "Select a weapon",
    selectAmmo: "Select ammunition",
    comparison: "Documented field comparison",
    weaponToAmmo: "Ammunition recorded for this weapon",
    ammoToWeapons: "Weapons recorded for this ammunition",
    currentEvidence: "Current",
    historicalEvidence: "Historical",
    unknownEvidence: "Unknown",
    historicalWarning: "Historical observations are not current-build recommendations.",
    build: "Build",
    verified: "Verified",
    fieldRole: "Role",
    fieldPrice: "Observed cost",
    fieldAmmunition: "Ammunition",
    fieldFireModes: "Fire modes",
    fieldWeight: "Weight",
    fieldProgression: "Progression gate",
    fieldRequiredLevel: "Required level",
    strengths: "Documented context",
    cautions: "Evidence cautions",
    openItem: "Open evidence page",
    noConfirmedAmmo: "No confirmed ammunition relationship is recorded for this weapon.",
    noConfirmedWeapons: "No confirmed weapon relationship is recorded for this ammunition.",
    emptyMatcher: "Choose a weapon, ammunition type, or both to inspect the recorded relationships.",
    copyToolLink: "Copy tool link",
    copiedToolLink: "Tool link copied",
  },
  de: {
    weaponCompareTitle: "WARDOGS Waffenvergleich",
    weaponCompareDescription: "Vergleiche nur dokumentierte Waffenfelder. Jeder Wert behält Build sowie aktuellen, historischen oder unbekannten Belegstatus.",
    weaponCompareEyebrow: "Beleggestütztes Loadout-Werkzeug",
    ammoMatcherTitle: "WARDOGS Munitionszuordnung",
    ammoMatcherDescription: "Zeigt Waffen-Munitions-Beziehungen nur dann, wenn der Katalog eine ausdrückliche Zuordnung enthält.",
    ammoMatcherEyebrow: "Explizite Katalogbeziehungen",
    leftWeapon: "Erste Waffe", rightWeapon: "Zweite Waffe", selectWeapon: "Waffe auswählen", selectAmmo: "Munition auswählen", comparison: "Dokumentierter Feldvergleich",
    weaponToAmmo: "Für diese Waffe erfasste Munition", ammoToWeapons: "Für diese Munition erfasste Waffen", currentEvidence: "Aktuell", historicalEvidence: "Historisch", unknownEvidence: "Unbekannt",
    historicalWarning: "Historische Beobachtungen sind keine Empfehlungen für den aktuellen Build.", build: "Build", verified: "Geprüft", fieldRole: "Rolle", fieldPrice: "Beobachtete Kosten", fieldAmmunition: "Munition", fieldFireModes: "Feuermodi", fieldWeight: "Gewicht", fieldProgression: "Fortschrittsbedingung", fieldRequiredLevel: "Benötigte Stufe",
    strengths: "Dokumentierter Kontext", cautions: "Beleggrenzen", openItem: "Belegseite öffnen", noConfirmedAmmo: "Für diese Waffe ist keine bestätigte Munitionsbeziehung erfasst.", noConfirmedWeapons: "Für diese Munition ist keine bestätigte Waffenbeziehung erfasst.", emptyMatcher: "Wähle eine Waffe, Munition oder beides, um erfasste Beziehungen zu prüfen.", copyToolLink: "Werkzeuglink kopieren", copiedToolLink: "Werkzeuglink kopiert",
  },
  ru: {
    weaponCompareTitle: "Сравнение оружия WARDOGS",
    weaponCompareDescription: "Сравнивайте только документированные поля. Для каждого значения сохраняются сборка и статус: актуальное, историческое или неизвестное.",
    weaponCompareEyebrow: "Инструмент на основе источников",
    ammoMatcherTitle: "Подбор боеприпасов WARDOGS",
    ammoMatcherDescription: "Связи оружия и боеприпасов показываются только при наличии прямой записи в каталоге.",
    ammoMatcherEyebrow: "Явные связи каталога",
    leftWeapon: "Первое оружие", rightWeapon: "Второе оружие", selectWeapon: "Выберите оружие", selectAmmo: "Выберите боеприпас", comparison: "Сравнение документированных полей",
    weaponToAmmo: "Боеприпасы, записанные для этого оружия", ammoToWeapons: "Оружие, записанное для этого боеприпаса", currentEvidence: "Актуально", historicalEvidence: "Исторические данные", unknownEvidence: "Неизвестно",
    historicalWarning: "Исторические наблюдения не являются рекомендацией для текущей сборки.", build: "Сборка", verified: "Проверено", fieldRole: "Роль", fieldPrice: "Наблюдавшаяся цена", fieldAmmunition: "Боеприпасы", fieldFireModes: "Режимы огня", fieldWeight: "Вес", fieldProgression: "Условие прогресса", fieldRequiredLevel: "Требуемый уровень",
    strengths: "Документированный контекст", cautions: "Ограничения данных", openItem: "Открыть страницу источников", noConfirmedAmmo: "Для этого оружия не записана подтверждённая связь с боеприпасом.", noConfirmedWeapons: "Для этого боеприпаса не записана подтверждённая связь с оружием.", emptyMatcher: "Выберите оружие, боеприпас или оба варианта для проверки записанных связей.", copyToolLink: "Копировать ссылку", copiedToolLink: "Ссылка скопирована",
  },
  "pt-br": {
    weaponCompareTitle: "Comparador de armas de WARDOGS",
    weaponCompareDescription: "Compare apenas campos documentados. Cada valor mantém a build de origem e o estado atual, histórico ou desconhecido.",
    weaponCompareEyebrow: "Ferramenta baseada em evidências",
    ammoMatcherTitle: "Correspondência de munição de WARDOGS",
    ammoMatcherDescription: "Consulte relações entre armas e munições somente quando houver uma correspondência explícita no catálogo.",
    ammoMatcherEyebrow: "Relações explícitas do catálogo",
    leftWeapon: "Primeira arma", rightWeapon: "Segunda arma", selectWeapon: "Selecione uma arma", selectAmmo: "Selecione a munição", comparison: "Comparação de campos documentados",
    weaponToAmmo: "Munição registrada para esta arma", ammoToWeapons: "Armas registradas para esta munição", currentEvidence: "Atual", historicalEvidence: "Histórico", unknownEvidence: "Desconhecido",
    historicalWarning: "Observações históricas não são recomendações para a build atual.", build: "Build", verified: "Verificado", fieldRole: "Função", fieldPrice: "Custo observado", fieldAmmunition: "Munição", fieldFireModes: "Modos de disparo", fieldWeight: "Peso", fieldProgression: "Requisito de progressão", fieldRequiredLevel: "Nível necessário",
    strengths: "Contexto documentado", cautions: "Limites da evidência", openItem: "Abrir página de evidências", noConfirmedAmmo: "Nenhuma relação confirmada de munição foi registrada para esta arma.", noConfirmedWeapons: "Nenhuma relação confirmada de arma foi registrada para esta munição.", emptyMatcher: "Escolha uma arma, munição ou ambas para consultar as relações registradas.", copyToolLink: "Copiar link da ferramenta", copiedToolLink: "Link da ferramenta copiado",
  },
  ja: {
    weaponCompareTitle: "WARDOGS 武器比較",
    weaponCompareDescription: "記録済みの項目だけを比較します。各値には、出典ビルドと現行・履歴・不明の証拠状態を表示します。",
    weaponCompareEyebrow: "証拠優先のロードアウトツール",
    ammoMatcherTitle: "WARDOGS 弾薬対応表",
    ammoMatcherDescription: "カタログに明示された関係だけを使って、武器から弾薬、弾薬から武器を検索します。",
    ammoMatcherEyebrow: "カタログの明示的な対応関係",
    leftWeapon: "1つ目の武器", rightWeapon: "2つ目の武器", selectWeapon: "武器を選択", selectAmmo: "弾薬を選択", comparison: "記録済み項目の比較",
    weaponToAmmo: "この武器に記録された弾薬", ammoToWeapons: "この弾薬に記録された武器", currentEvidence: "現行", historicalEvidence: "履歴", unknownEvidence: "不明",
    historicalWarning: "過去ビルドの観察値は、現行ビルドの推奨値ではありません。", build: "ビルド", verified: "確認日", fieldRole: "役割", fieldPrice: "確認済み価格", fieldAmmunition: "弾薬", fieldFireModes: "射撃モード", fieldWeight: "重量", fieldProgression: "進行条件", fieldRequiredLevel: "必要レベル",
    strengths: "記録済みの文脈", cautions: "証拠上の注意", openItem: "証拠ページを開く", noConfirmedAmmo: "この武器には確認済みの弾薬対応が記録されていません。", noConfirmedWeapons: "この弾薬には確認済みの武器対応が記録されていません。", emptyMatcher: "武器、弾薬、または両方を選択して記録済みの関係を確認してください。", copyToolLink: "ツールリンクをコピー", copiedToolLink: "ツールリンクをコピーしました",
  },
  "zh-cn": {
    weaponCompareTitle: "WARDOGS 武器对比工具",
    weaponCompareDescription: "只对比已经记录的武器字段。每个值都保留来源版本，并明确标注当前、历史或未知状态。",
    weaponCompareEyebrow: "证据优先的配装工具",
    ammoMatcherTitle: "WARDOGS 武器弹药匹配器",
    ammoMatcherDescription: "仅在图鉴存在明确关系时，查询武器对应弹药或弹药对应武器，不根据名称猜测兼容性。",
    ammoMatcherEyebrow: "图鉴中的明确对应关系",
    leftWeapon: "第一把武器", rightWeapon: "第二把武器", selectWeapon: "选择武器", selectAmmo: "选择弹药", comparison: "已记录字段对比",
    weaponToAmmo: "该武器已记录的弹药", ammoToWeapons: "该弹药已记录的武器", currentEvidence: "当前", historicalEvidence: "历史", unknownEvidence: "未知",
    historicalWarning: "历史版本观察值不是当前版本推荐。", build: "版本", verified: "核查日期", fieldRole: "定位", fieldPrice: "已观察价格", fieldAmmunition: "弹药", fieldFireModes: "射击模式", fieldWeight: "重量", fieldProgression: "进度门槛", fieldRequiredLevel: "所需等级",
    strengths: "已记录使用背景", cautions: "证据限制", openItem: "打开证据页面", noConfirmedAmmo: "图鉴尚未记录该武器的明确弹药关系。", noConfirmedWeapons: "图鉴尚未记录该弹药的明确武器关系。", emptyMatcher: "选择武器、弹药或同时选择两者，查看已记录的对应关系。", copyToolLink: "复制工具链接", copiedToolLink: "工具链接已复制",
  },
} as const;

export function getToolCopy(locale: Locale) {
  return {...copy[locale], ...evidenceToolCopy[locale]};
}

export type ToolCopy = ReturnType<typeof getToolCopy>;
