import {resolveToolLocale} from "./tool-copy";

const en = {
  shareTooLarge: "This plan is too long to share. Shorten names or remove items; the address bar still contains the previous plan.",
  totalMode: "Quick total", itemsMode: "Item list", once: "One-time costs ($)", repeat: "Per-purchase costs ($)", purchases: "Total purchases", replacements: "Replacements after first purchase", zeroCost: "No finite limit at zero recurring cost", assumptions: "User scenario. No income or refunds. Vehicle costs recur on each purchase; put one-time costs separately.",
  search: "Search catalogue", add: "Add item", quantity: "Quantity", unit: "Purchase unit (user-defined)", item: "Item", pack: "Pack", round: "Round", unknown: "Unknown", price: "Unit price ($, user-defined)", frequency: "Frequency", repeatShort: "Each purchase", onceShort: "Once", remove: "Remove", empty: "No items selected", incomplete: "Incomplete total: unknown price, unit or item. Purchase counts are unavailable.", subtotal: "Known subtotal", reference: "Catalogue reference, not applied", compatibility: "Recorded ammunition compatibility", compatibilityUnknown: "Unknown. No explicit relationship is recorded; calibre alone does not confirm fit.", attachmentUnknown: "Attachment and magazine fit, capacity and pack contents are not verified. These selections are not an approved loadout.", addBudget: "Plan in budget", select: "Select an item", differences: "Only differences", allTypes: "All types", noResults: "No matching items", noDifferences: "No differing fields", evidence: "Evidence", manifest: "Construction supplies", name: "Buildable / task (user-defined)", supplies: "Supply units per piece (user-defined)", demand: "Additional demand (user-defined)", stock: "Available stock", capacity: "Effective load per trip (user-defined)", resource: "Resource unit / type", trips: "Trips needed", required: "Total supply demand", outstanding: "Remaining demand", supplyNote: "All quantities use the same resource unit. Money is not supply. Unknown costs or load capacity do not produce a trip estimate.", addLine: "Add build stage", stage: "Stage", legacy: "Legacy link: no data version. Current reference data is shown; your entered amounts are unchanged.", changed: "Data version changed. Saved user quantities and prices are preserved; catalogue references and compatibility use current evidence.", unsupported: "Unsupported share version. Do not treat the displayed defaults as the shared plan.", invalid: "The shared plan is invalid or too large. Defaults are shown, not the original plan.", shareFailed: "Copy failed. The share link is in the address bar.", limit: "Maximum 50 items", deleted: "Catalogue item no longer available", snapshot: "Data version", custom: "User-defined", perStage: "Stage subtotal", firstSpend: "First purchase", legacyVehicle: "Vehicle cost per purchase ($)", selectWeapon: "Weapon for compatibility check",
};
type Copy = Record<keyof typeof en, string>;

const translations: Record<ReturnType<typeof resolveToolLocale>, Copy> = {
  en,
  "zh-cn": {
    shareTooLarge: "方案过长，无法分享。请缩短名称或减少项目；地址栏仍是之前的方案。",
    totalMode: "快速总额", itemsMode: "逐件清单", once: "一次性费用 ($)", repeat: "每次购买费用 ($)", purchases: "总购买次数", replacements: "首次后可补购次数", zeroCost: "每次费用为零，不设有限次数", assumptions: "用户自定义情景，不计收入或返还。载具费用每次重复计入；一次性支出单独填写。",
    search: "搜索目录", add: "添加物品", quantity: "数量", unit: "采购单位（用户定义）", item: "件", pack: "包", round: "发", unknown: "未知", price: "采购单位价格（自定义，$）", frequency: "购买频率", repeatShort: "每次购买", onceShort: "仅一次", remove: "移除", empty: "尚未选择物品", incomplete: "合计不完整：存在未知价格、单位或物品，暂不计算购买次数。", subtotal: "已知部分合计", reference: "目录参考，未自动采用", compatibility: "已记录的弹药兼容关系", compatibilityUnknown: "未知。没有明确关系证据，不能仅凭相同口径认定兼容。", attachmentUnknown: "配件及弹匣适配、容量与弹药包内容尚未核验，所选清单不代表已确认可用的配装。", addBudget: "加入预算规划", select: "选择物品", differences: "只看差异", allTypes: "全部类型", noResults: "无匹配物品", noDifferences: "没有不同字段", evidence: "证据", manifest: "建设物资清单", name: "建筑或任务（用户自定义）", supplies: "每件物资需求（自定义）", demand: "额外需求（自定义）", stock: "现有库存", capacity: "每趟有效载量（自定义）", resource: "资源单位或种类", trips: "所需趟数", required: "物资总需求", outstanding: "剩余需求", supplyNote: "所有数量使用相同资源单位。金钱不等于物资；费用或载量未知时不生成趟数估计。", addLine: "添加建设阶段", stage: "阶段", legacy: "旧链接未记录数据版本。显示当前参考资料，用户填写的金额保持不变。", changed: "数据版本已变化。保留链接中的自定义数量和价格；目录参考与兼容关系显示当前证据。", unsupported: "分享版本不受支持。显示的默认值不是原分享方案。", invalid: "分享方案无效或过大。当前显示默认值，不是原方案。", shareFailed: "复制失败，分享链接已写入地址栏。", limit: "最多 50 项", deleted: "目录物品已不存在", snapshot: "数据版本", custom: "用户自定义", perStage: "阶段小计", firstSpend: "首次购买支出", legacyVehicle: "每次载具支出 ($)", selectWeapon: "选择武器核对兼容关系",
  },
  de: {
    shareTooLarge: "Dieser Plan ist zu lang zum Teilen. Namen kürzen oder Einträge entfernen; die Adressleiste enthält noch den vorherigen Plan.",
    totalMode: "Gesamtsumme", itemsMode: "Stückliste", once: "Einmalige Kosten ($)", repeat: "Kosten je Kauf ($)", purchases: "Käufe insgesamt", replacements: "Ersatzkäufe nach dem Erstkauf", zeroCost: "Keine endliche Grenze bei laufenden Kosten von null", assumptions: "Eigenes Szenario ohne Einnahmen oder Erstattungen. Fahrzeugkosten gelten je Kauf; einmalige Kosten separat eintragen.",
    search: "Katalog durchsuchen", add: "Gegenstand hinzufügen", quantity: "Anzahl", unit: "Kaufeinheit (eigene Angabe)", item: "Stück", pack: "Packung", round: "Schuss", unknown: "Unbekannt", price: "Preis je Einheit ($, eigene Angabe)", frequency: "Häufigkeit", repeatShort: "Je Kauf", onceShort: "Einmalig", remove: "Entfernen", empty: "Keine Gegenstände ausgewählt", incomplete: "Unvollständig: Preis, Einheit oder Gegenstand unbekannt. Keine Kaufanzahl berechenbar.", subtotal: "Bekannte Zwischensumme", reference: "Katalogreferenz, nicht übernommen", compatibility: "Belegte Munitionszuordnung", compatibilityUnknown: "Unbekannt. Keine ausdrückliche Zuordnung; gleiches Kaliber belegt keine Kompatibilität.", attachmentUnknown: "Zubehör, Magazine, Kapazitäten und Packungsinhalt sind nicht geprüft. Diese Auswahl ist kein bestätigtes Loadout.", addBudget: "Im Budget planen", select: "Gegenstand auswählen", differences: "Nur Unterschiede", allTypes: "Alle Typen", noResults: "Keine Treffer", noDifferences: "Keine unterschiedlichen Felder", evidence: "Belege", manifest: "Baumaterialliste", name: "Bauwerk / Aufgabe (eigene Angabe)", supplies: "Material je Stück (eigene Angabe)", demand: "Zusatzbedarf (eigene Angabe)", stock: "Bestand", capacity: "Nutzlast je Fahrt (eigene Angabe)", resource: "Ressourceneinheit / Typ", trips: "Benötigte Fahrten", required: "Gesamtbedarf", outstanding: "Restbedarf", supplyNote: "Alle Mengen nutzen dieselbe Ressourceneinheit. Geld ist kein Material. Bei unbekannten Kosten oder Kapazitäten keine Fahrtenberechnung.", addLine: "Bauphase hinzufügen", stage: "Phase", legacy: "Alter Link ohne Datenversion. Aktuelle Referenzdaten; eingegebene Beträge bleiben unverändert.", changed: "Datenversion geändert. Gespeicherte eigene Mengen und Preise bleiben erhalten; Referenzen und Zuordnungen nutzen aktuelle Belege.", unsupported: "Nicht unterstützte Linkversion. Standardwerte sind nicht der geteilte Plan.", invalid: "Ungültiger oder zu großer Plan. Standardwerte statt Originalplan.", shareFailed: "Kopieren fehlgeschlagen. Der Link steht in der Adressleiste.", limit: "Höchstens 50 Einträge", deleted: "Katalogeintrag nicht mehr verfügbar", snapshot: "Datenversion", custom: "Eigene Angabe", perStage: "Phasensumme", firstSpend: "Erstkauf", legacyVehicle: "Fahrzeugkosten je Kauf ($)", selectWeapon: "Waffe für die Zuordnung",
  },
  ru: {
    shareTooLarge: "План слишком длинный для ссылки. Сократите названия или удалите строки; в адресной строке остаётся предыдущий план.",
    totalMode: "Общая сумма", itemsMode: "Список предметов", once: "Разовые расходы ($)", repeat: "Расходы на покупку ($)", purchases: "Всего покупок", replacements: "Повторных покупок после первой", zeroCost: "Нет конечного лимита при нулевой повторной стоимости", assumptions: "Пользовательский сценарий без доходов и возвратов. Транспорт оплачивается при каждой покупке; разовые расходы указываются отдельно.",
    search: "Поиск по каталогу", add: "Добавить предмет", quantity: "Количество", unit: "Единица покупки (своя)", item: "Штука", pack: "Упаковка", round: "Патрон", unknown: "Неизвестно", price: "Цена единицы ($, своя)", frequency: "Частота", repeatShort: "Каждая покупка", onceShort: "Один раз", remove: "Удалить", empty: "Предметы не выбраны", incomplete: "Неполная сумма: неизвестны цена, единица или предмет. Число покупок не рассчитано.", subtotal: "Известная сумма", reference: "Справочная цена, не применена", compatibility: "Записанная совместимость боеприпасов", compatibilityUnknown: "Неизвестно. Нет явной связи; совпадение калибра не подтверждает совместимость.", attachmentUnknown: "Совместимость модулей и магазинов, вместимость и содержимое упаковок не проверены. Это не подтверждённый комплект.", addBudget: "Планировать бюджет", select: "Выберите предмет", differences: "Только различия", allTypes: "Все типы", noResults: "Ничего не найдено", noDifferences: "Различий нет", evidence: "Источники", manifest: "Строительные припасы", name: "Постройка / задача (своя)", supplies: "Припасы на штуку (свои)", demand: "Дополнительный спрос (свой)", stock: "В наличии", capacity: "Полезный груз за рейс (свой)", resource: "Единица / тип ресурса", trips: "Нужно рейсов", required: "Общая потребность", outstanding: "Осталось доставить", supplyNote: "Единицы ресурса должны совпадать. Деньги не равны припасам. Неизвестные затраты или вместимость не дают оценки рейсов.", addLine: "Добавить этап", stage: "Этап", legacy: "Старый URL без версии данных. Справочные данные текущие, ваши суммы не изменены.", changed: "Версия данных изменилась. Сохранены пользовательские количества и цены; справка и совместимость используют текущие источники.", unsupported: "Версия ссылки не поддерживается. Значения по умолчанию не являются исходным планом.", invalid: "План некорректен или слишком велик. Показаны значения по умолчанию.", shareFailed: "Копирование не удалось. Ссылка находится в адресной строке.", limit: "Не более 50 строк", deleted: "Предмет больше недоступен", snapshot: "Версия данных", custom: "Свои данные", perStage: "Итого по этапу", firstSpend: "Первая покупка", legacyVehicle: "Транспорт при каждой покупке ($)", selectWeapon: "Оружие для проверки совместимости",
  },
  "pt-br": {
    shareTooLarge: "Plano longo demais para compartilhar. Encurte nomes ou remova itens; a barra de endereço ainda contém o plano anterior.",
    totalMode: "Total rápido", itemsMode: "Lista de itens", once: "Custos únicos ($)", repeat: "Custos por compra ($)", purchases: "Compras totais", replacements: "Reposições após a primeira compra", zeroCost: "Sem limite finito quando o custo recorrente é zero", assumptions: "Cenário próprio, sem renda ou reembolsos. Veículos entram em cada compra; informe custos únicos separadamente.",
    search: "Buscar no catálogo", add: "Adicionar item", quantity: "Quantidade", unit: "Unidade de compra (própria)", item: "Item", pack: "Pacote", round: "Projétil", unknown: "Desconhecido", price: "Preço unitário ($, próprio)", frequency: "Frequência", repeatShort: "Cada compra", onceShort: "Uma vez", remove: "Remover", empty: "Nenhum item selecionado", incomplete: "Total incompleto: preço, unidade ou item desconhecido. Número de compras indisponível.", subtotal: "Subtotal conhecido", reference: "Referência do catálogo, não aplicada", compatibility: "Compatibilidade de munição registrada", compatibilityUnknown: "Desconhecida. Sem relação explícita; o mesmo calibre não comprova compatibilidade.", attachmentUnknown: "Compatibilidade de acessórios e carregadores, capacidade e conteúdo dos pacotes não verificados. Esta não é uma configuração confirmada.", addBudget: "Planejar orçamento", select: "Selecionar item", differences: "Só diferenças", allTypes: "Todos os tipos", noResults: "Nenhum resultado", noDifferences: "Nenhum campo diferente", evidence: "Evidências", manifest: "Suprimentos de construção", name: "Construção / tarefa (própria)", supplies: "Suprimentos por peça (próprios)", demand: "Demanda adicional (própria)", stock: "Estoque disponível", capacity: "Carga útil por viagem (própria)", resource: "Unidade / tipo de recurso", trips: "Viagens necessárias", required: "Demanda total", outstanding: "Demanda restante", supplyNote: "Use a mesma unidade de recurso em todas as quantidades. Dinheiro não é suprimento. Custos ou capacidade desconhecidos não geram estimativa.", addLine: "Adicionar etapa", stage: "Etapa", legacy: "Link antigo sem versão dos dados. Referências atuais; valores informados não mudaram.", changed: "Versão dos dados alterada. Quantidades e preços próprios foram preservados; referências e compatibilidade usam evidências atuais.", unsupported: "Versão de link não suportada. Os valores padrão não representam o plano original.", invalid: "Plano inválido ou grande demais. Valores padrão exibidos.", shareFailed: "Falha ao copiar. O link está na barra de endereço.", limit: "Máximo de 50 itens", deleted: "Item não disponível no catálogo", snapshot: "Versão dos dados", custom: "Próprio", perStage: "Subtotal da etapa", firstSpend: "Primeira compra", legacyVehicle: "Veículo por compra ($)", selectWeapon: "Arma para verificar compatibilidade",
  },
  ja: {
    shareTooLarge: "計画が長すぎて共有できません。名前を短くするか品目を減らしてください。アドレスバーには前の計画が残っています。",
    totalMode: "合計入力", itemsMode: "品目リスト", once: "一度だけの費用 ($)", repeat: "購入ごとの費用 ($)", purchases: "購入可能回数", replacements: "初回後の再購入回数", zeroCost: "繰返し費用がゼロのため有限回数なし", assumptions: "収入・返金を含まないユーザー設定です。車両費は購入ごとに計上し、一度だけの費用は別に入力します。",
    search: "カタログ検索", add: "品目を追加", quantity: "数量", unit: "購入単位（ユーザー設定）", item: "個", pack: "パック", round: "発", unknown: "不明", price: "単価 ($、ユーザー設定)", frequency: "頻度", repeatShort: "購入ごと", onceShort: "一度だけ", remove: "削除", empty: "品目未選択", incomplete: "価格・単位・品目に不明な項目があり、合計と購入回数を確定できません。", subtotal: "既知分の小計", reference: "カタログ参考値・未適用", compatibility: "記録済みの弾薬適合関係", compatibilityUnknown: "不明。明示的な関係がなく、同口径だけでは適合を確認できません。", attachmentUnknown: "アタッチメント・弾倉の適合、容量、パック内容は未確認です。選択済みでも確認済み装備とは限りません。", addBudget: "予算に追加", select: "品目を選択", differences: "相違点のみ", allTypes: "全種類", noResults: "該当なし", noDifferences: "異なる項目なし", evidence: "根拠", manifest: "建築物資リスト", name: "建築物・作業（ユーザー設定）", supplies: "1個あたり物資（ユーザー設定）", demand: "追加需要（ユーザー設定）", stock: "現在の在庫", capacity: "1往復の実積載量（ユーザー設定）", resource: "資源の単位・種類", trips: "必要輸送回数", required: "物資総需要", outstanding: "残りの需要", supplyNote: "全数量を同じ資源単位で入力します。資金と物資は別です。費用や積載量が不明なら輸送回数は計算しません。", addLine: "建築段階を追加", stage: "段階", legacy: "旧リンクにデータ版はありません。参考資料は現行、入力額は保持しています。", changed: "データ版が変わりました。保存済み数量・価格は保持し、参考値と適合関係は現在の根拠を使用します。", unsupported: "未対応の共有版です。表示された既定値は共有元の計画ではありません。", invalid: "共有計画が無効か大きすぎます。既定値を表示しています。", shareFailed: "コピー失敗。リンクはアドレスバーにあります。", limit: "最大50品目", deleted: "カタログにない品目", snapshot: "データ版", custom: "ユーザー設定", perStage: "段階の小計", firstSpend: "初回購入", legacyVehicle: "毎回の車両費 ($)", selectWeapon: "適合確認する武器",
  },

  pl: {shareTooLarge:"Plan jest zbyt długi do udostępnienia. Skróć nazwy lub usuń pozycje; pasek adresu nadal zawiera poprzedni plan.", totalMode:"Szybka suma", itemsMode:"Lista przedmiotów", once:"Koszty jednorazowe ($)", repeat:"Koszt każdego zakupu ($)", purchases:"Łączna liczba zakupów", replacements:"Odtworzenia po pierwszym zakupie", zeroCost:"Przy zerowym koszcie powtarzalnym brak skończonego limitu", assumptions:"Scenariusz użytkownika, bez dochodów i zwrotów. Koszt pojazdu powtarza się przy każdym zakupie; koszty jednorazowe wpisz osobno.", search:"Szukaj w katalogu", add:"Dodaj przedmiot", quantity:"Liczba", unit:"Jednostka zakupu (własna)", item:"Sztuka", pack:"Paczka", round:"Nabój", unknown:"Nieznane", price:"Cena jednostkowa ($, własna)", frequency:"Częstotliwość", repeatShort:"Każdy zakup", onceShort:"Jednorazowo", remove:"Usuń", empty:"Nie wybrano przedmiotów", incomplete:"Suma niepełna: nieznana cena, jednostka lub przedmiot. Liczba zakupów jest niedostępna.", subtotal:"Suma znanych kosztów", reference:"Odniesienie do katalogu, nie zastosowano", compatibility:"Zapisana zgodność amunicji", compatibilityUnknown:"Nieznana. Brak udokumentowanego powiązania; sam kaliber nie potwierdza zgodności.", attachmentUnknown:"Nie zweryfikowano zgodności dodatków i magazynków, pojemności ani zawartości paczek. Ten wybór nie jest potwierdzonym zestawem.", addBudget:"Dodaj do planu budżetu", select:"Wybierz przedmiot", differences:"Tylko różnice", allTypes:"Wszystkie typy", noResults:"Brak pasujących przedmiotów", noDifferences:"Brak różniących się pól", evidence:"Dowody", manifest:"Materiały budowlane", name:"Obiekt lub zadanie (własne)", supplies:"Zasoby na sztukę (własne)", demand:"Dodatkowe zapotrzebowanie (własne)", stock:"Dostępne zapasy", capacity:"Efektywny ładunek na kurs (własny)", resource:"Jednostka lub rodzaj zasobu", trips:"Wymagane kursy", required:"Łączne zapotrzebowanie", outstanding:"Pozostałe zapotrzebowanie", supplyNote:"Wszystkie ilości używają tej samej jednostki zasobu. Pieniądze nie są zaopatrzeniem. Nieznane koszty lub ładowność nie pozwalają oszacować liczby kursów.", addLine:"Dodaj etap budowy", stage:"Etap", legacy:"Stary link nie zapisuje wersji danych. Wyświetlamy aktualne dane odniesienia; wpisane kwoty pozostają bez zmian.", changed:"Wersja danych się zmieniła. Zachowano zapisane ilości i ceny użytkownika; katalog i zgodność korzystają z aktualnych dowodów.", unsupported:"Nieobsługiwana wersja udostępniania. Wyświetlane wartości domyślne nie są przesłanym planem.", invalid:"Udostępniony plan jest nieprawidłowy lub za duży. Wyświetlono wartości domyślne, nie oryginalny plan.", shareFailed:"Nie udało się skopiować. Link znajduje się w pasku adresu.", limit:"Maksymalnie 50 pozycji", deleted:"Przedmiot nie jest już dostępny w katalogu", snapshot:"Wersja danych", custom:"Własne", perStage:"Suma etapu", firstSpend:"Pierwszy zakup", legacyVehicle:"Koszt pojazdu na zakup ($)", selectWeapon:"Broń do sprawdzenia zgodności"},
  "zh-tw": {
    shareTooLarge: "方案過長，無法分享。請縮短名稱或減少專案；位址列仍是之前的方案。",
    totalMode: "快速總額", itemsMode: "逐件清單", once: "一次性費用 ($)", repeat: "每次購買費用 ($)", purchases: "總購買次數", replacements: "首次後可補購次數", zeroCost: "每次費用為零，不設有限次數", assumptions: "使用者自定義情景，不計收入或返還。載具費用每次重複計入；一次性支出單獨填寫。",
    search: "搜尋目錄", add: "新增物品", quantity: "數量", unit: "採購單位（使用者定義）", item: "件", pack: "包", round: "發", unknown: "未知", price: "採購單位價格（自定義，$）", frequency: "購買頻率", repeatShort: "每次購買", onceShort: "僅一次", remove: "移除", empty: "尚未選擇物品", incomplete: "合計不完整：存在未知價格、單位或物品，暫不計算購買次數。", subtotal: "已知部分合計", reference: "目錄參考，未自動採用", compatibility: "已記錄的彈藥相容關係", compatibilityUnknown: "未知。沒有明確關係證據，不能僅憑相同口徑認定相容。", attachmentUnknown: "配件及彈匣適配、容量與彈藥包內容尚未核驗，所選清單不代表已確認可用的配裝。", addBudget: "加入預算規劃", select: "選擇物品", differences: "只看差異", allTypes: "全部型別", noResults: "無匹配物品", noDifferences: "沒有不同欄位", evidence: "證據", manifest: "建設物資清單", name: "建築或任務（使用者自定義）", supplies: "每件物資需求（自定義）", demand: "額外需求（自定義）", stock: "現有庫存", capacity: "每趟有效載量（自定義）", resource: "資源單位或種類", trips: "所需趟數", required: "物資總需求", outstanding: "剩餘需求", supplyNote: "所有數量使用相同資源單位。金錢不等於物資；費用或載量未知時不生成趟數估計。", addLine: "新增建設階段", stage: "階段", legacy: "舊連結未記錄資料版本。顯示當前參考資料，使用者填寫的金額保持不變。", changed: "資料版本已變化。保留連結中的自定義數量和價格；目錄參考與相容關係顯示當前證據。", unsupported: "分享版本不受支援。顯示的預設值不是原分享方案。", invalid: "分享方案無效或過大。當前顯示預設值，不是原方案。", shareFailed: "複製失敗，分享連結已寫入位址列。", limit: "最多 50 項", deleted: "目錄物品已不存在", snapshot: "資料版本", custom: "使用者自定義", perStage: "階段小計", firstSpend: "首次購買支出", legacyVehicle: "每次載具支出 ($)", selectWeapon: "選擇武器核對相容關係",
}
};

export function getWorkflowCopy(locale: string): Copy {
  return translations[resolveToolLocale(locale)];
}
