import type {Locale} from "@/config/site";

const copy: Record<Locale, readonly [string, string, string, string, string, string]> = {
  en: ["Offensive Support: unlock C4, then plan the second fight", "Colvin's October 7 video separates Support level from the paid detonator unlock, shows an unsuccessful RPG breach and a FOB that is captured, lost and retaken. The practical follow-up covers complete-kit cost and holding the entrance after the first push.", "FOB income: 334k earned, just over 200k profit", "RadioGLHF's October 6 recording ends with a loss despite high earnings. The breakdown includes three drones for one early target, mechanical-parts shortages, revive/build role changes and the difference between gross earnings and profit. It is a recorded case, not a repeatable hourly rate.", "Creator analysis", "Video publication"],
  de: ["Offensiver Support: C4 freischalten und den zweiten Kampf planen", "Colvins Video vom 7. Oktober trennt Support-Level und bezahlte Zünder-Freischaltung. Ein RPG-Durchbruch scheitert, eine FOB wird erobert, verloren und zurückgeholt. Der Guide erklärt vollständige Ausrüstungskosten und Torsicherung nach dem ersten Angriff.", "FOB-Einnahmen: 334k verdient, etwas über 200k Gewinn", "RadioGLHFs Aufnahme vom 6. Oktober endet trotz hoher Einnahmen mit einer Niederlage. Der Ablauf umfasst drei Drohnen für ein frühes Ziel, fehlende Teile, Wechsel zwischen Rettung und Bau sowie Bruttoeinnahmen und Gewinn. Ein Einzelfall, kein wiederholbarer Stundenlohn.", "Creator-Analyse", "Videoveröffentlichung"],
  ru: ["Атакующий Support: открыть C4 и подготовить второй бой", "Видео Colvin от 7 октября отделяет уровень Support от платного открытия детонатора: RPG не делает проход, а захваченный FOB теряют и берут снова. Разбор объясняет стоимость полного комплекта и охрану входа после первого штурма.", "Доход FOB: 334k заработано, чуть больше 200k прибыли", "Запись RadioGLHF от 6 октября заканчивается поражением при высоком доходе. Разбор включает три дрона на раннюю цель, дефицит деталей, переходы между спасением и строительством, разницу выручки и прибыли. Это один матч, не обещанная почасовая ставка.", "Разбор автора", "Публикация видео"],
  "pt-br": ["Support ofensivo: desbloquear C4 e preparar a segunda luta", "O vídeo de Colvin de 7 de outubro separa nível de Support e desbloqueio pago do detonador. Há uma tentativa de invasão com RPG que falha e um FOB capturado, perdido e retomado. O guia cobre custo do kit completo e defesa da entrada após o ataque.", "Renda de FOB: 334k recebidos, pouco mais de 200k de lucro", "A gravação de RadioGLHF de 6 de outubro termina em derrota apesar da renda alta. A análise inclui três drones para um alvo inicial, falta de peças, alternância entre resgate e construção e a diferença entre receita e lucro. É um caso, não renda horária garantida.", "Análise de criador", "Publicação do vídeo"],
  ja: ["攻めるSupport：C4解放と二度目の戦いを準備", "10月7日公開のColvin動画ではSupportのレベルと起爆装置の有料解放を区別し、RPGでの突破失敗、FOBの奪取と喪失、再奪還を記録。装備一式の費用と突入後の入口警戒へつなげます。", "FOB金策：総収入334k、利益は200k強", "10月6日公開のRadioGLHF動画は高収入でも敗北。最初の目標に三機を費やした失敗、機械部品不足、救助と建設の切り替え、総収入と利益の差を解説します。一試合の記録であり時給保証ではありません。", "投稿者の実戦解説", "動画公開日"],
  "zh-cn": ["进攻型Support：解锁C4后，还要准备第二场战斗", "Colvin的10月7日视频区分Support等级与引爆器付费解锁，记录RPG破点失败、FOB占下又丢失再夺回。解析落实到整套装备成本，以及突入后入口由谁来守。", "FOB收入复盘：334k总收入，净利略超200k", "RadioGLHF的10月6日录像在高收入下仍然输局。解析包含早期三发无人机才击毁一目标、机械件断供、救援建设切换与收入净利区别；这是单场记录，不是稳定时薪承诺。", "作者实战解析", "视频发布日期"],
  "zh-tw": ["進攻型Support：解鎖C4後，還要準備第二場戰鬥", "Colvin的10月7日影片區分Support等級和引爆器付費解鎖，記錄RPG破點失敗、FOB占下又失守再奪回。解析落實到整套裝備成本，以及突入後入口由誰來守。", "FOB收入復盤：334k總收入，淨利略超200k", "RadioGLHF的10月6日錄影在高收入下仍輸掉對局。解析包含早期三次無人機出擊才擊毀目標、機械零件斷供、救援建設切換與收入淨利區別；這是單場紀錄，不是穩定時薪保證。", "作者實戰解析", "影片發布日期"],
  pl: ["Ofensywny Support: odblokuj C4 i przygotuj drugi bój", "Film Colvina z 7 października rozdziela poziom Support i płatny detonator. Pokazuje nieudany atak RPG oraz FOB zdobyty, utracony i odzyskany. Omówienie obejmuje koszt pełnego zestawu i pilnowanie wejścia po pierwszym szturmie.", "Dochód FOB: 334k przychodu, nieco ponad 200k zysku", "Nagranie RadioGLHF z 6 października kończy się porażką mimo wysokich wpływów. Analiza obejmuje trzy drony na pierwszy cel, braki części, zmianę ratowania na budowę i różnicę przychodu oraz zysku. To jeden przypadek, nie gwarantowany zarobek godzinowy.", "Analiza twórcy", "Publikacja filmu"]
};
export function getRecentMatchNews(locale: Locale) {
  const c = copy[locale];
  return [
    {date: "2026-10-07", titleKey: "supportCaseOctober7", guideSlug: "wardogs-equipment-tools-guide", sources: ["https://www.youtube.com/watch?v=PhAVGZMIYCg"], title: c[0], description: c[1]},
    {date: "2026-10-06", titleKey: "fobIncomeCaseOctober6", guideSlug: "wardogs-money-guide", sources: ["https://www.youtube.com/watch?v=Qx1ndM1tc2Y"], title: c[2], description: c[3]}
  ].map(record => ({...record, sourceClass: "creator-current" as const, kind: "change" as const, status: "Confirmed" as const, badge: c[4], dateLabel: c[5]}));
}
