import type {Locale} from "@/config/site";
const copy: Record<Locale, {metaDescription: string; currentSourcesTitle: string; currentSourcesDescription: string}> = {
  en: {metaDescription: "WARDOGS video guides: Season 2 developer interview, attachments, solo FOBs, IR hotfix, money, helicopters and preserved gameplay walkthroughs, with timed chapters.", currentSourcesTitle: "Creator videos by player task", currentSourcesDescription: "Each source keeps its own publication and review date. Recent caption-based breakdowns sit alongside the September watchlist; compare the recorded build with current official rules."},
  de: {metaDescription: "WARDOGS-Videoguides: Saison-2-Interview, Aufsätze, Solo-FOBs, IR-Hotfix, Geld, Helikopter und ältere Gameplay-Anleitungen mit Zeitmarken.", currentSourcesTitle: "Creator-Videos nach Spielaufgabe", currentSourcesDescription: "Jede Quelle behält ihr Veröffentlichungs- und Prüfdatum. Neue Untertitel-Auswertungen ergänzen die September-Liste; vergleiche die gezeigte Version mit aktuellen offiziellen Regeln."},
  ru: {metaDescription: "Видеогайды WARDOGS: интервью о сезоне 2, модули, одиночные FOB, IR-хотфикс, деньги, вертолёты и сохранённые разборы с временными метками.", currentSourcesTitle: "Видео авторов по игровым задачам", currentSourcesDescription: "У источников отдельные даты публикации и проверки. Новые разборы субтитров дополняют сентябрьский список; сверяйте записанную версию с текущими официальными правилами."},
  "pt-br": {metaDescription: "Guias em vídeo de WARDOGS: entrevista da Temporada 2, acessórios, FOB solo, hotfix IR, dinheiro, helicópteros e análises anteriores com capítulos.", currentSourcesTitle: "Vídeos de criadores por tarefa", currentSourcesDescription: "Cada fonte mantém sua data de publicação e revisão. Novas análises de legendas complementam a lista de setembro; compare a versão gravada com as regras oficiais atuais."},
  ja: {metaDescription: "WARDOGS動画攻略。シーズン2開発者インタビュー、アタッチメント、ソロFOB、IR修正、金策、ヘリ、過去の実戦解説を時間指定チャプターで確認。", currentSourcesTitle: "目的別の投稿者動画", currentSourcesDescription: "公開日と確認日は動画ごとに表示します。新しい字幕解説と9月の動画一覧を併記し、録画時のバージョンと現在の公式ルールを区別しています。"},
  "zh-cn": {metaDescription: "WARDOGS视频攻略：第二赛季开发者访谈、配件取舍、单人FOB、IR热修、赚钱与直升机操作。保留历史实机解析，提供时间章节和后续工具入口。", currentSourcesTitle: "按玩家任务查找作者视频", currentSourcesDescription: "每份来源保留独立的发布与核验日期。近期字幕解读与9月视频清单并存，请对照录制版本和当前官方规则使用。"},
  "zh-tw": {metaDescription: "WARDOGS影片攻略：第二賽季開發者訪談、配件取捨、單人FOB、IR熱修、賺錢與直升機操作。保留歷史實機解析，提供時間章節及後續工具入口。", currentSourcesTitle: "依玩家任務查找作者影片", currentSourcesDescription: "每份來源保留獨立的發布與查核日期。近期字幕解讀與9月影片清單並存，請對照錄製版本和目前官方規則使用。"},
  pl: {metaDescription: "Poradniki wideo WARDOGS: wywiad o sezonie 2, dodatki, FOB solo, hotfix IR, zarabianie, śmigłowce i zachowane analizy z rozdziałami czasowymi.", currentSourcesTitle: "Filmy twórców według zadań gracza", currentSourcesDescription: "Każde źródło zachowuje datę publikacji i przeglądu. Nowe omówienia napisów uzupełniają listę wrześniową; porównuj nagraną wersję z aktualnymi oficjalnymi zasadami."}
};
export function getRecentVideoHubCopy(locale: Locale) {return copy[locale];}
