import type {Locale} from "@/config/site";

// Descriptions summarize the creator's displayed description, not a review of unseen footage.
const copy: Record<Locale, readonly string[]> = {
  en: ["A single full match combines FOB building, an oil rig, healing and Stingray use. The 334k title is this creator's reported result, not a repeatable hourly income rate.", "The creator describes an attacking Support style. Use it to compare team roles; the title does not establish weapon statistics or a universally best class.", "A helicopter attack, lost kits and an anti-air response give this recording a defensive-FOB focus. The creator's chapters mark situations, not a tested damage table.", "Shacknews' Recon stream follows a squad with scoped weapons, bandages and concealed positions. Compare observation and movement decisions; the complete recording has not been reviewed here.", "Shacknews' Transport stream focuses on taking players from HQ to the combat area by helicopter. The programme describes low flight and cover; landing safety still depends on the current situation.", "The third Shacknews stream brings the squad into busy combat areas. This is a match recording for team decisions, not a Season 2 feature announcement."],
  de: ["Eine vollständige Runde verbindet FOB-Bau, Bohrinsel, Heilung und Stingray. Die 334.000 im Titel sind das gemeldete Ergebnis dieser Runde, kein wiederholbarer Stundenverdienst.", "Der Autor beschreibt einen offensiven Support-Stil. Vergleiche damit Teamrollen; der Titel belegt weder Waffenwerte noch eine allgemein beste Klasse.", "Helikopterangriff, verlorene Ausrüstung und Flugabwehr geben dem Video einen FOB-Verteidigungsfokus. Kapitel markieren Situationen, keine geprüfte Schadenstabelle.", "Shacknews zeigt ein Recon-Team mit Zielfernrohren, Verbänden und verdeckten Positionen. Vergleiche Beobachtung und Bewegung; die vollständige Aufnahme wurde hier nicht geprüft.", "Der Transport-Stream behandelt Helikopterfahrten vom HQ ins Kampfgebiet. Das Programm nennt Tiefflug und Deckung; sichere Landungen hängen weiterhin von der Lage ab.", "Der dritte Shacknews-Stream führt das Team in stark umkämpfte Bereiche. Eine Matchaufnahme für Teamentscheidungen, keine Ankündigung neuer Season-2-Funktionen."],
  ru: ["Один полный матч объединяет строительство FOB, нефтяную вышку, лечение и Stingray. 334 тысячи в заголовке — заявленный результат автора, а не гарантированный доход в час.", "Автор описывает атакующий стиль Support. Сравнивайте командные роли; заголовок не доказывает характеристики оружия или превосходство класса.", "Атака вертолёта, потеря комплектов и ответ ПВО задают тему защиты FOB. Главы обозначают ситуации, а не проверенную таблицу урона.", "В Recon-трансляции Shacknews отряд использует оптику, бинты и укрытые позиции. Сравнивайте наблюдение и перемещение; полная запись здесь не проверена.", "Транспортная трансляция посвящена доставке игроков вертолётом от HQ к бою. Описание упоминает малую высоту и укрытия; безопасность посадки зависит от обстановки.", "Третья трансляция Shacknews отправляет отряд в зоны активного боя. Это запись матча для разбора командных решений, а не анонс функций Season 2."],
  "pt-br": ["Uma partida completa combina construção de FOB, plataforma de petróleo, cura e Stingray. Os 334 mil do título são o resultado relatado pelo autor, não uma renda horária garantida.", "O autor descreve um Support ofensivo. Compare funções da equipe; o título não comprova atributos das armas nem uma classe melhor em toda situação.", "Ataque de helicóptero, perda de equipamentos e reação antiaérea dão foco à defesa de FOB. Os capítulos indicam situações, não uma tabela de dano testada.", "A transmissão Recon da Shacknews acompanha um esquadrão com miras, bandagens e posições ocultas. Compare observação e movimentação; a gravação completa ainda não foi revisada aqui.", "A transmissão de transporte leva jogadores de helicóptero do HQ até a zona de combate. A descrição cita voo baixo e cobertura; pousar com segurança depende da situação.", "A terceira transmissão da Shacknews leva o esquadrão a áreas de combate intenso. É uma partida para analisar decisões em equipe, não um anúncio de recursos da Season 2."],
  ja: ["FOB建設、油井、回復、Stingrayを組み合わせた1試合の記録です。タイトルの334kは投稿者が報告した結果で、再現可能な時給ではありません。", "投稿者は攻めるSupportの立ち回りを紹介しています。役割の比較に使い、タイトルだけで武器性能や最強クラスを断定しないでください。", "ヘリの攻撃、装備損失、対空対応を扱うFOB防衛寄りの記録です。チャプターは場面の目印で、検証済みダメージ表ではありません。", "ShacknewsのRecon配信はスコープ付き武器、包帯、隠れた位置を使う分隊が題材です。観測と移動を比較できますが、こちらでは全編を確認していません。", "輸送配信はHQから戦闘地域へプレイヤーをヘリで運ぶ内容です。番組説明では低空飛行と遮蔽物に触れていますが、安全な着陸は現地状況次第です。", "Shacknewsの第3回は分隊で激戦区へ向かう配信です。チーム判断を考える試合記録で、Season 2の新機能発表ではありません。"],
  "zh-cn": ["一场完整对局同时使用FOB建设、油井、治疗和Stingray。标题的334k是作者报告的单局结果，不是可重复的每小时收入。", "作者介绍进攻型Support打法，可用于比较团队分工；仅凭标题不能确认武器数值或认定某职业永远最强。", "直升机袭击、装备损失与防空反击构成FOB防守案例。作者章节只是场景导航，不是经过验证的伤害表。", "Shacknews侦察篇围绕带瞄具武器、绷带与隐蔽位置展开。可比较观察和移动决策；此处尚未审阅完整实况。", "Shacknews运输篇把玩家从HQ送到交战区。节目介绍提到低空飞行与掩体，但降落安全仍取决于实际战况。", "Shacknews第三篇带小队进入密集战区。这是供比较团队决策的对局录像，并非Season 2新功能公告。"],
  "zh-tw": ["一場完整對局同時運用FOB建設、油井、治療和Stingray。標題的334k是作者回報的單局結果，不是可重複的每小時收入。", "作者介紹進攻型Support玩法，可用來比較團隊分工；光看標題無法確認武器數值或認定某職業永遠最強。", "直升機襲擊、裝備損失與防空反擊構成FOB防守案例。作者章節只是場景導覽，不是經過驗證的傷害表。", "Shacknews偵察篇圍繞瞄具武器、繃帶與隱蔽位置展開。可比較觀察和移動決策；此處尚未檢視完整實況。", "Shacknews運輸篇把玩家從HQ送到交戰區。節目介紹提到低空飛行與掩體，但降落安全仍取決於實際戰況。", "Shacknews第三篇帶小隊進入密集戰區。這是供比較團隊決策的對局錄影，並非Season 2新功能公告。"],
  pl: ["Jeden pełny mecz łączy budowę FOB, platformę naftową, leczenie i Stingray. 334 tysiące w tytule to wynik podany przez autora, a nie powtarzalny zarobek na godzinę.", "Autor opisuje ofensywny styl Support. Porównuj role zespołu; sam tytuł nie potwierdza statystyk broni ani najlepszej klasy w każdej sytuacji.", "Atak śmigłowca, utrata zestawów i odpowiedź przeciwlotnicza tworzą przykład obrony FOB. Rozdziały wskazują sytuacje, a nie zweryfikowaną tabelę obrażeń.", "Transmisja Recon od Shacknews pokazuje oddział z optyką, bandażami i ukrytymi pozycjami. Porównuj obserwację i ruch; nie przejrzano tu całego nagrania.", "Transmisja transportowa dotyczy przewozu graczy śmigłowcem z HQ do strefy walki. Opis wspomina niski lot i osłony; bezpieczeństwo lądowania zależy od sytuacji.", "Trzecia transmisja Shacknews prowadzi oddział do intensywnych walk. To zapis meczu do analizy decyzji zespołu, nie zapowiedź funkcji Season 2."]
};
const ids = ["Qx1ndM1tc2Y", "PhAVGZMIYCg", "NC7nsS8qKBM", "PNfh95Ua4-M", "-4QpcApA6SY", "MI_aXSfoQws"];
export function getRecentCandidateCopy(locale: Locale, youtubeId: string) {
  const index = ids.indexOf(youtubeId);
  return index < 0 ? undefined : copy[locale][index];
}
