import type {Locale} from "@/config/site";
import type {CurrentVideoTopic} from "./video-library";

export const RECENT_VIDEO_CHECKED_AT = "2026-10-09";
export type RecentVideo = {
  id: string; title: string; channel: string; publishedAt: string; durationSeconds: number;
  topic: CurrentVideoTopic; guideSlug: string; toolPath: string;
  articleSlug?: string; captionReview: "full-track-read" | "not-reviewed";
  /** Native English captions read; neither audio alignment nor current-client reproduction. */
  chapters: readonly {seconds: number; label: string}[];
};

// Exact publication timestamps and lengths from the public YouTube player metadata.
// Dates shown in the October review use Asia/Shanghai; live start is not VOD publication.
export const recentVideos: readonly RecentVideo[] = [
  {id: "liRK9si1Ubo", title: "We Asked the Wardogs Devs EVERYTHING | Push to Talk Podcast", channel: "BigfryTV & Crash Games", publishedAt: "2026-10-01T11:52:18-07:00", durationSeconds: 5796, topic: "progression", guideSlug: "wardogs-season-2", toolPath: "/tools/progression-route", articleSlug: "wardogs-season-2-developer-interview", captionReview: "full-track-read", chapters: [{seconds: 1958, label: "Gold Market and retention"}, {seconds: 2764, label: "Season length"}, {seconds: 3230, label: "Parachutes and landing"}, {seconds: 5127, label: "Level 4 helmet"}, {seconds: 5181, label: "Weather"}, {seconds: 5315, label: "Four weapons"}]},
  {id: "kC3P-klWNxk", title: "You've been using the WRONG attachments in WARDOGS", channel: "Evo4Fun", publishedAt: "2026-10-07T12:43:50-07:00", durationSeconds: 1152, topic: "loadouts", guideSlug: "wardogs-best-weapons-loadouts", toolPath: "/tools/loadout-budget", articleSlug: "wardogs-attachments-tested", captionReview: "full-track-read", chapters: [{seconds: 48, label: "Attachment trade-offs"}, {seconds: 349, label: "Assault rifles"}, {seconds: 597, label: "SMGs"}, {seconds: 790, label: "LMGs"}, {seconds: 841, label: "DMRs"}, {seconds: 942, label: "Snipers"}, {seconds: 989, label: "Shotguns"}, {seconds: 1042, label: "Pistols"}, {seconds: 1105, label: "Limits and preferences"}]},
  {id: "z7wMLQQtIIM", title: "I BUILT THE PERFECT SOLO/DUO FOB IN WARDOGS", channel: "Wake Up", publishedAt: "2026-10-08T00:38:15-07:00", durationSeconds: 1153, topic: "fob", guideSlug: "wardogs-fob-layouts", toolPath: "/tools/logistics-planner", articleSlug: "wardogs-solo-duo-fob-layout", captionReview: "full-track-read", chapters: [{seconds: 0, label: "Supply plan"}, {seconds: 221, label: "Sealed shell"}, {seconds: 447, label: "Mortar pit"}, {seconds: 561, label: "Talon construction"}, {seconds: 847, label: "Door and re-entry limits"}, {seconds: 901, label: "Cover and firing arcs"}]},
  {id: "j7hJXEXo5U8", title: "WARDOGS Just Removed the Most Overpowered Item in the Game", channel: "Airwingmarine", publishedAt: "2026-10-05T09:20:05-07:00", durationSeconds: 1363, topic: "patches", guideSlug: "wardogs-equipment-tools-guide", toolPath: "/gold-market", articleSlug: "wardogs-ir-rangefinder-hotfix", captionReview: "full-track-read", chapters: [{seconds: 30, label: "IR vendor change"}, {seconds: 272, label: "CIWS and Havoc"}, {seconds: 412, label: "Player observations"}, {seconds: 666, label: "Gold-price speculation"}, {seconds: 1020, label: "Developer interview recap"}]},
  {id: "Qx1ndM1tc2Y", title: "Wardogs - Full Match - 334k earned in FOB - Money tips - Full Commentary!", channel: "RadioGLHF", publishedAt: "2026-10-05T13:02:26-07:00", durationSeconds: 3420, topic: "money", guideSlug: "wardogs-money-guide", toolPath: "/tools/logistics-planner", captionReview: "not-reviewed", chapters: []},
  {id: "PhAVGZMIYCg", title: "How I Discovered The Perfect Support Playstyle In Wardogs!", channel: "Colvin", publishedAt: "2026-10-06T09:00:03-07:00", durationSeconds: 740, topic: "progression", guideSlug: "wardogs-beginner-guide", toolPath: "/tools/progression-route", captionReview: "not-reviewed", chapters: []},
  {id: "NC7nsS8qKBM", title: "The Grenade-Launcher Helicopter Nobody Warned Me About | Wardogs", channel: "Nalerian", publishedAt: "2026-10-05T12:00:29-07:00", durationSeconds: 514, topic: "helicopter", guideSlug: "wardogs-fob-guide", toolPath: "/tools/map", captionReview: "not-reviewed", chapters: [{seconds: 0, label: "Air attack"}, {seconds: 169, label: "Kit losses"}, {seconds: 232, label: "Anti-air"}, {seconds: 293, label: "Spawn vehicle"}, {seconds: 360, label: "FOB attack"}]},
  {id: "PNfh95Ua4-M", title: "ShackStream: A trifecta of Wardogs strategies #1 - Recon", channel: "Shacknews", publishedAt: "2026-10-06T09:27:58-07:00", durationSeconds: 6775, topic: "teamplay", guideSlug: "wardogs-squad-guide", toolPath: "/tools/map", captionReview: "not-reviewed", chapters: []},
  {id: "-4QpcApA6SY", title: "ShackStream: A trifecta of Wardogs strategies #2 - Transport", channel: "Shacknews", publishedAt: "2026-10-07T12:08:17-07:00", durationSeconds: 6597, topic: "helicopter", guideSlug: "wardogs-helicopter-guide", toolPath: "/tools/map", captionReview: "not-reviewed", chapters: []},
  {id: "MI_aXSfoQws", title: "ShackStream: A trifecta of Wardogs strategies #3 - Mayhem", channel: "Shacknews", publishedAt: "2026-10-08T10:49:34-07:00", durationSeconds: 7034, topic: "teamplay", guideSlug: "wardogs-towers-guide", toolPath: "/tools/map", captionReview: "not-reviewed", chapters: []}
];

export function recentVideoDate(video: RecentVideo) {
  return new Date(new Date(video.publishedAt).getTime() + 8 * 60 * 60 * 1000).toISOString().slice(0, 10);
}

export const recentVideoUi: Record<Locale, {current: string; title: string; full: string; metadata: string; chapters: string; apply: string; limits: string; tool: string; published: string; checked: string; timezone: string}> = {
  en: {current: "October analysis", title: "Recent videos and practical follow-ups", full: "Full caption track read; not an in-game reproduction", metadata: "Title, date and creator description checked; full footage not reviewed", chapters: "Jump to a chapter", apply: "What to do in your next match", limits: "What this source does not establish", tool: "Open the related tool", published: "Published", checked: "Source checked", timezone: "Publication dates: Shanghai time (UTC+8)"},
  de: {current: "Oktober-Analyse", title: "Neue Videos und praktische nächste Schritte", full: "Vollständige Untertitel gelesen; nicht im Spiel nachgestellt", metadata: "Titel, Datum und Beschreibung geprüft; vollständige Aufnahme nicht geprüft", chapters: "Kapitel auswählen", apply: "Anwendung im nächsten Match", limits: "Was die Quelle nicht belegt", tool: "Passendes Werkzeug öffnen", published: "Veröffentlicht", checked: "Quelle geprüft", timezone: "Veröffentlichungsdatum: Shanghai (UTC+8)"},
  ru: {current: "Октябрьский разбор", title: "Свежие видео и практические шаги", full: "Все субтитры прочитаны; в игре не воспроизведено", metadata: "Проверены название, дата и описание; вся запись не просмотрена", chapters: "Перейти к главе", apply: "Что сделать в следующем матче", limits: "Чего источник не подтверждает", tool: "Открыть связанный инструмент", published: "Опубликовано", checked: "Источник проверен", timezone: "Даты публикации: Шанхай (UTC+8)"},
  "pt-br": {current: "Análise de outubro", title: "Vídeos recentes e próximos passos", full: "Legendas completas lidas; sem reprodução no jogo", metadata: "Título, data e descrição conferidos; gravação completa não revisada", chapters: "Ir para um capítulo", apply: "O que fazer na próxima partida", limits: "O que a fonte não comprova", tool: "Abrir ferramenta relacionada", published: "Publicado", checked: "Fonte conferida", timezone: "Datas de publicação: Xangai (UTC+8)"},
  ja: {current: "10月の動画解説", title: "新着動画と実戦への活用", full: "字幕全編を確認済み・ゲーム内での再現検証は未実施", metadata: "タイトル・公開日・説明欄を確認済み・映像全編は未確認", chapters: "チャプターへ移動", apply: "次の試合で試すこと", limits: "この情報源だけでは分からないこと", tool: "関連ツールを開く", published: "公開日", checked: "情報源確認日", timezone: "公開日は上海時間（UTC+8）"},
  "zh-cn": {current: "10月视频解析", title: "近期视频与实战下一步", full: "已读完整字幕；尚未在游戏内复现", metadata: "已核标题、日期与作者描述；尚未完整审阅画面", chapters: "跳转到章节", apply: "下一场怎么用", limits: "这份来源不能证明什么", tool: "打开相关工具", published: "发布日期", checked: "来源核验", timezone: "发布日期采用北京时间（UTC+8）"},
  "zh-tw": {current: "10月影片解析", title: "近期影片與實戰下一步", full: "已讀完整字幕；尚未在遊戲內重現", metadata: "已核對標題、日期與作者說明；尚未完整檢視畫面", chapters: "跳至章節", apply: "下一場如何運用", limits: "這份來源無法證明什麼", tool: "開啟相關工具", published: "發布日期", checked: "來源查核", timezone: "發布日期採用台北時間（UTC+8）"},
  pl: {current: "Analiza z października", title: "Nowe filmy i praktyczne wskazówki", full: "Przeczytano pełne napisy; bez odtworzenia w grze", metadata: "Sprawdzono tytuł, datę i opis; nie przejrzano całego nagrania", chapters: "Przejdź do rozdziału", apply: "Co zrobić w następnym meczu", limits: "Czego źródło nie potwierdza", tool: "Otwórz powiązane narzędzie", published: "Opublikowano", checked: "Sprawdzono źródło", timezone: "Daty publikacji: Szanghaj (UTC+8)"}
};
