import type {Locale} from "@/config/site";
import type {CandidateCaution} from "./video-candidates";
import type {CaptionReview, EvidenceCaution} from "./video-candidate-evidence";

type Copy = {title: string; summary: string; metadata: string; chapters: string; noChapters: string; play: string; close: string; guide: string; watch: string; cautions: Record<CandidateCaution, string>};
const copy: Record<Locale, Copy> = {
  en: {title: "New creator videos: candidates", summary: "Original titles, authors, dates and available chapters checked September 30. Operations, full transcripts and embedded playback are not verified. Creator videos are not official game guidance; chapter links are navigation only.", metadata: "Metadata checked", chapters: "Displayed chapters", noChapters: "No chapters verified", play: "Open YouTube player", close: "Close player", guide: "Related guide", watch: "Original video", cautions: {operations: "Compare the current game prompts and your own bindings. No verified default keys or step-by-step procedure is inferred from the title.", calculator: "Third-party calculator: accuracy, voice input and permissions have not been tested. No guaranteed hit or microphone-access recommendation.", gold: "Historical prices are not current quotes. Only official sources establish wipe and retention rules.", rollback: "Conditional Windows-update case, not a universal fix. Check the official WD-L020 notice first; removing security updates has risks.", layout: "Costs, protection and placement have not been reproduced. 'Best' or 'ultimate' is the creator's title, not our assessment. Stingray is not SPH2.", axis: "A viewer questions the axis explanation around 03:23. Unresolved: do not copy that setting as a verified rule.", sponsor: "Contains accelerator promotion. It is not an endorsed connection or crash fix; gameplay chapters start after the promotion.", disputed: "Viewer corrections dispute container, reward and durability claims. Pending review; do not use its numbers as authoritative."}},
  ja: {title: "新しい投稿者動画：候補", summary: "9月30日に原題・投稿者・公開日・確認できたチャプターを確認。操作、字幕全文、埋め込み再生は未検証です。公式攻略ではなく、チャプターは視聴位置の案内です。", metadata: "メタデータ確認", chapters: "ページ掲載チャプター", noChapters: "チャプター未確認", play: "YouTube プレーヤーを開く", close: "プレーヤーを閉じる", guide: "関連ガイド", watch: "元の動画", cautions: {operations: "現在のゲーム内表示と自分の割り当てを照合してください。タイトルから操作手順や初期キーを断定しません。", calculator: "外部計算機です。精度・音声入力・権限は未検証。命中保証やマイク許可を推奨しません。", gold: "過去の価格は現在の相場ではありません。ワイプと保持条件は公式情報を優先します。", rollback: "Windows 更新に関する条件付き事例です。先に公式 WD-L020 告知を確認。セキュリティ更新の削除にはリスクがあります。", layout: "費用・防御効果・配置は再現検証していません。「最強」は原題の表現です。Stingray は SPH2 ではありません。", axis: "03:23 付近の軸説明に視聴者から疑問が出ています。未解決のため確定設定として転用しません。", sponsor: "通信アクセラレーターの宣伝を含みます。接続・クラッシュ対策として推奨しません。操作章は宣伝の後です。", disputed: "コンテナ・報酬・耐久の説明に視聴者の訂正があります。未裁定であり、数値を根拠にしないでください。"}},
  ru: {title: "Новые видео авторов: кандидаты", summary: "30 сентября проверены исходные названия, авторы, даты и доступные главы. Действия, полный текст субтитров и встроенное воспроизведение не проверены. Это не официальные инструкции; главы служат только навигацией.", metadata: "Метаданные проверены", chapters: "Главы на странице", noChapters: "Главы не подтверждены", play: "Открыть плеер YouTube", close: "Закрыть плеер", guide: "Связанный гайд", watch: "Исходное видео", cautions: {operations: "Сверяйте подсказки текущей игры и свои назначения клавиш. Заголовок не подтверждает стандартные клавиши или порядок действий.", calculator: "Сторонний калькулятор: точность, голосовой ввод и разрешения не проверены. Нет гарантии попадания или рекомендации давать доступ к микрофону.", gold: "Исторические цены не равны текущему курсу. Правила вайпа и сохранения устанавливают только официальные источники.", rollback: "Условный случай обновления Windows, не универсальное исправление. Сначала прочитайте официальное сообщение WD-L020; удаление обновлений безопасности несет риски.", layout: "Стоимость, защита и размещение не воспроизведены. «Лучший» в заголовке не является нашей оценкой. Stingray не равен SPH2.", axis: "Зритель оспаривает объяснение осей около 03:23. Вопрос не решен; не считайте настройку проверенным правилом.", sponsor: "Есть реклама ускорителя сети. Это не рекомендация для исправления соединения или вылетов. Главы об игре идут после рекламы.", disputed: "Есть возражения зрителей о контейнерах, выплатах и прочности. Спор не проверен; не используйте числа как достоверные."}},
  de: {title: "Neue Creator-Videos: Kandidaten", summary: "Originaltitel, Autoren, Daten und verfügbare Kapitel am 30. September geprüft. Abläufe, vollständige Untertitel und eingebettete Wiedergabe sind nicht verifiziert. Keine offiziellen Spielanleitungen; Kapitel dienen nur zur Navigation.", metadata: "Metadaten geprüft", chapters: "Angezeigte Kapitel", noChapters: "Keine Kapitel bestätigt", play: "YouTube-Player öffnen", close: "Player schließen", guide: "Passender Guide", watch: "Originalvideo", cautions: {operations: "Aktuelle Spielhinweise und eigene Belegung vergleichen. Titel bestätigen keine Standardtasten oder Abläufe.", calculator: "Externer Rechner: Genauigkeit, Spracheingabe und Berechtigungen ungetestet. Keine Treffergarantie oder Empfehlung für Mikrofonzugriff.", gold: "Historische Preise sind keine aktuellen Kurse. Wipe- und Erhaltungsregeln benötigen offizielle Quellen.", rollback: "Bedingter Windows-Update-Fall, keine universelle Lösung. Zuerst den offiziellen WD-L020-Hinweis lesen; entfernte Sicherheitsupdates haben Risiken.", layout: "Kosten, Schutz und Platzierung nicht nachgestellt. Superlative gehören zum Originaltitel, nicht zu unserer Bewertung. Stingray ist nicht SPH2.", axis: "Ein Zuschauer hinterfragt die Achsenerklärung bei 03:23. Ungeklärt, daher keine bestätigte Einstellung.", sponsor: "Enthält Werbung für Netzwerkbeschleuniger. Keine Empfehlung gegen Verbindungsfehler oder Abstürze; Spielkapitel folgen der Werbung.", disputed: "Zuschauer widersprechen Angaben zu Behältern, Ertrag und Haltbarkeit. Ungeklärt; Zahlen nicht als gesichert übernehmen."}},
  "pt-br": {title: "Novos vídeos de criadores: candidatos", summary: "Títulos originais, autores, datas e capítulos disponíveis conferidos em 30 de setembro. Operações, legendas completas e reprodução incorporada não foram verificadas. Não são instruções oficiais; capítulos servem apenas à navegação.", metadata: "Metadados conferidos", chapters: "Capítulos exibidos", noChapters: "Capítulos não confirmados", play: "Abrir player do YouTube", close: "Fechar player", guide: "Guia relacionado", watch: "Vídeo original", cautions: {operations: "Compare os avisos atuais do jogo e suas teclas. O título não confirma atalhos padrão nem procedimentos.", calculator: "Calculadora externa: precisão, voz e permissões não testadas. Sem garantia de acerto ou recomendação de acesso ao microfone.", gold: "Preços históricos não são cotações atuais. Regras de wipe e retenção dependem de fontes oficiais.", rollback: "Caso condicional de atualização do Windows, não correção universal. Leia primeiro o aviso oficial WD-L020; remover atualizações de segurança envolve riscos.", layout: "Custos, proteção e posicionamento não foram reproduzidos. Superlativos são do título original, não nossa avaliação. Stingray não é SPH2.", axis: "Um espectador questiona a explicação dos eixos em 03:23. Questão não resolvida; não trate a configuração como regra validada.", sponsor: "Contém promoção de acelerador de rede. Não recomendamos como solução de conexão ou crash; os capítulos de jogo vêm depois da propaganda.", disputed: "Comentários contestam contêineres, recompensas e durabilidade. Divergências não resolvidas; não use os números como referência confirmada."}},
  "zh-cn": {title: "创作者新视频：候选区", summary: "9月30日核对原题、作者、绝对日期与可读章节。操作、完整字幕及本站嵌入播放均未核验；创作者视频不是官方攻略，章节仅用于定位。", metadata: "元数据核对", chapters: "页面可见章节", noChapters: "未核到章节", play: "打开 YouTube 播放器", close: "关闭播放器", guide: "相关攻略", watch: "原作者视频", cautions: {operations: "请对照当前游戏提示及自己的改键。不能由标题推导默认按键或已验证操作步骤。", calculator: "第三方计算器的精度、语音功能与权限未测试，不保证命中，也不建议据此授予麦克风权限。", gold: "历史价格不等于当前报价。清档与保留规则只以官方来源为据。", rollback: "Windows 更新的条件性案例，不是通用修复。先读官方 WD-L020 公告；移除安全更新存在风险。", layout: "造价、防御效果和放置方式尚未复现；“最强”等是原标题措辞，不是本站评价。Stingray 不是 SPH2。", axis: "观众对约03:23的轴分离解释提出疑问，尚未裁定，不能当作已验证设置。", sponsor: "包含网络加速器推广，不作为连接或崩溃修复推荐。操作章节从推广之后开始。", disputed: "观众对容器、收益与耐久提出纠错，争议尚未复核；不引用其中数值作为攻略依据。"}},

  pl: {title:"Nowe filmy twórców: kandydaci", summary:"30 września sprawdzono oryginalne tytuły, autorów, daty i dostępne rozdziały. Nie zweryfikowano procedur, pełnych transkrypcji ani odtwarzania osadzonych filmów. Materiały twórców nie są oficjalnymi instrukcjami; rozdziały służą tylko nawigacji.", metadata:"Metadane sprawdzone", chapters:"Widoczne rozdziały", noChapters:"Brak potwierdzonych rozdziałów", play:"Otwórz odtwarzacz YouTube", close:"Zamknij odtwarzacz", guide:"Powiązany poradnik", watch:"Oryginalny film", cautions:{operations:"Porównaj bieżące komunikaty gry i własne przypisania klawiszy. Tytuł nie potwierdza klawiszy domyślnych ani procedury krok po kroku.", calculator:"Kalkulator zewnętrzny: nie przetestowano dokładności, obsługi głosu ani uprawnień. Nie gwarantujemy trafień ani nie zalecamy udostępniania mikrofonu.", gold:"Historyczne ceny nie są obecnymi notowaniami. Zasady resetu i zachowania postępów potwierdzają wyłącznie oficjalne źródła.", rollback:"Warunkowy przypadek aktualizacji Windows, nie uniwersalna naprawa. Najpierw przeczytaj oficjalny komunikat WD-L020; usuwanie aktualizacji bezpieczeństwa wiąże się z ryzykiem.", layout:"Nie odtworzono kosztów, ochrony ani rozmieszczenia. Określenia typu najlepszy pochodzą z tytułu twórcy, nie z naszej oceny. Stingray to nie SPH2.", axis:"Widz kwestionuje wyjaśnienie osi około 03:23. Sprawa nierozstrzygnięta: nie traktuj tych ustawień jako zweryfikowanej zasady.", sponsor:"Zawiera promocję akceleratora sieciowego. Nie rekomendujemy go jako naprawy połączenia ani awarii; rozdziały o rozgrywce zaczynają się po reklamie.", disputed:"Uwagi widzów podważają informacje o pojemnikach, nagrodach i wytrzymałości. Wymagają sprawdzenia; nie traktuj podanych liczb jako potwierdzonych."}},
  "zh-tw": { title: "創作者新影片：候選區", summary: "9月30日核對原題、作者、絕對日期與可讀章節。操作、完整字幕及本站嵌入播放均未核驗；創作者影片不是官方攻略，章節僅用於定位。", metadata: "後設資料核對", chapters: "頁面可見章節", noChapters: "未核到章節", play: "開啟 YouTube 播放器", close: "關閉播放器", guide: "相關攻略", watch: "原作者影片", cautions: { operations: "請對照當前遊戲提示及自己的改鍵。不能由標題推導預設按鍵或已驗證操作步驟。", calculator: "第三方計算器的精度、語音功能與許可權未測試，不保證命中，也不建議據此授予麥克風許可權。", gold: "歷史價格不等於當前報價。清檔與保留規則只以官方來源為據。", rollback: "Windows 更新的條件性案例，不是通用修復。先讀官方 WD-L020 公告；移除安全更新存在風險。", layout: "造價、防禦效果和放置方式尚未復現；“最強”等是原標題措辭，不是本站評價。Stingray 不是 SPH2。", axis: "觀眾對約03:23的軸分離解釋提出疑問，尚未裁定，不能當作已驗證設定。", sponsor: "包含網路加速器推廣，不作為連線或崩潰修復推薦。操作章節從推廣之後開始。", disputed: "觀眾對容器、收益與耐久提出糾錯，爭議尚未複核；不引用其中數值作為攻略依據。" } }
};

type ReviewCopy = {
  summary: string;
  reviewed: string;
  captions: Record<CaptionReview, string>;
  footage: string;
  intro: string;
  noFootage: string;
  evidenceCautions: Record<EvidenceCaution, string>;
};

const reviewCopy: Record<Locale, ReviewCopy> = {
  en: {
    summary: "September 30 review: automatic caption exports and selected source-video frames are distinguished below. Captions may contain errors and were not independently checked against the audio. No full-video viewing, game-client reproduction or site-embed playback verification. Creator videos are not official guidance; chapters are navigation only.",
    reviewed: "Evidence review", captions: {"full-track-read": "Full automatic caption track exported; full text read", "excerpts-read": "Full automatic caption track exported; selected passages read", unavailable: "No caption export obtained"},
    footage: "Source footage sampled", intro: "Intro only", noFootage: "Source footage not inspected",
    evidenceCautions: {"wipe-estimate": "The creator presents October 10 as a working wipe estimate, not an official confirmed date.", "floating-roof": "The creator calls the floating roof an exploit and expects it to be patched. Do not treat it as durable building guidance.", "input-overlay": "The creator says the overlay arrow shows cursor position relative to screen center, not raw mouse movement."}
  },
  ja: {
    summary: "9月30日確認。自動字幕の取得・読解と元動画の部分的な画面確認を分けて表示します。字幕には誤認識があり、音声との独立照合はしていません。全編視聴、ゲーム内再現、当サイトの埋め込み再生は未検証です。公式攻略ではなく、チャプターは視聴位置の案内です。",
    reviewed: "確認日", captions: {"full-track-read": "自動字幕トラック全体を取得・全文を読解", "excerpts-read": "自動字幕トラック全体を取得・一部を読解", unavailable: "字幕を取得できず"},
    footage: "元動画の画面を部分確認", intro: "導入部分のみ", noFootage: "元動画の画面は未確認",
    evidenceCautions: {"wipe-estimate": "投稿者が示す10月10日は暫定的なワイプ予想で、公式の確定日ではありません。", "floating-roof": "投稿者自身が浮いた屋根を不具合利用と呼び、修正を予想しています。継続して使える建築手順とは見なせません。", "input-overlay": "投稿者によると矢印は画面中央に対するカーソル位置であり、マウスの生の移動量ではありません。"}
  },
  ru: {
    summary: "Проверка 30 сентября: экспорт и чтение автосубтитров отделены от выборочного просмотра кадров исходного видео. Возможны ошибки распознавания; независимой сверки с аудио не было. Полный просмотр, воспроизведение в клиенте игры и проверка встроенного плеера сайта не выполнены. Это не официальные инструкции; главы служат навигацией.",
    reviewed: "Дата проверки", captions: {"full-track-read": "Полная дорожка автосубтитров экспортирована; весь текст прочитан", "excerpts-read": "Полная дорожка автосубтитров экспортирована; прочитаны отдельные фрагменты", unavailable: "Экспорт субтитров не получен"},
    footage: "Выборочно просмотрены кадры источника", intro: "Только вступление", noFootage: "Кадры источника не просмотрены",
    evidenceCautions: {"wipe-estimate": "10 октября названо автором предварительной оценкой даты вайпа, а не официально подтвержденной датой.", "floating-roof": "Автор называет парящую крышу эксплойтом и ожидает исправления. Это не надежное долгосрочное руководство по строительству.", "input-overlay": "Автор поясняет: стрелка показывает положение курсора относительно центра экрана, а не непосредственное движение мыши."}
  },
  de: {
    summary: "Prüfung vom 30. September: Export und Lesen automatischer Untertitel sind von Stichproben der Originalaufnahmen getrennt. Untertitel können Fehler enthalten; kein unabhängiger Audioabgleich. Keine vollständige Sichtung, Nachstellung im Spielclient oder Prüfung des Website-Players. Keine offiziellen Anleitungen; Kapitel dienen der Navigation.",
    reviewed: "Prüfdatum", captions: {"full-track-read": "Vollständige automatische Untertitelspur exportiert; gesamten Text gelesen", "excerpts-read": "Vollständige automatische Untertitelspur exportiert; ausgewählte Passagen gelesen", unavailable: "Kein Untertitelexport erhalten"},
    footage: "Originalaufnahmen stichprobenartig gesichtet", intro: "Nur Einleitung", noFootage: "Originalaufnahmen nicht gesichtet",
    evidenceCautions: {"wipe-estimate": "Der Autor nennt den 10. Oktober als vorläufige Wipe-Schätzung, nicht als offiziell bestätigten Termin.", "floating-roof": "Der Autor nennt das schwebende Dach einen Exploit und erwartet einen Patch. Keine dauerhaft verlässliche Bauanleitung.", "input-overlay": "Laut Autor zeigt der Overlay-Pfeil die Cursorposition relativ zur Bildschirmmitte, nicht die rohe Mausbewegung."}
  },
  "pt-br": {
    summary: "Revisão de 30 de setembro: exportação e leitura de legendas automáticas estão separadas da inspeção de trechos visuais do vídeo original. As legendas podem conter erros e não foram conferidas independentemente com o áudio. Sem revisão integral do vídeo, reprodução no jogo ou verificação do player do site. Não são instruções oficiais; capítulos servem à navegação.",
    reviewed: "Data da revisão", captions: {"full-track-read": "Faixa completa de legendas automáticas exportada; texto integral lido", "excerpts-read": "Faixa completa de legendas automáticas exportada; trechos selecionados lidos", unavailable: "Exportação de legendas não obtida"},
    footage: "Trechos visuais do original inspecionados", intro: "Somente introdução", noFootage: "Imagens do original não inspecionadas",
    evidenceCautions: {"wipe-estimate": "O criador apresenta 10 de outubro como estimativa provisória do wipe, não como data oficialmente confirmada.", "floating-roof": "O criador chama o teto flutuante de exploit e espera uma correção. Não o trate como técnica de construção duradoura.", "input-overlay": "O criador explica que a seta mostra a posição do cursor em relação ao centro da tela, não o movimento bruto do mouse."}
  },
  "zh-cn": {
    summary: "9月30日复核：下方分别标明自动字幕导出、文本阅读范围和原视频画面抽查。自动字幕可能识别错误，未独立逐句对照音频；未完整观看所有视频、未在游戏客户端复现、未验证本站嵌入播放。创作者视频不是官方攻略，章节仅用于定位。",
    reviewed: "证据复核", captions: {"full-track-read": "完整自动字幕轨已导出；已阅读全文", "excerpts-read": "完整自动字幕轨已导出；仅阅读选段", unavailable: "未取得字幕导出"},
    footage: "原视频画面抽查", intro: "仅开场片段", noFootage: "未查看到原视频画面",
    evidenceCautions: {"wipe-estimate": "作者把10月10日作为暂定清档估计，不是官方确认日期。", "floating-roof": "作者自己称悬空屋顶为漏洞利用，并预计会被修复，不能当作长期有效的建造规则。", "input-overlay": "作者说明叠加箭头表示光标相对屏幕中心的位置，并非原始鼠标移动轨迹。"}
  },

  pl: {summary:"Przegląd z 30 września: poniżej rozróżniamy eksport automatycznych napisów i wybrane klatki źródłowych filmów. Napisy mogą zawierać błędy i nie zostały niezależnie porównane z dźwiękiem. Nie obejrzano całych filmów, nie odtworzono czynności w grze ani nie zweryfikowano odtwarzacza na stronie. Materiały twórców nie są oficjalnymi instrukcjami; rozdziały służą nawigacji.", reviewed:"Przegląd dowodów", captions:{"full-track-read":"Wyeksportowano pełną ścieżkę automatycznych napisów; przeczytano cały tekst", "excerpts-read":"Wyeksportowano pełną ścieżkę automatycznych napisów; przeczytano wybrane fragmenty", unavailable:"Nie uzyskano eksportu napisów"}, footage:"Sprawdzono wybrane klatki źródła", intro:"Tylko wstęp", noFootage:"Nie sprawdzono obrazu źródłowego", evidenceCautions:{"wipe-estimate":"Twórca przedstawia 10 października jako roboczą prognozę resetu, nie oficjalnie potwierdzoną datę.", "floating-roof":"Twórca nazywa unoszący się dach exploitem i oczekuje jego naprawy. Nie traktuj tego jako trwałej metody budowania.", "input-overlay":"Według twórcy strzałka nakładki pokazuje położenie kursora względem środka ekranu, a nie surowy ruch myszy."}},
  "zh-tw": {
    summary: "9月30日複核：下方分別標明自動字幕匯出、文本閱讀範圍和原影片畫面抽查。自動字幕可能識別錯誤，未獨立逐句對照音訊；未完整觀看所有影片、未在遊戲客戶端復現、未驗證本站嵌入播放。創作者影片不是官方攻略，章節僅用於定位。",
    reviewed: "證據複核", captions: { "full-track-read": "完整自動字幕軌已匯出；已閱讀全文", "excerpts-read": "完整自動字幕軌已匯出；僅閱讀選段", unavailable: "未取得字幕匯出" },
    footage: "原影片畫面抽查", intro: "僅開場片段", noFootage: "未檢視到原影片畫面",
    evidenceCautions: { "wipe-estimate": "作者把10月10日作為暫定清檔估計，不是官方確認日期。", "floating-roof": "作者自己稱懸空屋頂為漏洞利用，並預計會被修復，不能當作長期有效的建造規則。", "input-overlay": "作者說明疊加箭頭表示游標相對螢幕中心的位置，並非原始滑鼠移動軌跡。" }
}
};

export function getVideoCandidateCopy(locale: string): Copy & ReviewCopy {
  // Follow-up evidence replaces the earlier metadata-only summary in every locale.
  const supportedLocale = locale as Locale;
  return {...(copy[supportedLocale] ?? copy.en), ...(reviewCopy[supportedLocale] ?? reviewCopy.en)};
}
