const en = {
  map: "Map", zoomIn: "Zoom in", zoomOut: "Zoom out", reset: "Reset view", fullscreen: "Fullscreen", exitFullscreen: "Exit fullscreen",
  loading: "Loading map", failed: "Map could not load", retry: "Retry", search: "Search map references", empty: "No matching references",
  references: "Sourced references", unlocated: "Position not verified", manual: "Manual markers", marker: "Marker", label: "Marker name", remove: "Remove marker",
  add: "Place a manual marker", center: "Mark view center", pan: "Pan map", share: "Share view and markers", copied: "Link copied", shareLink: "Share link",
  invalid: "This map link is invalid or uses a different data version.", limit: "Maximum 16 markers per map link.",
  measurement: "Distance unavailable: this basemap has no verified scale or orientation.", measure: "Measure distance (not calibrated)",
  provenance: "Basemap source", source: "Site-owner-provided map asset, recorded 27 Sep 2026. 8 x 8 tiles stitched and re-encoded as WebP (quality 92); not a lossless original. Owner-use statement is recorded in the asset notes, not independently certified here.",
  version: "EA v0.11 / Closed Beta 02", notes: "Asset notes", privacy: "Shared markers are user annotations, not verified game locations. Names are included in the link.",
};
export type MapViewerCopy = typeof en;
const translations: Record<string, Partial<MapViewerCopy>> = {
  "zh-cn": {map: "地图", zoomIn: "放大", zoomOut: "缩小", reset: "重置视角", fullscreen: "全屏", exitFullscreen: "退出全屏", loading: "地图加载中", failed: "地图加载失败", retry: "重试", search: "搜索地图资料", empty: "没有匹配资料", references: "有来源的资料", unlocated: "位置未核实", manual: "手动标记", marker: "标记", label: "标记名称", remove: "删除标记", add: "放置手动标记", center: "标记视角中心", pan: "移动地图", share: "分享视角与标记", copied: "链接已复制", shareLink: "分享链接", invalid: "地图链接无效或数据版本不匹配。", limit: "每个地图链接最多 16 个标记。", measurement: "测距不可用：底图比例和方向尚未校准。", measure: "测距（尚未校准）", provenance: "底图来源", source: "站长提供的地图素材，记录日期为 2026-09-27。由 8×8 瓦片拼接，并以 quality=92 重编码为 WebP，并非无损原图。素材说明记录了站长的使用授权声明，此处不作独立许可认证。", notes: "素材说明", privacy: "共享标记是用户注释，不是已核实的游戏点位。名称包含在链接中。"},
  "zh-tw": {map: "地圖", zoomIn: "放大", zoomOut: "縮小", reset: "重設視角", fullscreen: "全螢幕", exitFullscreen: "退出全螢幕", loading: "地圖載入中", failed: "地圖載入失敗", retry: "重試", search: "搜尋地圖資料", empty: "沒有符合的資料", references: "有來源的資料", unlocated: "位置未核實", manual: "手動標記", marker: "標記", label: "標記名稱", remove: "刪除標記", add: "放置手動標記", center: "標記視角中心", pan: "移動地圖", share: "分享視角與標記", copied: "連結已複製", shareLink: "分享連結", invalid: "地圖連結無效或資料版本不符。", limit: "每個地圖連結最多 16 個標記。", measurement: "測距不可用：底圖比例和方向尚未校準。", measure: "測距（尚未校準）", provenance: "底圖來源", notes: "素材說明", privacy: "共享標記是使用者註記，不是已核實的遊戲位置。名稱包含在連結中。"},
  ja: {map: "マップ", zoomIn: "拡大", zoomOut: "縮小", reset: "表示をリセット", fullscreen: "全画面", exitFullscreen: "全画面を終了", loading: "マップを読み込み中", failed: "マップを読み込めません", retry: "再試行", search: "マップ資料を検索", empty: "該当する資料はありません", references: "出典付き資料", unlocated: "位置は未確認", manual: "手動マーカー", marker: "マーカー", label: "マーカー名", remove: "マーカーを削除", add: "手動マーカーを配置", center: "中心にマーカーを配置", pan: "マップを移動", share: "表示とマーカーを共有", copied: "リンクをコピーしました", shareLink: "共有リンク", invalid: "リンクが無効、またはデータのバージョンが異なります。", measurement: "距離計測は利用不可：縮尺と方角が未検証です。", measure: "距離計測（未校正）", provenance: "地図の出典", notes: "素材の記録", privacy: "共有マーカーはユーザーの注釈であり、確認済み地点ではありません。名前はリンクに含まれます。"},
  de: {map: "Karte", zoomIn: "Vergrößern", zoomOut: "Verkleinern", reset: "Ansicht zurücksetzen", fullscreen: "Vollbild", exitFullscreen: "Vollbild verlassen", loading: "Karte wird geladen", failed: "Karte konnte nicht geladen werden", retry: "Erneut versuchen", search: "Kartenquellen suchen", manual: "Eigene Markierungen", share: "Ansicht und Markierungen teilen", copied: "Link kopiert", measurement: "Entfernung nicht verfügbar: Maßstab und Ausrichtung sind nicht bestätigt."},
  ru: {map: "Карта", zoomIn: "Увеличить", zoomOut: "Уменьшить", reset: "Сбросить вид", fullscreen: "Полный экран", exitFullscreen: "Выйти из полного экрана", loading: "Загрузка карты", failed: "Не удалось загрузить карту", retry: "Повторить", search: "Поиск материалов карты", manual: "Свои метки", share: "Поделиться видом и метками", copied: "Ссылка скопирована", measurement: "Расстояние недоступно: масштаб и ориентация не проверены."},
  "pt-br": {map: "Mapa", zoomIn: "Ampliar", zoomOut: "Reduzir", reset: "Redefinir vista", fullscreen: "Tela cheia", exitFullscreen: "Sair da tela cheia", loading: "Carregando mapa", failed: "Falha ao carregar mapa", retry: "Tentar novamente", search: "Buscar referências do mapa", manual: "Marcações manuais", share: "Compartilhar vista e marcações", copied: "Link copiado", measurement: "Distância indisponível: escala e orientação não verificadas."},
  pl: {map: "Mapa", zoomIn: "Powiększ", zoomOut: "Pomniejsz", reset: "Resetuj widok", fullscreen: "Pełny ekran", exitFullscreen: "Opuść pełny ekran", loading: "Wczytywanie mapy", failed: "Nie można wczytać mapy", retry: "Ponów", search: "Szukaj informacji o mapie", manual: "Własne znaczniki", share: "Udostępnij widok i znaczniki", copied: "Link skopiowany", measurement: "Pomiar niedostępny: skala i orientacja nie są potwierdzone."},
};
export function getMapViewerCopy(locale: string): MapViewerCopy { return {...en, ...translations[locale]}; }
