import type {Locale} from "@/config/site";

const en = {
  "timingHelp": "Flight time and the timer are linear estimates, not measured impacts. Do not use them for precise synchronized volleys.",
  "shareTooLarge": "This plan is too large for a link. Use Save plan file.",
  "routeTitle": "Route planner",
  "routeHelp": "Place waypoints in order. Save or share the complete plan.",
  "clearRoute": "Clear route",
  "points": "Points",
  "total": "Route distance",
  "rangeTitle": "Fire mission",
  "rangeHelp": "Place gun, then target. The calculator uses the same map scale.",
  "clearRange": "Clear mission",
  "distance": "Distance",
  "azimuth": "Azimuth",
  "mils": "Elevation (mil)",
  "tof": "Estimated flight time",
  "waiting": "Place two points.",
  "openCalculator": "Open calculator with mission",
  "layers": "Tactical layers",
  "objectives": "Objectives",
  "fob": "FOBs",
  "supply": "Supply",
  "routes": "Routes",
  "fire-support": "Fire support",
  "air": "Air",
  "intel": "Intel",
  "kind": "Marker category",
  "focus": "Focus",
  "setGun": "Set as gun",
  "setTarget": "Set as target",
  "exportPlan": "Save plan file",
  "importPlan": "Load plan file",
  "importHelp": "Loading a file replaces the current map plan. Files and links include labels, points and calibration notes.",
  "imported": "Plan loaded.",
  "invalidFile": "Invalid plan: check file size, map version and coordinates.",
  "nominalScale": "Nominal map scale: estimate; calibrate against a known in-game distance.",
  "userScale": "User calibration is used by ruler, route and fire mission.",
  "limits": "Distances are horizontal estimates; terrain and obstructions are not modeled. Bearing assumes north is at the top.",
  "undo": "Undo point",
  "addCenter": "Place at view center",
  "community": "Community places",
  "communityHelp": "Community reference coordinates, retrieved 9 Oct 2026. Check your match: these are not live positions.",
  "tower": "Tower",
  "garage_vendor": "Garage",
  "weapons_vendor": "Weapons vendor",
  "spawn_board": "Deployment board",
  "useMarker": "Copy to my markers",
  "routePoint": "Add to route",
  "x": "X (%)",
  "y": "Y (%)",
  "closeTasks": "Close task panel",
  "outOfRange": "Outside firing table"
};
export type MapPlannerCopy = typeof en;
const copies: Record<Locale, MapPlannerCopy> = {en,
"zh-cn": {
  "timingHelp": "飞行时间和计时器为线性估算，并非实测落点时间，不可用于精确同步齐射。",
  "shareTooLarge": "此计划超过链接容量，请使用“保存计划文件”。",
  "routeTitle": "路线规划",
  "routeHelp": "依次放置途经点，可保存或分享完整计划。",
  "clearRoute": "清除路线",
  "points": "点数",
  "total": "路线距离",
  "rangeTitle": "火力任务",
  "rangeHelp": "先设炮位，再设目标；计算器沿用同一地图比例。",
  "clearRange": "清除任务",
  "distance": "距离",
  "azimuth": "方位角",
  "mils": "射角（密位）",
  "tof": "估算飞行时间",
  "waiting": "请设置两个点。",
  "openCalculator": "携带任务打开计算器",
  "layers": "战术图层",
  "objectives": "目标点",
  "fob": "前线基地",
  "supply": "补给",
  "routes": "路线",
  "fire-support": "火力支援",
  "air": "空中",
  "intel": "情报",
  "kind": "标记类别",
  "focus": "定位",
  "setGun": "设为炮位",
  "setTarget": "设为目标",
  "exportPlan": "保存计划文件",
  "importPlan": "载入计划文件",
  "importHelp": "载入会替换当前地图计划。文件和链接包含名称、坐标及校准记录。",
  "imported": "计划已载入。",
  "invalidFile": "计划无效：请检查文件大小、地图版本和坐标。",
  "nominalScale": "默认地图比例仅为估算；请用游戏内已知距离校准。",
  "userScale": "标尺、路线和火力任务统一使用用户校准比例。",
  "limits": "距离为水平估算，未计算地形和遮挡；方位角假设图片上方为北。",
  "undo": "撤销端点",
  "addCenter": "在视角中心放置",
  "community": "社区地点",
  "communityHelp": "社区参考坐标，获取于 2026 年 10 月 9 日。请对照当前对局；并非实时位置。",
  "tower": "塔台",
  "garage_vendor": "车库",
  "weapons_vendor": "武器商人",
  "spawn_board": "部署板",
  "useMarker": "复制到我的标记",
  "routePoint": "加入路线",
  "x": "X（%）",
  "y": "Y（%）",
  "closeTasks": "关闭任务面板",
  "outOfRange": "超出射表范围"
},
"zh-tw": {
  "timingHelp": "飛行時間和計時器為線性估算，並非實測落點時間，不可用於精確同步齊射。",
  "shareTooLarge": "此計畫超過連結容量，請使用「儲存計畫檔案」。",
  "routeTitle": "路線規劃",
  "routeHelp": "依序放置途經點，可儲存或分享完整計畫。",
  "clearRoute": "清除路線",
  "points": "點數",
  "total": "路線距離",
  "rangeTitle": "火力任務",
  "rangeHelp": "先設砲位，再設目標；計算器沿用同一地圖比例。",
  "clearRange": "清除任務",
  "distance": "距離",
  "azimuth": "方位角",
  "mils": "射角（密位）",
  "tof": "估算飛行時間",
  "waiting": "請設定兩個點。",
  "openCalculator": "攜帶任務開啟計算器",
  "layers": "戰術圖層",
  "objectives": "目標點",
  "fob": "前線基地",
  "supply": "補給",
  "routes": "路線",
  "fire-support": "火力支援",
  "air": "空中",
  "intel": "情報",
  "kind": "標記類別",
  "focus": "定位",
  "setGun": "設為砲位",
  "setTarget": "設為目標",
  "exportPlan": "儲存計畫檔案",
  "importPlan": "載入計畫檔案",
  "importHelp": "載入會取代目前地圖計畫。檔案和連結包含名稱、座標及校準紀錄。",
  "imported": "計畫已載入。",
  "invalidFile": "計畫無效：請檢查檔案大小、地圖版本和座標。",
  "nominalScale": "預設地圖比例僅為估算；請用遊戲內已知距離校準。",
  "userScale": "標尺、路線和火力任務統一使用使用者校準比例。",
  "limits": "距離為水平估算，未計算地形和遮擋；方位角假設圖片上方為北。",
  "undo": "復原端點",
  "addCenter": "在視角中心放置",
  "community": "社群地點",
  "communityHelp": "社群參考座標，取得於 2026 年 10 月 9 日。請對照目前對局；並非即時位置。",
  "tower": "塔台",
  "garage_vendor": "車庫",
  "weapons_vendor": "武器商人",
  "spawn_board": "部署板",
  "useMarker": "複製到我的標記",
  "routePoint": "加入路線",
  "x": "X（%）",
  "y": "Y（%）",
  "closeTasks": "關閉任務面板",
  "outOfRange": "超出射表範圍"
},
"ja": {
  "timingHelp": "飛翔時間とタイマーは線形推定で、実測した着弾時刻ではありません。精密な同時着弾射撃には使用できません。",
  "shareTooLarge": "この計画はリンクの上限を超えています。計画ファイルを保存してください。",
  "routeTitle": "経路計画",
  "routeHelp": "通過点を順に配置し、計画を保存・共有します。",
  "clearRoute": "経路を消去",
  "points": "地点数",
  "total": "経路の距離",
  "rangeTitle": "射撃任務",
  "rangeHelp": "砲位置、目標の順に配置。計算機も同じ縮尺を使います。",
  "clearRange": "任務を消去",
  "distance": "距離",
  "azimuth": "方位角",
  "mils": "仰角（ミル）",
  "tof": "推定飛翔時間",
  "waiting": "2点を設定してください。",
  "openCalculator": "任務を計算機で開く",
  "layers": "戦術レイヤー",
  "objectives": "目標地点",
  "fob": "前線基地",
  "supply": "補給",
  "routes": "経路",
  "fire-support": "火力支援",
  "air": "航空",
  "intel": "情報",
  "kind": "マーカー分類",
  "focus": "位置を表示",
  "setGun": "砲位置に設定",
  "setTarget": "目標に設定",
  "exportPlan": "計画ファイルを保存",
  "importPlan": "計画ファイルを読込",
  "importHelp": "読み込みで現在の計画を置き換えます。ファイルとリンクには名称・座標・校正メモが含まれます。",
  "imported": "計画を読み込みました。",
  "invalidFile": "無効な計画：サイズ・マップの版・座標を確認してください。",
  "nominalScale": "既定の縮尺は推定値です。ゲーム内の既知の距離で校正してください。",
  "userScale": "定規・経路・射撃任務は同じユーザー校正を使用します。",
  "limits": "水平距離の推定値です。地形・遮蔽物は未計算。画像の上が北と仮定します。",
  "undo": "直前の点を戻す",
  "addCenter": "表示の中心に配置",
  "community": "コミュニティ地点",
  "communityHelp": "2026年10月9日取得のコミュニティ参考座標。現在の試合で確認してください。ライブ位置情報ではありません。",
  "tower": "タワー",
  "garage_vendor": "ガレージ",
  "weapons_vendor": "武器商人",
  "spawn_board": "出撃ボード",
  "useMarker": "自分のマーカーに追加",
  "routePoint": "経路に追加",
  "x": "X（%）",
  "y": "Y（%）",
  "closeTasks": "作業パネルを閉じる",
  "outOfRange": "射表の範囲外"
},
"de": {
  "timingHelp": "Flugzeit und Timer sind lineare Schätzungen, keine gemessenen Einschlagzeiten. Nicht für präzise synchronisierte Salven verwenden.",
  "shareTooLarge": "Dieser Plan ist zu groß für einen Link. Als Datei speichern.",
  "routeTitle": "Routenplaner",
  "routeHelp": "Wegpunkte der Reihe nach setzen. Den gesamten Plan speichern oder teilen.",
  "clearRoute": "Route löschen",
  "points": "Punkte",
  "total": "Routenlänge",
  "rangeTitle": "Feuerauftrag",
  "rangeHelp": "Geschütz und dann Ziel setzen. Der Rechner nutzt denselben Maßstab.",
  "clearRange": "Auftrag löschen",
  "distance": "Entfernung",
  "azimuth": "Azimut",
  "mils": "Erhöhung (mil)",
  "tof": "Geschätzte Flugzeit",
  "waiting": "Zwei Punkte setzen.",
  "openCalculator": "Auftrag im Rechner öffnen",
  "layers": "Taktische Ebenen",
  "objectives": "Ziele",
  "fob": "Feldbasen",
  "supply": "Versorgung",
  "routes": "Routen",
  "fire-support": "Feuerunterstützung",
  "air": "Luft",
  "intel": "Aufklärung",
  "kind": "Markierungstyp",
  "focus": "Anzeigen",
  "setGun": "Als Geschütz setzen",
  "setTarget": "Als Ziel setzen",
  "exportPlan": "Plan speichern",
  "importPlan": "Plan laden",
  "importHelp": "Laden ersetzt den aktuellen Plan. Dateien und Links enthalten Namen, Punkte und Kalibriernotizen.",
  "imported": "Plan geladen.",
  "invalidFile": "Ungültiger Plan: Größe, Kartenversion und Koordinaten prüfen.",
  "nominalScale": "Nomineller Maßstab: Schätzung. An einer bekannten Entfernung im Spiel kalibrieren.",
  "userScale": "Lineal, Route und Feuerauftrag nutzen dieselbe Nutzerkalibrierung.",
  "limits": "Horizontale Schätzwerte ohne Gelände oder Hindernisse. Norden wird oben angenommen.",
  "undo": "Punkt zurücknehmen",
  "addCenter": "In Ansichtsmitte setzen",
  "community": "Community-Orte",
  "communityHelp": "Community-Referenzkoordinaten vom 9. Oktober 2026. Im eigenen Match prüfen; keine Live-Positionen.",
  "tower": "Turm",
  "garage_vendor": "Garage",
  "weapons_vendor": "Waffenhändler",
  "spawn_board": "Einsatztafel",
  "useMarker": "Zu meinen Markierungen",
  "routePoint": "Zur Route hinzufügen",
  "x": "X (%)",
  "y": "Y (%)",
  "closeTasks": "Auftragsbereich schließen",
  "outOfRange": "Außerhalb der Schusstafel"
},
"ru": {
  "timingHelp": "Время полёта и таймер — линейные оценки, а не измеренное время попадания. Не используйте их для точной синхронизации залпов.",
  "shareTooLarge": "План слишком велик для ссылки. Сохраните файл плана.",
  "routeTitle": "Планировщик маршрута",
  "routeHelp": "Размещайте точки по порядку. Сохраните или передайте весь план.",
  "clearRoute": "Очистить маршрут",
  "points": "Точки",
  "total": "Длина маршрута",
  "rangeTitle": "Огневая задача",
  "rangeHelp": "Укажите орудие, затем цель. Калькулятор использует тот же масштаб.",
  "clearRange": "Очистить задачу",
  "distance": "Дальность",
  "azimuth": "Азимут",
  "mils": "Угол (мил)",
  "tof": "Расчётное время полёта",
  "waiting": "Укажите две точки.",
  "openCalculator": "Открыть задачу в калькуляторе",
  "layers": "Тактические слои",
  "objectives": "Объекты",
  "fob": "Передовые базы",
  "supply": "Снабжение",
  "routes": "Маршруты",
  "fire-support": "Огневая поддержка",
  "air": "Авиация",
  "intel": "Разведка",
  "kind": "Тип отметки",
  "focus": "Показать",
  "setGun": "Позиция орудия",
  "setTarget": "Назначить целью",
  "exportPlan": "Сохранить файл плана",
  "importPlan": "Загрузить файл плана",
  "importHelp": "Загрузка заменяет текущий план. Файлы и ссылки содержат подписи, точки и записи калибровки.",
  "imported": "План загружен.",
  "invalidFile": "Неверный план: проверьте размер, версию карты и координаты.",
  "nominalScale": "Номинальный масштаб даёт оценку. Откалибруйте по известному расстоянию в игре.",
  "userScale": "Линейка, маршрут и огневая задача используют общую калибровку пользователя.",
  "limits": "Горизонтальная оценка без рельефа и препятствий. Север принят сверху.",
  "undo": "Отменить точку",
  "addCenter": "Поставить в центре вида",
  "community": "Места сообщества",
  "communityHelp": "Справочные координаты сообщества, получены 9 октября 2026 г. Проверяйте в своём матче; это не данные в реальном времени.",
  "tower": "Вышка",
  "garage_vendor": "Гараж",
  "weapons_vendor": "Торговец оружием",
  "spawn_board": "Доска высадки",
  "useMarker": "В мои отметки",
  "routePoint": "Добавить в маршрут",
  "x": "X (%)",
  "y": "Y (%)",
  "closeTasks": "Закрыть панель задачи",
  "outOfRange": "За пределами таблицы стрельбы"
},
"pt-br": {
  "timingHelp": "O tempo de voo e o cronômetro são estimativas lineares, não tempos de impacto medidos. Não use para sincronizar salvas com precisão.",
  "shareTooLarge": "O plano é grande demais para um link. Salve o arquivo do plano.",
  "routeTitle": "Planejador de rotas",
  "routeHelp": "Marque os pontos em ordem. Salve ou compartilhe o plano completo.",
  "clearRoute": "Limpar rota",
  "points": "Pontos",
  "total": "Distância da rota",
  "rangeTitle": "Missão de tiro",
  "rangeHelp": "Marque a arma e depois o alvo. A calculadora usa a mesma escala.",
  "clearRange": "Limpar missão",
  "distance": "Distância",
  "azimuth": "Azimute",
  "mils": "Elevação (mil)",
  "tof": "Tempo de voo estimado",
  "waiting": "Marque dois pontos.",
  "openCalculator": "Abrir missão na calculadora",
  "layers": "Camadas táticas",
  "objectives": "Objetivos",
  "fob": "Bases avançadas",
  "supply": "Suprimentos",
  "routes": "Rotas",
  "fire-support": "Apoio de fogo",
  "air": "Aéreo",
  "intel": "Informações",
  "kind": "Categoria do marcador",
  "focus": "Localizar",
  "setGun": "Definir como arma",
  "setTarget": "Definir como alvo",
  "exportPlan": "Salvar arquivo do plano",
  "importPlan": "Carregar arquivo do plano",
  "importHelp": "O arquivo substitui o plano atual. Arquivos e links incluem nomes, pontos e notas de calibração.",
  "imported": "Plano carregado.",
  "invalidFile": "Plano inválido: confira tamanho, versão do mapa e coordenadas.",
  "nominalScale": "Escala nominal: estimativa. Calibre com uma distância conhecida no jogo.",
  "userScale": "Régua, rota e missão usam a mesma calibração do usuário.",
  "limits": "Estimativas horizontais sem relevo ou obstáculos. Considera-se o norte no topo.",
  "undo": "Desfazer ponto",
  "addCenter": "Marcar no centro da vista",
  "community": "Locais da comunidade",
  "communityHelp": "Coordenadas de referência da comunidade, obtidas em 9 de outubro de 2026. Confira na partida; não são posições ao vivo.",
  "tower": "Torre",
  "garage_vendor": "Garagem",
  "weapons_vendor": "Vendedor de armas",
  "spawn_board": "Quadro de implantação",
  "useMarker": "Copiar para meus marcadores",
  "routePoint": "Adicionar à rota",
  "x": "X (%)",
  "y": "Y (%)",
  "closeTasks": "Fechar painel da missão",
  "outOfRange": "Fora da tabela de tiro"
},
"pl": {
  "timingHelp": "Czas lotu i licznik są liniowymi szacunkami, nie zmierzonym czasem trafienia. Nie używaj ich do precyzyjnej synchronizacji salw.",
  "shareTooLarge": "Plan jest zbyt duży dla linku. Zapisz plik planu.",
  "routeTitle": "Planer trasy",
  "routeHelp": "Ustaw punkty po kolei. Zapisz lub udostępnij cały plan.",
  "clearRoute": "Wyczyść trasę",
  "points": "Punkty",
  "total": "Długość trasy",
  "rangeTitle": "Zadanie ogniowe",
  "rangeHelp": "Ustaw działo, następnie cel. Kalkulator używa tej samej skali.",
  "clearRange": "Wyczyść zadanie",
  "distance": "Odległość",
  "azimuth": "Azymut",
  "mils": "Podniesienie (mil)",
  "tof": "Szacowany czas lotu",
  "waiting": "Ustaw dwa punkty.",
  "openCalculator": "Otwórz zadanie w kalkulatorze",
  "layers": "Warstwy taktyczne",
  "objectives": "Cele",
  "fob": "Bazy polowe",
  "supply": "Zaopatrzenie",
  "routes": "Trasy",
  "fire-support": "Wsparcie ogniowe",
  "air": "Lotnictwo",
  "intel": "Rozpoznanie",
  "kind": "Rodzaj znacznika",
  "focus": "Pokaż",
  "setGun": "Ustaw jako działo",
  "setTarget": "Ustaw jako cel",
  "exportPlan": "Zapisz plik planu",
  "importPlan": "Wczytaj plik planu",
  "importHelp": "Wczytanie zastępuje bieżący plan. Pliki i linki zawierają nazwy, punkty i notatki kalibracji.",
  "imported": "Plan wczytany.",
  "invalidFile": "Nieprawidłowy plan: sprawdź rozmiar, wersję mapy i współrzędne.",
  "nominalScale": "Skala nominalna to szacunek. Skalibruj według znanej odległości w grze.",
  "userScale": "Linijka, trasa i zadanie używają jednej kalibracji użytkownika.",
  "limits": "Szacowane odległości poziome bez terenu i przeszkód. Północ jest przyjęta u góry.",
  "undo": "Cofnij punkt",
  "addCenter": "Ustaw w środku widoku",
  "community": "Miejsca społeczności",
  "communityHelp": "Referencyjne współrzędne społeczności z 9 października 2026 r. Sprawdź w swoim meczu; to nie pozycje na żywo.",
  "tower": "Wieża",
  "garage_vendor": "Garaż",
  "weapons_vendor": "Handlarz bronią",
  "spawn_board": "Tablica rozmieszczenia",
  "useMarker": "Do moich znaczników",
  "routePoint": "Dodaj do trasy",
  "x": "X (%)",
  "y": "Y (%)",
  "closeTasks": "Zamknij panel zadania",
  "outOfRange": "Poza tabelą strzelania"
},
};
export function getMapPlannerCopy(locale: string): MapPlannerCopy {return copies[locale as Locale] ?? en;}
