import type {Locale} from "@/config/site";
import {publicRoutePath} from "@/lib/public-url";

type BudgetCopy = {title: string; intro: string; steps: readonly string[]; headings: readonly [string, string]; rows: readonly (readonly [string, string])[]; example: string; budget: string; wipe: string};
const copy: Record<Locale, BudgetCopy> = {
  en: {title: "Turn a cosmetic goal into a cash budget", intro: "A price complaint cannot tell you whether your next purchase is affordable. Use the offer displayed in your own client, after protecting the sessions you still want to play.", steps: ["Record the chosen cosmetic's Gold price and your owned Gold. Missing Gold is the target minus owned Gold, with no shortfall if you already have enough.", "Reserve cash for planned kits, unpaid unlocks and needed transport; a lost kit's old purchase price is not charged twice.", "Read the current offer for a supported exchange quantity. Record its cash cost, Gold received, date, timezone and build; do not infer an unlimited linear rate.", "Compare cash left after that offer with your reserve, then confirm only if you still want the cosmetic. Keep the completed transaction record."], headings: ["Your position", "Decision"], rows: [["Enough Gold already", "No cash conversion is needed for this target; decide whether you value the cosmetic or prefer saving Gold."], ["Gold shortfall fits spare cash", "Compare the actual offer and purchase quantity, then preserve the session reserve."], ["The exchange would consume kit money", "Delay the cosmetic or reduce optional gear; higher-risk spending does not guarantee faster earnings."]], example: "Quantity example only: target 120 Gold, owned 95, shortfall 25. Read the current offer for that gap if supported; use the displayed lot if another quantity is offered. This is not a live price or a forecast for wipe day.", budget: "Check kit and replacement costs", wipe: "Plan spending before the wipe"},
  de: {title: "Kosmetikziel in ein Geldbudget übersetzen", intro: "Eine Preisbeschwerde zeigt nicht, ob dein nächster Kauf bezahlbar ist. Nutze das Angebot im eigenen Spiel und sichere zuerst die geplanten Sitzungen.", steps: ["Goldpreis des gewünschten Gegenstands und eigenes Gold notieren. Fehlmenge = Ziel minus Bestand; bei ausreichendem Bestand gibt es keine Lücke.", "Geld für Sets, unbezahlte Freischaltungen und nötigen Transport reservieren. Verlorene Ausrüstung wird nicht ein zweites Mal bezahlt.", "Aktuelles Angebot für eine unterstützte Tauschmenge lesen. Geldbedarf, erhaltenes Gold, Datum, Zeitzone und Build festhalten; keinen unbegrenzt linearen Kurs annehmen.", "Restgeld nach dem Angebot mit der Reserve vergleichen. Nur bestätigen, wenn du das Ziel weiterhin willst; abgeschlossene Transaktion sichern."], headings: ["Deine Lage", "Entscheidung"], rows: [["Gold reicht bereits", "Für dieses Ziel ist kein Geldtausch nötig. Kosmetikwert gegen weiteres Sparen abwägen."], ["Fehlendes Gold passt zum Überschuss", "Tatsächliches Angebot und Menge prüfen und Spielreserve behalten."], ["Tausch würde Ausrüstungsgeld verbrauchen", "Kosmetik verschieben oder optionale Ausrüstung kürzen; riskantere Ausgaben garantieren keinen schnelleren Gewinn."]], example: "Nur Mengenbeispiel: Ziel 120 Gold, Bestand 95, Lücke 25. Falls unterstützt, Angebot für diese Menge lesen; andernfalls angezeigtes Paket verwenden. Kein Live-Preis und keine Wipe-Prognose.", budget: "Set- und Ersatzkosten prüfen", wipe: "Ausgaben vor dem Wipe planen"},
  ru: {title: "Превратите цель в косметике в денежный бюджет", intro: "Жалоба на цену не определяет доступность вашей покупки. Смотрите предложение своего клиента, сначала обеспечив оставшиеся игровые сессии.", steps: ["Запишите цену выбранной косметики и своё золото. Недостающее количество — цель минус запас; при достаточном запасе дефицита нет.", "Оставьте деньги на комплекты, неоплаченные открытия и транспорт. Потеря купленного комплекта не списывает его цену повторно.", "Прочтите предложение для доступного объёма обмена. Запишите стоимость, получаемое золото, дату, пояс и сборку; не выводите бесконечно линейный курс.", "Сравните остаток денег после сделки с резервом и подтвердите, только если покупка всё ещё нужна. Сохраните результат операции."], headings: ["Ваше положение", "Решение"], rows: [["Золота уже хватает", "Для этой цели обмен не нужен. Решите, важнее косметика или сохранение золота."], ["Дефицит покрывается свободными деньгами", "Проверьте предложение и объём, сохранив резерв сессий."], ["Обмен заберёт деньги на комплекты", "Отложите косметику или сократите необязательное снаряжение; риск не гарантирует быстрого дохода."]], example: "Только пример количества: цель 120 Gold, запас 95, не хватает 25. Если такой объём доступен, прочтите предложение; иначе используйте показанный пакет. Это не текущая цена и не прогноз курса вайпа.", budget: "Проверить стоимость комплектов и замены", wipe: "Спланировать расходы перед вайпом"},
  "pt-br": {title: "Transforme a meta de cosmético em orçamento", intro: "Uma reclamação de preço não mostra se sua compra cabe no bolso. Use a oferta do seu cliente e garanta primeiro as sessões que ainda quer jogar.", steps: ["Anote o preço do cosmético em Gold e o saldo que possui. Falta = meta menos saldo; se já tem o suficiente, não há diferença a cobrir.", "Reserve dinheiro para kits, desbloqueios não pagos e transporte necessário. Perder um kit já comprado não cobra o preço outra vez.", "Leia a oferta atual para uma quantidade aceita na troca. Registre custo, Gold recebido, data, fuso e build; não presuma taxa linear ilimitada.", "Compare o saldo após a oferta com a reserva e só confirme se ainda quiser o cosmético. Guarde o registro concluído."], headings: ["Sua situação", "Decisão"], rows: [["Já tem Gold suficiente", "Não precisa converter dinheiro para essa meta; escolha entre o cosmético e guardar Gold."], ["O Gold que falta cabe na sobra", "Compare oferta e quantidade reais e preserve a reserva das sessões."], ["A troca consumiria dinheiro dos kits", "Adie o cosmético ou reduza itens opcionais; aumentar o risco não garante lucro mais rápido."]], example: "Exemplo apenas de quantidade: meta 120 Gold, saldo 95, falta 25. Consulte a oferta dessa diferença se aceita; caso contrário, use o lote exibido. Não é cotação ao vivo nem previsão para o wipe.", budget: "Conferir kits e reposições", wipe: "Planejar gastos antes do wipe"},
  ja: {title: "コスメ目標を現金予算に落とし込む", intro: "価格への不満だけでは自分が買えるか判断できません。残りのプレイ予算を確保したうえで、自分のゲーム画面の見積もりを使います。", steps: ["欲しい品のGold価格と所有Goldを記録。不足は目標−所有分で、すでに足りていれば追加交換は不要です。", "装備、未払いの解除、必要な輸送の現金を確保します。購入済み装備の損失で元の価格を二重計上しません。", "対応する交換数量の現在の見積もりを確認。現金支出・受取Gold・日時・時間帯・ビルドを残し、無制限の比例レートは想定しません。", "交換後の残高を予備資金と比較し、まだ欲しい場合のみ確定。取引完了の記録を保存します。"], headings: ["状態", "判断"], rows: [["Goldはすでに足りている", "この目標のための現金交換は不要。コスメを買うかGoldを残すか選びます。"], ["不足分は余剰現金で補える", "実際の提示量と費用を比較し、プレイ用の予備資金を守ります。"], ["交換すると装備代まで使う", "コスメを延期するか任意装備を減らします。高リスクな出費が収益を早めるとは限りません。"]], example: "数量だけの例：目標120 Gold、所有95、不足25。対応していれば不足分の見積もりを読み、別の単位なら画面の総量を使います。現在価格やワイプ当日の相場予測ではありません。", budget: "装備と買い直し費用を確認", wipe: "ワイプ前の支出計画"},
  "zh-cn": {title: "把外观目标变成可执行的现金预算", intro: "别人抱怨贵，并不能判断你下一笔买不买得起。先保障还想玩的场次，再使用自己客户端里的实际报价。", steps: ["记录目标外观的Gold价格和已有金条。缺口为目标减持有量；已经够用时无需补充。", "为可用装备、未付解锁和必要运输留现金。已购装备丢失不能把原价再算一次支出。", "读取交易支持数量的当下报价，记录现金成本、得到的Gold、日期、时区和版本；不假定无限线性的兑换率。", "比较兑换后余额与备用金，只在仍想要该外观时确认，并保存成功交易记录。"], headings: ["你的情况", "怎么决定"], rows: [["已有金条足够", "这个目标无需再兑换现金；选择买外观，或继续保存Gold。"], ["金条缺口在余款范围内", "核对实际报价与交易数量，保住剩余场次备用金。"], ["兑换会用掉装备费", "延后外观或削减非必要装备；冒更大风险并不保证赚得更快。"]], example: "仅作数量示例：目标120 Gold，已有95，缺25。交易支持时读取补足缺口的报价；若只提供其他档位，就使用界面显示的总量。这不是实时报价，也不是删档当天预测。", budget: "检查出装与重购成本", wipe: "安排删档前的花费"},
  "zh-tw": {title: "把外觀目標轉成可執行的現金預算", intro: "別人覺得太貴，無法判斷你下一筆是否買得起。先保障還想玩的場次，再使用自己遊戲畫面上的實際報價。", steps: ["記錄目標外觀的Gold價格及已有金條。缺口是目標減持有量；已經足夠就不需補充。", "為可用裝備、未付解鎖及必要運輸保留現金。已購裝備遺失不能再把原價列為支出。", "讀取交易支援數量的當下報價，記錄現金成本、取得的Gold、日期、時區及版本；不假定無限線性的兌換率。", "比較兌換後餘額與備用金，只在仍想要該外觀時確認，並保留成功交易紀錄。"], headings: ["你的情況", "如何決定"], rows: [["已有金條足夠", "這個目標不需再兌換現金；選擇購買外觀，或繼續保存Gold。"], ["金條缺口在餘款範圍內", "核對實際報價及交易數量，保住剩餘場次備用金。"], ["兌換會占用裝備費", "延後外觀或刪減非必要裝備；冒更大風險不保證賺得更快。"]], example: "僅供數量示範：目標120 Gold，已有95，缺25。交易支援時讀取補齊缺口的報價；若只提供其他級距，使用介面顯示的總量。這不是即時報價，也不是重置當天的預測。", budget: "檢查配裝與重購成本", wipe: "安排重置前的支出"},
  pl: {title: "Zamień cel kosmetyczny w budżet gotówkowy", intro: "Narzekanie na cenę nie określa, czy stać cię na zakup. Użyj oferty ze swojego klienta, najpierw zabezpieczając planowane sesje.", steps: ["Zapisz cenę kosmetyku w Gold i posiadane złoto. Brak to cel minus zapas; jeśli już wystarcza, nie trzeba uzupełnienia.", "Odłóż gotówkę na zestawy, nieopłacone odblokowania i potrzebny transport. Utrata kupionego zestawu nie nalicza jego ceny ponownie.", "Odczytaj bieżącą ofertę obsługiwanej ilości. Zapisz koszt, otrzymane Gold, datę, strefę i wersję; nie zakładaj nieograniczonego liniowego kursu.", "Porównaj gotówkę po ofercie z rezerwą i potwierdź tylko, jeśli nadal chcesz kosmetyku. Zachowaj zapis ukończonej transakcji."], headings: ["Twoja sytuacja", "Decyzja"], rows: [["Gold już wystarcza", "Do tego celu nie potrzeba wymiany gotówki. Wybierz kosmetyk albo dalsze oszczędzanie."], ["Brakujące Gold mieści się w nadwyżce", "Sprawdź rzeczywistą ofertę i ilość, zachowując rezerwę sesji."], ["Wymiana zużyje środki na zestawy", "Odłóż kosmetyk lub ogranicz opcjonalny sprzęt; większe ryzyko nie gwarantuje szybszego zarobku."]], example: "Tylko przykład ilości: cel 120 Gold, zapas 95, brak 25. Odczytaj ofertę tej ilości, jeśli jest obsługiwana; inaczej użyj pokazanego pakietu. To nie bieżąca cena ani prognoza resetu.", budget: "Sprawdź koszt zestawów i wymiany", wipe: "Zaplanuj wydatki przed resetem"}
};
export function getGoldBudgetCopy(locale: Locale) {return copy[locale];}
export function GoldBudgetPanel({locale}: {locale: Locale}) {
  const c = copy[locale];
  return <section className="mt-12 border-t border-[#354039] pt-8" aria-labelledby="gold-target-budget">
    <h2 id="gold-target-budget" className="display-font text-3xl text-white">{c.title}</h2>
    <p className="mt-3 text-sm leading-7 text-[#b6c2ba]">{c.intro}</p>
    <ol className="mt-5 list-decimal space-y-3 pl-5 text-sm leading-7 text-[#c3cec6]">{c.steps.map(step => <li key={step}>{step}</li>)}</ol>
    <div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm leading-6"><thead><tr>{c.headings.map(heading => <th className="border-b border-[#465149] px-3 py-3 text-[#79d19c]" key={heading}>{heading}</th>)}</tr></thead><tbody>{c.rows.map(([state, decision]) => <tr key={state}><th className="border-b border-[#354039] px-3 py-3 font-medium text-white" scope="row">{state}</th><td className="border-b border-[#354039] px-3 py-3 text-[#b6c2ba]">{decision}</td></tr>)}</tbody></table></div>
    <p className="mt-4 text-sm leading-7 text-[#b6c2ba]">{c.example}</p>
    <div className="mt-5 flex flex-wrap gap-5 text-sm font-semibold text-[#79d19c]"><a title={c.budget} href={publicRoutePath(`/${locale}/tools/loadout-budget`)}>{c.budget} →</a><a title={c.wipe} href={publicRoutePath(`/${locale}/guides/wardogs-what-to-buy-before-wipe`)}>{c.wipe} →</a></div>
  </section>;
}
