import type {Locale} from "@/config/site";

export type DiagnosticRecordKind = "performance" | "connection" | "linux";
const copy = {
  "en": {
    "copy": "Copy blank record",
    "copied": "Record copied",
    "failed": "Copy failed; select the text below.",
    "performance": "Performance comparison: A → B → A",
    "connection": "Connection handoff record",
    "linux": "Linux / Proton stage record",
    "labels": [
      "Date / timezone",
      "Game build",
      "OS / kernel / GPU driver",
      "CPU / GPU / RAM",
      "Resolution / render scale / preset",
      "Server / region / map / role",
      "Route / duration / minutes since launch",
      "A: original setting / FPS / frametime spikes / ping",
      "B: one changed setting / same measurements",
      "A again: restored setting / same measurements",
      "Result: keep or restore / reason",
      "Exact on-screen stage / queue position",
      "Responsive / progressing / process still running",
      "Selected filters / refreshed once / outcome",
      "Main game or Playtest / game updated / account access",
      "Last successful step / exact error / screenshot time",
      "Action already tried / before and after result",
      "Proton exact version / launch options",
      "Native / process starts / menu / join / full match / reconnect",
      "SteamOS / input layout / resolution / sustained performance",
      "Other variables changed / not measured"
    ]
  },
  "ja": {
    "copy": "空の記録をコピー",
    "copied": "記録をコピーしました",
    "failed": "コピーできません。下のテキストを選択してください。",
    "performance": "性能比較：A → B → A",
    "connection": "接続問題の引き継ぎ記録",
    "linux": "Linux / Proton の段階別記録",
    "labels": [
      "日時・タイムゾーン",
      "ゲームビルド",
      "OS・カーネル・GPU ドライバー",
      "CPU・GPU・RAM",
      "解像度・描画倍率・プリセット",
      "サーバー・地域・マップ・役割",
      "経路・時間・起動後の経過時間",
      "A：元の設定・FPS・フレーム時間の跳ね・ping",
      "B：変更した設定一つ・同じ測定項目",
      "A 再試験：元に戻した設定・同じ測定項目",
      "判断：維持または元に戻す・理由",
      "画面の段階・待機列の位置",
      "入力に反応するか・進行するか・プロセスが残るか",
      "選択フィルター・一度更新した結果",
      "製品版か Playtest か・更新状況・アカウントの利用権",
      "最後に成功した段階・正確なエラー・画像の時刻",
      "実施済みの操作・前後の結果",
      "正確な Proton バージョン・起動オプション",
      "ネイティブ・プロセス開始・メニュー・参加・試合完了・再接続",
      "SteamOS・操作配置・解像度・継続的な性能",
      "ほかに変わった条件・未測定項目"
    ]
  },
  "de": {
    "copy": "Leeres Protokoll kopieren",
    "copied": "Protokoll kopiert",
    "failed": "Kopieren fehlgeschlagen; Text unten auswählen.",
    "performance": "Leistungsvergleich: A → B → A",
    "connection": "Protokoll für Verbindungsprobleme",
    "linux": "Linux-/Proton-Prüfprotokoll",
    "labels": [
      "Datum / Zeitzone",
      "Spielbuild",
      "OS / Kernel / GPU-Treiber",
      "CPU / GPU / RAM",
      "Auflösung / Renderskalierung / Preset",
      "Server / Region / Karte / Rolle",
      "Route / Dauer / Minuten seit Start",
      "A: Originaleinstellung / FPS / Frametime-Spitzen / Ping",
      "B: eine geänderte Einstellung / gleiche Messwerte",
      "A erneut: wiederhergestellte Einstellung / gleiche Messwerte",
      "Ergebnis: behalten oder zurückstellen / Grund",
      "Genauer Bildschirmzustand / Warteschlangenplatz",
      "Reagiert / macht Fortschritt / Prozess läuft weiter",
      "Gewählte Filter / einmal aktualisiert / Ergebnis",
      "Hauptspiel oder Playtest / aktualisiert / Kontozugang",
      "Letzter erfolgreicher Schritt / exakter Fehler / Screenshotzeit",
      "Bereits versuchte Aktion / Ergebnis vorher und nachher",
      "Exakte Proton-Version / Startoptionen",
      "Nativ / Prozessstart / Menü / Beitritt / vollständiges Match / Wiederverbindung",
      "SteamOS / Eingabebelegung / Auflösung / anhaltende Leistung",
      "Andere geänderte Variablen / nicht gemessen"
    ]
  },
  "ru": {
    "copy": "Скопировать пустой бланк",
    "copied": "Бланк скопирован",
    "failed": "Не удалось скопировать; выделите текст ниже.",
    "performance": "Сравнение производительности: A → B → A",
    "connection": "Отчёт о подключении для поддержки",
    "linux": "Проверка этапов Linux / Proton",
    "labels": [
      "Дата / часовой пояс",
      "Сборка игры",
      "ОС / ядро / драйвер GPU",
      "CPU / GPU / RAM",
      "Разрешение / масштаб рендера / пресет",
      "Сервер / регион / карта / роль",
      "Маршрут / длительность / минуты после запуска",
      "A: исходная настройка / FPS / скачки времени кадра / пинг",
      "B: одна изменённая настройка / те же измерения",
      "Снова A: восстановленная настройка / те же измерения",
      "Итог: оставить или вернуть / причина",
      "Точный экран / позиция в очереди",
      "Реагирует / продвигается / процесс ещё работает",
      "Выбранные фильтры / одно обновление / результат",
      "Основная игра или Playtest / обновление / доступ аккаунта",
      "Последний успешный шаг / точная ошибка / время снимка",
      "Что уже пробовали / результат до и после",
      "Точная версия Proton / параметры запуска",
      "Нативный / старт процесса / меню / вход / полный матч / переподключение",
      "SteamOS / раскладка ввода / разрешение / длительная производительность",
      "Другие изменённые условия / не измерено"
    ]
  },
  "pt-br": {
    "copy": "Copiar registro em branco",
    "copied": "Registro copiado",
    "failed": "Não foi possível copiar; selecione o texto abaixo.",
    "performance": "Comparação de desempenho: A → B → A",
    "connection": "Registro de conexão para suporte",
    "linux": "Registro de etapas Linux / Proton",
    "labels": [
      "Data / fuso horário",
      "Build do jogo",
      "OS / kernel / driver da GPU",
      "CPU / GPU / RAM",
      "Resolução / escala de renderização / preset",
      "Servidor / região / mapa / função",
      "Rota / duração / minutos desde o início",
      "A: ajuste original / FPS / picos de tempo de quadro / ping",
      "B: um ajuste alterado / mesmas medições",
      "A novamente: ajuste restaurado / mesmas medições",
      "Resultado: manter ou restaurar / motivo",
      "Tela exata / posição na fila",
      "Responde / avança / processo ainda aberto",
      "Filtros selecionados / uma atualização / resultado",
      "Jogo principal ou Playtest / atualizado / acesso da conta",
      "Última etapa concluída / erro exato / horário da captura",
      "Ação já tentada / resultado antes e depois",
      "Versão exata do Proton / opções de inicialização",
      "Nativo / processo inicia / menu / entrada / partida completa / reconexão",
      "SteamOS / controles / resolução / desempenho sustentado",
      "Outras variáveis alteradas / não medido"
    ]
  },
  "zh-cn": {
    "copy": "复制空白记录",
    "copied": "记录已复制",
    "failed": "复制失败，请选中下方文字。",
    "performance": "性能对照：A → B → A",
    "connection": "连接故障交接记录",
    "linux": "Linux / Proton 分阶段记录",
    "labels": [
      "日期 / 时区",
      "游戏构建",
      "OS / 内核 / GPU 驱动",
      "CPU / GPU / 内存",
      "分辨率 / 渲染比例 / 预设",
      "服务器 / 地区 / 地图 / 职责",
      "路线 / 时长 / 启动后分钟数",
      "A：原设置 / FPS / 帧时间尖峰 / ping",
      "B：只改一项设置 / 同样的测量项",
      "再次 A：还原设置 / 同样的测量项",
      "结论：保留或还原 / 理由",
      "准确界面阶段 / 排队位置",
      "是否响应 / 是否推进 / 进程是否仍在",
      "所选筛选 / 刷新一次 / 结果",
      "正式版或 Playtest / 是否更新 / 账号访问权限",
      "最后成功步骤 / 错误原文 / 截图时间",
      "已尝试操作 / 前后结果",
      "Proton 准确版本 / 启动参数",
      "原生 / 进程启动 / 菜单 / 加入 / 完整对局 / 重连",
      "SteamOS / 输入布局 / 分辨率 / 持续性能",
      "其他改变的变量 / 未测量项"
    ]
  },
  "zh-tw": {
    "copy": "複製空白記錄",
    "copied": "記錄已複製",
    "failed": "複製失敗，請選取下方文字。",
    "performance": "效能對照：A → B → A",
    "connection": "連線故障交接記錄",
    "linux": "Linux / Proton 分階段記錄",
    "labels": [
      "日期 / 時區",
      "遊戲組建",
      "OS / 核心 / GPU 驅動程式",
      "CPU / GPU / 記憶體",
      "解析度 / 渲染比例 / 預設",
      "伺服器 / 地區 / 地圖 / 職責",
      "路線 / 時長 / 啟動後分鐘數",
      "A：原設定 / FPS / 畫格時間尖峰 / ping",
      "B：只改一項設定 / 相同測量項",
      "再次 A：還原設定 / 相同測量項",
      "結論：保留或還原 / 理由",
      "準確畫面階段 / 排隊位置",
      "是否回應 / 是否推進 / 程序是否仍在",
      "所選篩選 / 更新一次 / 結果",
      "正式版或 Playtest / 是否更新 / 帳號存取權",
      "最後成功步驟 / 錯誤原文 / 截圖時間",
      "已嘗試操作 / 前後結果",
      "Proton 準確版本 / 啟動參數",
      "原生 / 程序啟動 / 選單 / 加入 / 完整對局 / 重新連線",
      "SteamOS / 輸入配置 / 解析度 / 持續效能",
      "其他改變的變數 / 未測量項"
    ]
  },
  "pl": {
    "copy": "Kopiuj pusty formularz",
    "copied": "Formularz skopiowany",
    "failed": "Kopiowanie nie powiodło się; zaznacz tekst poniżej.",
    "performance": "Porównanie wydajności: A → B → A",
    "connection": "Raport połączenia dla wsparcia",
    "linux": "Raport etapów Linux / Proton",
    "labels": [
      "Data / strefa czasowa",
      "Build gry",
      "OS / jądro / sterownik GPU",
      "CPU / GPU / RAM",
      "Rozdzielczość / skala renderowania / preset",
      "Serwer / region / mapa / rola",
      "Trasa / czas testu / minuty od uruchomienia",
      "A: pierwotne ustawienie / FPS / skoki czasu klatki / ping",
      "B: jedno zmienione ustawienie / te same pomiary",
      "Ponownie A: przywrócone ustawienie / te same pomiary",
      "Wynik: zachować lub przywrócić / powód",
      "Dokładny ekran / pozycja w kolejce",
      "Reaguje / postępuje / proces nadal działa",
      "Wybrane filtry / jedno odświeżenie / wynik",
      "Gra główna lub Playtest / aktualizacja / dostęp konta",
      "Ostatni udany krok / dokładny błąd / czas zrzutu",
      "Wypróbowane działanie / wynik przed i po",
      "Dokładna wersja Proton / opcje uruchamiania",
      "Natywny / start procesu / menu / wejście / cały mecz / ponowne połączenie",
      "SteamOS / sterowanie / rozdzielczość / stała wydajność",
      "Inne zmienione warunki / nie zmierzono"
    ]
  }
} as const satisfies Record<Locale, {copy: string; copied: string; failed: string; performance: string; connection: string; linux: string; labels: readonly string[]}>;

const fields: Record<DiagnosticRecordKind, readonly number[]> = {performance: [0,1,2,3,4,5,6,7,8,9,10,20], connection: [0,1,5,11,12,13,14,15,16], linux: [0,1,2,3,17,18,19,15,16,20]};
export function getDiagnosticRecordCopy(locale: Locale, kind: DiagnosticRecordKind) {
  const t = copy[locale];
  return {...t, title: t[kind], text: fields[kind].map(index => `${t.labels[index]}: ____`).join("\n")};
}
