import type {Locale} from "@/config/site";

// Related queries share a useful page; existing primary keywords remain in metadata.
const intents: Record<string, Record<Locale, readonly string[]>> = {
  "wardogs-solo-guide": {
    "en": ["solo beginner route", "play without a mic", "solo loadout budget", "find a squad as a solo player"],
    "ja": ["ソロ初心者の立ち回り", "マイクなしで遊ぶ", "ソロ装備の予算", "一人で分隊に参加"],
    "zh-cn": ["独狼新手路线", "不开麦怎么玩", "单排配装预算", "一个人怎么找小队"],
    "zh-tw": ["獨狼新手路線", "不開麥怎麼玩", "單排配裝預算", "一個人怎麼找小隊"],
    "ru": ["как играть одному новичку", "играть без микрофона", "бюджет снаряжения для соло", "как одиночке найти отряд"],
    "de": ["als Anfänger solo spielen", "ohne Mikrofon spielen", "Budget für Solo-Ausrüstung", "als Solospieler einen Squad finden"],
    "pt-br": ["rota para iniciante solo", "jogar sem microfone", "orçamento de equipamento solo", "encontrar esquadrão jogando sozinho"],
    "pl": ["jak grać solo jako początkujący", "gra bez mikrofonu", "budżet wyposażenia solo", "jak znaleźć drużynę grając samemu"],
  },
  "wardogs-report-player": {
    "en": ["report a cheater", "ban appeal", "report a renamed player", "community server ban", "player report evidence"],
    "ja": ["チーターを通報", "BAN異議申し立て", "名前を変えたプレイヤーの通報", "コミュニティサーバーBAN", "通報の証拠"],
    "zh-cn": ["举报作弊玩家", "封禁申诉", "玩家改名后怎么举报", "社区服务器封禁", "举报证据模板"],
    "zh-tw": ["檢舉作弊玩家", "停權申訴", "玩家改名後怎麼檢舉", "社群伺服器停權", "檢舉證據範本"],
    "ru": ["пожаловаться на читера", "обжаловать бан", "жалоба на игрока после смены ника", "бан на сервере сообщества", "доказательства для жалобы"],
    "de": ["Cheater melden", "Bann anfechten", "Spieler nach Namensänderung melden", "Community-Server-Bann", "Beweise für eine Spielermeldung"],
    "pt-br": ["denunciar jogador trapaceiro", "recorrer de banimento", "denunciar jogador que mudou de nome", "banimento em servidor comunitário", "provas para denúncia"],
    "pl": ["zgłosić oszusta", "odwołanie od bana", "zgłosić gracza po zmianie nicku", "ban na serwerze społeczności", "dowody do zgłoszenia"],
  },
  "wardogs-squad-guide": {
    "en": ["play with friends", "invite friends", "join the same team"],
    "ja": ["フレンドと遊ぶ", "フレンド招待", "同じチームに入る"],
    "zh-cn": ["好友组队", "邀请好友", "加入同一队伍"],
    "zh-tw": ["好友組隊", "邀請好友", "加入同一隊伍"],
    "ru": ["играть с друзьями", "пригласить друга", "попасть в одну команду"],
    "de": ["mit Freunden spielen", "Freunde einladen", "gleichem Team beitreten"],
    "pt-br": ["jogar com amigos", "convidar amigos", "entrar na mesma equipe"],
    "pl": ["gra ze znajomymi", "zaprosić znajomych", "dołączyć do tej samej drużyny"],
  },
  "wardogs-crash-fix": {
    "en": ["WD-L014", "WD-L018", "WD-L020", "unable to launch"],
    "ja": ["WD-L014", "WD-L018", "WD-L020", "起動しない", "認証エラー"],
    "zh-cn": ["WD-L014", "WD-L018", "WD-L020", "启动报错", "无法启动"],
    "zh-tw": ["WD-L014", "WD-L018", "WD-L020", "啟動報錯", "無法啟動"],
    "ru": ["WD-L014", "WD-L018", "WD-L020", "не запускается", "ошибка запуска"],
    "de": ["WD-L014", "WD-L018", "WD-L020", "startet nicht", "Startfehler"],
    "pt-br": ["WD-L014", "WD-L018", "WD-L020", "não inicia", "erro de autenticação"],
    "pl": ["WD-L014", "WD-L018", "WD-L020", "nie uruchamia się", "błąd uruchamiania"],
  },
  "wardogs-community-servers-guide": {
    "en": ["infantry mode", "infantry only", "low-level servers"],
    "ja": ["歩兵モード", "歩兵専用", "低レベルサーバー"],
    "zh-cn": ["步兵模式", "纯步兵服务器", "低等级服务器"],
    "zh-tw": ["步兵模式", "純步兵伺服器", "低等級伺服器"],
    "ru": ["режим пехоты", "пехотные серверы", "серверы для новичков"],
    "de": ["Infanteriemodus", "nur Infanterie", "Server für niedrige Level"],
    "pt-br": ["modo infantaria", "somente infantaria", "servidores de nível baixo"],
    "pl": ["tryb piechoty", "tylko piechota", "serwery dla niskich poziomów"],
  },
  "wardogs-best-settings": {
    "en": ["best graphics settings", "increase FPS", "visibility settings"],
    "ja": ["おすすめ設定", "FPSを上げる", "見やすい画質設定"],
    "zh-cn": ["最佳画面设置", "提高FPS", "清晰度设置"],
    "zh-tw": ["最佳畫面設定", "提高FPS", "清晰度設定"],
    "ru": ["лучшие настройки", "повысить FPS", "видимость противников"],
    "de": ["beste Einstellungen", "FPS erhöhen", "Sichtbarkeit verbessern"],
    "pt-br": ["melhores configurações", "aumentar FPS", "visibilidade"],
    "pl": ["najlepsze ustawienia", "zwiększyć FPS", "widoczność przeciwników"],
  },
  "wardogs-controls": {
    "en": ["controller double input", "Steam Input", "helicopter controls"],
    "ja": ["コントローラー二重入力", "Steam Input", "ヘリ操作"],
    "zh-cn": ["手柄重复输入", "Steam Input", "直升机按键"],
    "zh-tw": ["手把重複輸入", "Steam Input", "直升機按鍵"],
    "ru": ["двойной ввод геймпада", "Steam Input", "управление вертолётом"],
    "de": ["doppelte Controller-Eingaben", "Steam Input", "Hubschraubersteuerung"],
    "pt-br": ["entrada duplicada no controle", "Steam Input", "controles do helicóptero"],
    "pl": ["podwójne wejście kontrolera", "Steam Input", "sterowanie helikopterem"],
  },
  "wardogs-equipment-tools-guide": {
    "en": ["IR rangefinder", "CWIS", "CIWS", "rangefinder batteries"],
    "ja": ["IR距離計", "CWIS", "CIWS", "距離計バッテリー"],
    "zh-cn": ["红外测距仪", "CWIS", "CIWS", "测距仪电池"],
    "zh-tw": ["紅外測距儀", "CWIS", "CIWS", "測距儀電池"],
    "ru": ["IR-дальномер", "CWIS", "CIWS", "батареи дальномера"],
    "de": ["IR-Entfernungsmesser", "CWIS", "CIWS", "Batterien"],
    "pt-br": ["telêmetro IR", "CWIS", "CIWS", "baterias do telêmetro"],
    "pl": ["dalmierz IR", "CWIS", "CIWS", "baterie dalmierza"],
  },
  "wardogs-progression-wipes-guide": {
    "en": ["next wipe date", "season reset", "Career XP", "role XP"],
    "ja": ["次のワイプ", "シーズンリセット", "キャリアXP", "役割XP"],
    "zh-cn": ["下次清档日期", "赛季重置", "生涯经验", "角色经验"],
    "zh-tw": ["下次清檔日期", "賽季重置", "生涯經驗", "角色經驗"],
    "ru": ["дата вайпа", "сброс сезона", "опыт карьеры", "опыт роли"],
    "de": ["nächster Wipe", "Saison-Reset", "Karriere-XP", "Rollen-XP"],
    "pt-br": ["próximo wipe", "reinício da temporada", "XP de carreira", "XP de função"],
    "pl": ["data następnego wipe", "reset sezonu", "XP kariery", "XP roli"],
  },
  "wardogs-season-2": {
    "en": ["Season 2 October 15", "what resets", "what carries over"],
    "ja": ["シーズン2 10月15日", "リセット対象", "引き継ぎ"],
    "zh-cn": ["第二赛季10月15日", "清档保留内容", "赛季重置"],
    "zh-tw": ["第二賽季10月15日", "清檔保留內容", "賽季重置"],
    "ru": ["сезон 2 15 октября", "что сбрасывается", "что сохраняется"],
    "de": ["Season 2 15. Oktober", "was wird zurückgesetzt", "was bleibt"],
    "pt-br": ["Temporada 2 15 de outubro", "o que reinicia", "o que permanece"],
    "pl": ["sezon 2 15 października", "co się resetuje", "co pozostaje"],
  },
  "wardogs-money-guide": {
    "en": ["gold bar price", "cash to gold", "loadout budget"],
    "ja": ["金の延べ棒価格", "キャッシュからゴールド", "装備予算"],
    "zh-cn": ["金条价格", "现金兑换黄金", "配装预算"],
    "zh-tw": ["金條價格", "現金兌換黃金", "配裝預算"],
    "ru": ["цена золотого слитка", "деньги в золото", "бюджет комплекта"],
    "de": ["Goldbarrenpreis", "Geld in Gold", "Loadout-Budget"],
    "pt-br": ["preço da barra de ouro", "dinheiro em ouro", "orçamento do kit"],
    "pl": ["cena sztabki złota", "gotówka na złoto", "budżet wyposażenia"],
  },
  "wardogs-achievements": {
    "en": ["hidden achievements", "secret achievements", "achievement unlocks"],
    "ja": ["隠し実績", "秘密の実績", "実績解除"],
    "zh-cn": ["隐藏成就", "秘密成就", "成就解锁"],
    "zh-tw": ["隱藏成就", "秘密成就", "成就解鎖"],
    "ru": ["скрытые достижения", "секретные достижения", "открыть достижения"],
    "de": ["versteckte Erfolge", "geheime Errungenschaften", "Erfolge freischalten"],
    "pt-br": ["conquistas ocultas", "conquistas secretas", "desbloquear conquistas"],
    "pl": ["ukryte osiągnięcia", "sekretne osiągnięcia", "odblokować osiągnięcia"],
  },
  "wardogs-mortar-guide": {
    "en": ["mortar calculator", "mortar range", "L81 mils"],
    "ja": ["迫撃砲計算機", "迫撃砲射程", "L81ミル"],
    "zh-cn": ["迫击炮计算器", "迫击炮射程", "L81密位"],
    "zh-tw": ["迫擊砲計算器", "迫擊砲射程", "L81密位"],
    "ru": ["калькулятор миномёта", "дальность миномёта", "тысячные L81"],
    "de": ["Mörser-Rechner", "Mörserreichweite", "L81 Strich"],
    "pt-br": ["calculadora de morteiro", "alcance do morteiro", "mils L81"],
    "pl": ["kalkulator moździerza", "zasięg moździerza", "tysięczne L81"],
  },
  "wardogs-artillery-guide": {
    "en": ["artillery calculator", "SPH-2 high arc", "artillery map"],
    "ja": ["砲兵計算機", "SPH-2高角射撃", "砲兵マップ"],
    "zh-cn": ["火炮计算器", "SPH-2高抛弹道", "火炮地图"],
    "zh-tw": ["火炮計算器", "SPH-2高拋彈道", "火炮地圖"],
    "ru": ["артиллерийский калькулятор", "навесная траектория SPH-2", "карта артиллерии"],
    "de": ["Artillerie-Rechner", "SPH-2 hoher Bogen", "Artilleriekarte"],
    "pt-br": ["calculadora de artilharia", "trajetória alta SPH-2", "mapa de artilharia"],
    "pl": ["kalkulator artylerii", "wysoki tor SPH-2", "mapa artylerii"],
  },
  "wardogs-map": {
    "en": ["interactive map", "map distance", "FOB routes"],
    "ja": ["インタラクティブマップ", "地図の距離", "FOBルート"],
    "zh-cn": ["交互地图", "地图测距", "FOB路线"],
    "zh-tw": ["互動地圖", "地圖測距", "FOB路線"],
    "ru": ["интерактивная карта", "расстояние на карте", "маршруты FOB"],
    "de": ["interaktive Karte", "Entfernung messen", "FOB-Routen"],
    "pt-br": ["mapa interativo", "distância no mapa", "rotas de FOB"],
    "pl": ["interaktywna mapa", "odległość na mapie", "trasy FOB"],
  },
  "wardogs-cargo-guide": {
    "en": ["cargo transport", "supply pallet", "logistics route"],
    "ja": ["物資輸送", "補給パレット", "兵站ルート"],
    "zh-cn": ["货物运输", "补给托盘", "后勤路线"],
    "zh-tw": ["貨物運輸", "補給棧板", "後勤路線"],
    "ru": ["перевозка грузов", "поддоны снабжения", "маршрут логистики"],
    "de": ["Frachttransport", "Versorgungspalette", "Logistikroute"],
    "pt-br": ["transporte de carga", "palete de suprimentos", "rota logística"],
    "pl": ["transport ładunku", "paleta zaopatrzenia", "trasa logistyczna"],
  },
  "wardogs-best-weapons-loadouts": {
    "en": ["best guns", "weapon tier list", "weapon comparison"],
    "ja": ["おすすめ武器", "武器ランキング", "武器比較"],
    "zh-cn": ["最强武器", "武器排行", "武器对比"],
    "zh-tw": ["最強武器", "武器排行", "武器對比"],
    "ru": ["лучшее оружие", "тир-лист оружия", "сравнение оружия"],
    "de": ["beste Waffen", "Waffen-Tierliste", "Waffenvergleich"],
    "pt-br": ["melhores armas", "tier list de armas", "comparar armas"],
    "pl": ["najlepsza broń", "ranking broni", "porównanie broni"],
  },
  "wardogs-helicopter-guide": {
    "en": ["helicopter mouse control", "Havoc", "pilot progression"],
    "ja": ["ヘリのマウス操作", "Havoc", "パイロット育成"],
    "zh-cn": ["直升机鼠标操作", "Havoc", "飞行员升级"],
    "zh-tw": ["直升機滑鼠操作", "Havoc", "飛行員升級"],
    "ru": ["вертолёт мышью", "Havoc", "прокачка пилота"],
    "de": ["Hubschrauber mit Maus", "Havoc", "Pilotenfortschritt"],
    "pt-br": ["helicóptero com mouse", "Havoc", "progressão de piloto"],
    "pl": ["helikopter myszą", "Havoc", "postępy pilota"],
  },
  "wardogs-known-issues": {
    "en": ["known bugs", "WD-L014", "WD-L018", "controller input"],
    "ja": ["既知の不具合", "WD-L014", "WD-L018", "コントローラー入力"],
    "zh-cn": ["已知问题", "WD-L014", "WD-L018", "手柄输入"],
    "zh-tw": ["已知問題", "WD-L014", "WD-L018", "手把輸入"],
    "ru": ["известные проблемы", "WD-L014", "WD-L018", "ввод геймпада"],
    "de": ["bekannte Fehler", "WD-L014", "WD-L018", "Controller-Eingabe"],
    "pt-br": ["problemas conhecidos", "WD-L014", "WD-L018", "entrada do controle"],
    "pl": ["znane problemy", "WD-L014", "WD-L018", "wejście kontrolera"],
  },
  "wardogs-patch-notes": {
    "en": ["update today", "0.1.2 patch", "CWIS hotfix"],
    "ja": ["今日のアップデート", "0.1.2パッチ", "CWIS修正"],
    "zh-cn": ["今日更新", "0.1.2补丁", "CWIS热修"],
    "zh-tw": ["今日更新", "0.1.2補丁", "CWIS熱修"],
    "ru": ["обновление сегодня", "патч 0.1.2", "исправление CWIS"],
    "de": ["Update heute", "Patch 0.1.2", "CWIS-Hotfix"],
    "pt-br": ["atualização de hoje", "patch 0.1.2", "hotfix CWIS"],
    "pl": ["dzisiejsza aktualizacja", "aktualizacja 0.1.2", "poprawka CWIS"],
  },
  "wardogs-server-status": {
    "en": ["server maintenance", "servers down", "authentication status"],
    "ja": ["サーバーメンテナンス", "サーバー障害", "認証状況"],
    "zh-cn": ["服务器维护", "服务器故障", "认证状态"],
    "zh-tw": ["伺服器維護", "伺服器故障", "認證狀態"],
    "ru": ["обслуживание серверов", "серверы не работают", "состояние авторизации"],
    "de": ["Serverwartung", "Server offline", "Authentifizierungsstatus"],
    "pt-br": ["manutenção dos servidores", "servidores fora do ar", "status de autenticação"],
    "pl": ["konserwacja serwerów", "serwery niedostępne", "stan uwierzytelniania"],
  },
  "wardogs-towers-guide": {
    "en": ["capture towers", "tower objectives", "hold a tower"],
    "ja": ["タワーの取り方", "タワー攻略", "タワー防衛"],
    "zh-cn": ["塔楼怎么占领", "塔楼攻略", "塔楼防守"],
    "zh-tw": ["塔樓怎麼佔領", "塔樓攻略", "塔樓防守"],
    "ru": ["захват башни", "башни", "оборона башни"],
    "de": ["Türme erobern", "Turmziele", "Turm verteidigen"],
    "pt-br": ["capturar torres", "objetivos de torre", "defender torre"],
    "pl": ["przejmowanie wież", "cele wieży", "obrona wieży"],
  },
  "wardogs-beginner-guide": {
    "en": ["beginner tips", "first match", "starter loadout"],
    "ja": ["初心者攻略", "最初の試合", "初心者装備"],
    "zh-cn": ["新手攻略", "第一局怎么玩", "新手配装"],
    "zh-tw": ["新手攻略", "第一局怎麼玩", "新手配裝"],
    "ru": ["советы новичкам", "первый матч", "стартовый комплект"],
    "de": ["Anfängertipps", "erstes Match", "Starter-Loadout"],
    "pt-br": ["dicas para iniciantes", "primeira partida", "kit inicial"],
    "pl": ["porady dla początkujących", "pierwszy mecz", "zestaw początkowy"],
  },
  "wardogs-ammo-reload-guide": {
    "en": ["ammo matcher", "weapon ammunition", "reload magazines"],
    "ja": ["弾薬対応表", "武器の弾薬", "マガジン交換"],
    "zh-cn": ["弹药匹配器", "武器弹药", "弹匣换弹"],
    "zh-tw": ["彈藥匹配器", "武器彈藥", "彈匣換彈"],
    "ru": ["подбор боеприпасов", "патроны для оружия", "перезарядка магазина"],
    "de": ["Munitionszuordnung", "Waffenmunition", "Magazin nachladen"],
    "pt-br": ["compatibilidade de munição", "munição da arma", "recarregar carregador"],
    "pl": ["dobór amunicji", "amunicja do broni", "przeładowanie magazynka"],
  },
  "wardogs-fob-guide": {
    "en": ["FOB construction", "building placement", "logistics planner"],
    "ja": ["FOB建築", "建築できない", "兵站プランナー"],
    "zh-cn": ["FOB建造", "建筑放不下", "后勤规划器"],
    "zh-tw": ["FOB建造", "建築放不下", "後勤規劃器"],
    "ru": ["строительство FOB", "постройка не ставится", "планировщик логистики"],
    "de": ["FOB bauen", "Bau lässt sich nicht platzieren", "Logistikplaner"],
    "pt-br": ["construir FOB", "construção não encaixa", "planejador logístico"],
    "pl": ["budowa FOB", "nie można postawić budowli", "planer logistyki"],
  },
  "wardogs-oil-rig-guide": {
    "en": ["oil rig logistics", "oil supply route", "oil rig defense"],
    "ja": ["石油リグの兵站", "石油補給ルート", "リグ防衛"],
    "zh-cn": ["石油钻井平台后勤", "油料补给路线", "平台防守"],
    "zh-tw": ["石油鑽井平台後勤", "油料補給路線", "平台防守"],
    "ru": ["логистика нефтяной платформы", "маршрут снабжения", "оборона платформы"],
    "de": ["Ölplattform-Logistik", "Ölversorgungsroute", "Plattform verteidigen"],
    "pt-br": ["logística da plataforma de petróleo", "rota de abastecimento", "defender plataforma"],
    "pl": ["logistyka platformy naftowej", "trasa dostaw", "obrona platformy"],
  },
};

export function getGuideIntentKeywords(locale: Locale, slug: string): readonly string[] {
  return intents[slug]?.[locale] ?? [];
}
