import type {Locale} from "@/config/site";
const en = {
  "estimatedTof": "Estimated flight time",
  "timingHelp": "Flight time and the timer are linear estimates, not measured impacts. Do not use them for precise synchronized volleys.",
  "heightHelp": "Height compensation is an unverified linear estimate. Enter the observed height difference and confirm with a ranging shot. Terrain is not sampled.",
  "estimatedImpact": "Estimated impact in",
  "timerElapsed": "Estimated timer elapsed",
  "fireAgain": "Restart estimated timer",
  "imported": "Map mission loaded.",
  "importHelp": "Distance, bearing and map scale were restored. Check the target height before firing.",
  "invalidImport": "The shared firing solution is incomplete or invalid and was not applied. Set the positions on the map or enter the distance and bearing.",
  "correction": "Spotting correction",
  "title": "Adjust from the observed impact",
  "help": "The next step changes range by 5% (minimum 5 m) and bearing by 2°. It is a ranging estimate; observe another shot before firing a volley.",
  "apply": "Apply correction",
  "range": "Range impact",
  "lateral": "Lateral impact",
  "short": "Short",
  "on": "On target",
  "long": "Long",
  "left": "Left",
  "right": "Right",
  "line": "On line",
  "nextDistance": "Next distance",
  "nextAzimuth": "Next azimuth",
  "elevationCue": "Elevation cue",
  "lateralCue": "Lateral cue",
  "increase_mil": "Increase mil",
  "decrease_mil": "Decrease mil",
  "hold_mil": "Hold mil",
  "unavailable": "Unavailable",
  "hold": "Hold",
  "log": "Fire log",
  "recent": "Recent shots",
  "clear": "Clear log",
  "empty": "Fire a valid solution to record a shot on this device.",
  "audioOn": "Audio cues enabled",
  "audioOff": "Audio muted",
  "invalid": "Correction is outside the firing table. Change the range or trajectory before applying."
};
export type ArtilleryMissionCopy = typeof en;
const copies: Record<Locale, ArtilleryMissionCopy> = {en,
"zh-cn": {
  "estimatedTof": "估算飞行时间",
  "timingHelp": "飞行时间和计时器为线性估算，并非实测落点时间，不可用于精确同步齐射。",
  "heightHelp": "高差补偿使用未经验证的线性估算。请手动输入观测高差并通过试射确认；工具不采样地形。",
  "estimatedImpact": "预计落点倒计时",
  "timerElapsed": "估算计时结束",
  "fireAgain": "重新估算计时",
  "imported": "地图任务已载入。",
  "importHelp": "已恢复距离、方位角和地图比例。开火前核对目标高差。",
  "invalidImport": "分享的射击参数不完整或无效，未予载入。请在地图上设置位置，或手动输入距离和方位角。",
  "correction": "落点修正",
  "title": "根据实际弹着点修正",
  "help": "下一步调整距离 5%（至少 5 米）、方位角 2°。这只是校射估算；请再观测一发后进行齐射。",
  "apply": "应用修正",
  "range": "远近落点",
  "lateral": "左右落点",
  "short": "偏近",
  "on": "命中目标",
  "long": "偏远",
  "left": "偏左",
  "right": "偏右",
  "line": "方向正确",
  "nextDistance": "下次距离",
  "nextAzimuth": "下次方位角",
  "elevationCue": "射角提示",
  "lateralCue": "方向提示",
  "increase_mil": "提高密位",
  "decrease_mil": "降低密位",
  "hold_mil": "保持密位",
  "unavailable": "不可用",
  "hold": "保持",
  "log": "射击记录",
  "recent": "最近射击",
  "clear": "清空记录",
  "empty": "按有效射击解算开火，即可在本设备记录。",
  "audioOn": "声音提示已开启",
  "audioOff": "声音已关闭",
  "invalid": "修正超出射表范围。请调整距离或弹道后再应用。"
},
"zh-tw": {
  "estimatedTof": "估算飛行時間",
  "timingHelp": "飛行時間和計時器為線性估算，並非實測落點時間，不可用於精確同步齊射。",
  "heightHelp": "高差補償使用未經驗證的線性估算。請手動輸入觀測高差並透過試射確認；工具不取樣地形。",
  "estimatedImpact": "預計落點倒數",
  "timerElapsed": "估算計時結束",
  "fireAgain": "重新估算計時",
  "imported": "地圖任務已載入。",
  "importHelp": "已恢復距離、方位角和地圖比例。開火前核對目標高差。",
  "invalidImport": "分享的射擊參數不完整或無效，未予載入。請在地圖上設定位置，或手動輸入距離和方位角。",
  "correction": "落點修正",
  "title": "根據實際彈著點修正",
  "help": "下一步調整距離 5%（至少 5 米）、方位角 2°。這只是校射估算；請再觀測一發後進行齊射。",
  "apply": "套用修正",
  "range": "遠近落點",
  "lateral": "左右落點",
  "short": "偏近",
  "on": "命中目標",
  "long": "偏遠",
  "left": "偏左",
  "right": "偏右",
  "line": "方向正確",
  "nextDistance": "下次距離",
  "nextAzimuth": "下次方位角",
  "elevationCue": "射角提示",
  "lateralCue": "方向提示",
  "increase_mil": "提高密位",
  "decrease_mil": "降低密位",
  "hold_mil": "保持密位",
  "unavailable": "不可用",
  "hold": "保持",
  "log": "射擊紀錄",
  "recent": "最近射擊",
  "clear": "清空紀錄",
  "empty": "按有效射擊解算開火，即可在本裝置記錄。",
  "audioOn": "聲音提示已開啟",
  "audioOff": "聲音已關閉",
  "invalid": "修正超出射表範圍。請調整距離或彈道後再套用。"
},
"ja": {
  "estimatedTof": "推定飛翔時間",
  "timingHelp": "飛翔時間とタイマーは線形推定で、実測した着弾時刻ではありません。精密な同時着弾射撃には使用できません。",
  "heightHelp": "高低差補正は未検証の線形推定です。観測した高低差を入力し、試射で確認してください。地形の高さは取得しません。",
  "estimatedImpact": "推定着弾まで",
  "timerElapsed": "推定タイマー終了",
  "fireAgain": "推定タイマーを再開",
  "imported": "マップの任務を読み込みました。",
  "importHelp": "距離・方位角・縮尺を復元しました。射撃前に目標との高低差を確認してください。",
  "invalidImport": "共有された射撃データが不完全または無効なため、読み込めませんでした。マップ上で位置を指定するか、距離と方位角を入力してください。",
  "correction": "着弾修正",
  "title": "観測した着弾点から修正",
  "help": "距離を5%（最低5 m）、方位角を2°修正します。試射用の推定値です。斉射前にもう1発観測してください。",
  "apply": "修正を適用",
  "range": "前後の着弾",
  "lateral": "左右の着弾",
  "short": "手前",
  "on": "目標上",
  "long": "奥",
  "left": "左",
  "right": "右",
  "line": "射線上",
  "nextDistance": "次の距離",
  "nextAzimuth": "次の方位角",
  "elevationCue": "仰角の指示",
  "lateralCue": "左右の指示",
  "increase_mil": "ミルを上げる",
  "decrease_mil": "ミルを下げる",
  "hold_mil": "ミルを維持",
  "unavailable": "利用不可",
  "hold": "維持",
  "log": "射撃記録",
  "recent": "最近の射撃",
  "clear": "記録を消去",
  "empty": "有効な射撃解で発射すると、この端末に記録されます。",
  "audioOn": "音声通知オン",
  "audioOff": "音声オフ",
  "invalid": "修正値が射表の範囲外です。距離または弾道を変更してください。"
},
"de": {
  "estimatedTof": "Geschätzte Flugzeit",
  "timingHelp": "Flugzeit und Timer sind lineare Schätzungen, keine gemessenen Einschlagzeiten. Nicht für präzise synchronisierte Salven verwenden.",
  "heightHelp": "Die Höhenkorrektur ist eine ungeprüfte lineare Schätzung. Beobachteten Höhenunterschied eingeben und mit einem Probeschuss prüfen. Geländehöhen werden nicht erfasst.",
  "estimatedImpact": "Geschätzter Einschlag in",
  "timerElapsed": "Geschätzte Zeit abgelaufen",
  "fireAgain": "Schätztimer neu starten",
  "imported": "Kartenauftrag geladen.",
  "importHelp": "Entfernung, Richtung und Maßstab wurden übernommen. Vor dem Feuern den Höhenunterschied prüfen.",
  "invalidImport": "Die geteilten Schussdaten sind unvollständig oder ungültig und wurden nicht übernommen. Positionen auf der Karte setzen oder Entfernung und Richtung eingeben.",
  "correction": "Trefferkorrektur",
  "title": "Nach beobachtetem Einschlag korrigieren",
  "help": "Der nächste Schritt ändert die Entfernung um 5% (mindestens 5 m) und die Richtung um 2°. Schätzung fürs Einschießen; vor einer Salve einen weiteren Schuss beobachten.",
  "apply": "Korrektur anwenden",
  "range": "Längsabweichung",
  "lateral": "Seitenabweichung",
  "short": "Zu kurz",
  "on": "Im Ziel",
  "long": "Zu weit",
  "left": "Links",
  "right": "Rechts",
  "line": "Auf Linie",
  "nextDistance": "Nächste Entfernung",
  "nextAzimuth": "Nächster Azimut",
  "elevationCue": "Höhenkorrektur",
  "lateralCue": "Seitenkorrektur",
  "increase_mil": "Mil erhöhen",
  "decrease_mil": "Mil senken",
  "hold_mil": "Mil halten",
  "unavailable": "Nicht verfügbar",
  "hold": "Halten",
  "log": "Feuerprotokoll",
  "recent": "Letzte Schüsse",
  "clear": "Protokoll löschen",
  "empty": "Mit einer gültigen Lösung feuern, um den Schuss auf diesem Gerät zu speichern.",
  "audioOn": "Tonsignale aktiviert",
  "audioOff": "Ton aus",
  "invalid": "Korrektur außerhalb der Schusstafel. Entfernung oder Flugbahn ändern."
},
"ru": {
  "estimatedTof": "Расчётное время полёта",
  "timingHelp": "Время полёта и таймер — линейные оценки, а не измеренное время попадания. Не используйте их для точной синхронизации залпов.",
  "heightHelp": "Поправка по высоте — непроверенная линейная оценка. Введите наблюдаемый перепад и проверьте пристрелочным выстрелом. Высота рельефа не считывается.",
  "estimatedImpact": "Примерно до попадания",
  "timerElapsed": "Расчётное время истекло",
  "fireAgain": "Перезапустить расчётный таймер",
  "imported": "Задача с карты загружена.",
  "importHelp": "Восстановлены дальность, азимут и масштаб. Перед выстрелом проверьте перепад высот.",
  "invalidImport": "Данные огневой задачи неполные или неверные и не загружены. Укажите позиции на карте или введите дальность и азимут.",
  "correction": "Корректировка огня",
  "title": "Поправка по наблюдаемому попаданию",
  "help": "Следующий шаг меняет дальность на 5% (минимум 5 м), азимут на 2°. Это пристрелочная оценка; перед залпом наблюдайте ещё один выстрел.",
  "apply": "Применить поправку",
  "range": "Отклонение по дальности",
  "lateral": "Боковое отклонение",
  "short": "Недолёт",
  "on": "В цель",
  "long": "Перелёт",
  "left": "Влево",
  "right": "Вправо",
  "line": "По линии",
  "nextDistance": "Следующая дальность",
  "nextAzimuth": "Следующий азимут",
  "elevationCue": "Поправка угла",
  "lateralCue": "Боковая поправка",
  "increase_mil": "Увеличить мил",
  "decrease_mil": "Уменьшить мил",
  "hold_mil": "Сохранить мил",
  "unavailable": "Недоступно",
  "hold": "Сохранить",
  "log": "Журнал огня",
  "recent": "Последние выстрелы",
  "clear": "Очистить журнал",
  "empty": "Выстрел с допустимым решением сохранится на этом устройстве.",
  "audioOn": "Звуковые сигналы включены",
  "audioOff": "Звук выключен",
  "invalid": "Поправка выходит за таблицу стрельбы. Измените дальность или траекторию."
},
"pt-br": {
  "estimatedTof": "Tempo de voo estimado",
  "timingHelp": "O tempo de voo e o cronômetro são estimativas lineares, não tempos de impacto medidos. Não use para sincronizar salvas com precisão.",
  "heightHelp": "A compensação de altura é uma estimativa linear não verificada. Informe o desnível observado e confirme com um tiro de ajuste. A altura do terreno não é coletada.",
  "estimatedImpact": "Impacto estimado em",
  "timerElapsed": "Tempo estimado decorrido",
  "fireAgain": "Reiniciar tempo estimado",
  "imported": "Missão do mapa carregada.",
  "importHelp": "Distância, azimute e escala foram restaurados. Confira a diferença de altura antes de disparar.",
  "invalidImport": "Os dados de tiro compartilhados estão incompletos ou inválidos e não foram aplicados. Marque as posições no mapa ou informe a distância e o azimute.",
  "correction": "Correção de impacto",
  "title": "Ajuste pelo impacto observado",
  "help": "O próximo passo altera a distância em 5% (mínimo 5 m) e o azimute em 2°. É uma estimativa de ajuste; observe outro disparo antes da salva.",
  "apply": "Aplicar correção",
  "range": "Impacto em distância",
  "lateral": "Impacto lateral",
  "short": "Curto",
  "on": "No alvo",
  "long": "Longo",
  "left": "Esquerda",
  "right": "Direita",
  "line": "Na linha",
  "nextDistance": "Próxima distância",
  "nextAzimuth": "Próximo azimute",
  "elevationCue": "Ajuste de elevação",
  "lateralCue": "Ajuste lateral",
  "increase_mil": "Aumentar mil",
  "decrease_mil": "Reduzir mil",
  "hold_mil": "Manter mil",
  "unavailable": "Indisponível",
  "hold": "Manter",
  "log": "Registro de tiro",
  "recent": "Disparos recentes",
  "clear": "Limpar registro",
  "empty": "Dispare uma solução válida para registrar o tiro neste dispositivo.",
  "audioOn": "Alertas sonoros ativados",
  "audioOff": "Som desativado",
  "invalid": "Correção fora da tabela de tiro. Altere distância ou trajetória antes de aplicar."
},
"pl": {
  "estimatedTof": "Szacowany czas lotu",
  "timingHelp": "Czas lotu i licznik są liniowymi szacunkami, nie zmierzonym czasem trafienia. Nie używaj ich do precyzyjnej synchronizacji salw.",
  "heightHelp": "Korekta wysokości jest niezweryfikowanym szacunkiem liniowym. Wpisz zaobserwowaną różnicę i sprawdź strzałem próbnym. Wysokość terenu nie jest odczytywana.",
  "estimatedImpact": "Szacowane trafienie za",
  "timerElapsed": "Szacowany czas minął",
  "fireAgain": "Uruchom szacowany licznik ponownie",
  "imported": "Wczytano zadanie z mapy.",
  "importHelp": "Przywrócono odległość, azymut i skalę. Sprawdź różnicę wysokości przed strzałem.",
  "invalidImport": "Udostępnione dane ostrzału są niepełne lub nieprawidłowe i nie zostały wczytane. Wskaż pozycje na mapie albo wpisz odległość i azymut.",
  "correction": "Korekta trafienia",
  "title": "Koryguj według miejsca trafienia",
  "help": "Następny krok zmienia odległość o 5% (minimum 5 m) i azymut o 2°. To szacunek do wstrzeliwania; obserwuj kolejny strzał przed salwą.",
  "apply": "Zastosuj korektę",
  "range": "Odchylenie odległości",
  "lateral": "Odchylenie boczne",
  "short": "Za blisko",
  "on": "W cel",
  "long": "Za daleko",
  "left": "W lewo",
  "right": "W prawo",
  "line": "Na linii",
  "nextDistance": "Kolejna odległość",
  "nextAzimuth": "Kolejny azymut",
  "elevationCue": "Korekta podniesienia",
  "lateralCue": "Korekta boczna",
  "increase_mil": "Zwiększ mil",
  "decrease_mil": "Zmniejsz mil",
  "hold_mil": "Utrzymaj mil",
  "unavailable": "Niedostępne",
  "hold": "Utrzymaj",
  "log": "Dziennik ognia",
  "recent": "Ostatnie strzały",
  "clear": "Wyczyść dziennik",
  "empty": "Oddaj strzał z poprawnego rozwiązania, aby zapisać go na tym urządzeniu.",
  "audioOn": "Sygnały dźwiękowe włączone",
  "audioOff": "Dźwięk wyłączony",
  "invalid": "Korekta poza tabelą strzelania. Zmień odległość lub tor przed zastosowaniem."
},
};
export function getArtilleryMissionCopy(locale: string): ArtilleryMissionCopy {return copies[locale as Locale] ?? en;}
